### ISSUE TITLE
Soft Buttons sent via RPC disappear

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1000]
### Bug Report
On v5.2.0+, when sending a soft button via the Show RPC, they flicker, and appear then disappear.

> Nicole was chatting with me on Monday and she thought that the `screenManager` might be doing something things that were causing my screen display issues. Just to be clear, I updated from 5.11 to 5.20 and did not make a single change (still using RPCs), but my buttons were appearing and then disappearing instantly.  Using screen manager to handle button display fixed the disappearing issue, but looks like it requires me to transition several other things so RPCs and screenMgr dont collide.

##### Reproduction Steps
```
on hmiLevel didChangeToLevel:
if newLevel == .Full && manager is ready;
Upload a set of base images for icons if needed

Iterate on the 4 items (our 4 command types, like TodaysForecast or WeatherAlerts).
Make SDLAddCommands for the VR strings.
Make buttons for each command.
Send addcommand via manager
End repeat.
Add buttons via SDLShow via manager
Add help phrases to unit via SDLSetGlobalProperties

then
dispatch after 1 second: SDLSetDisplayLayout with SDLPredefinedLayoutTextAndSoftButtonsWithGraphic
```

##### Expected Behavior
Soft buttons remain on the screen

##### Observed Behavior
Soft buttons disappear

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: v.5.2.0+
* Testing Against: unknown

**Comment by JamaicanRumCream** [comment]
With 5.2.0, see video at:
https://www.dropbox.com/s/jgh8bp0buemwfjh/AccuWeather-SDL-5.2.0.MP4?dl=0
