### ISSUE TITLE
SDK sometimes hangs after disconnecting the USB cable between the iPhone and the Head Unit.

### ISSUE THREAD

**Issue by Lievesley** [smartdevicelink/sdl_ios#1002]
### Bug Report
iOS application sometimes hangs after disconnecting the USB cable connecting the iPhone to the Head Unit because threads become deadlocked.

##### Reproduction Steps (sometimes occurs usually with low frequency)
Reproduction steps (1):
1) Run app on iPhone.
2) Connect iPhone to Head Unit with USB cable.
3) Wait few minutes.
4) Disconnect iPhone from Head Unit.

Reproduction steps (2):
1) Run app on iPhone.
2) Connect iPhone to Head Unit with USB cable.
3) Disconnect iPhone from Head Unit and then continue to rapidly connect and disconnect the USB cable.

##### Expected Behavior
Application should not hang.

##### Observed Behavior
"Failed to cancel stream thread" message is logged by SDL SDK to console.
Application hangs in external accessory framework.

##### OS & Version Information
* iOS Version: 11.3
* SDL iOS Version: 5.2
* Testing Against: Harman head unit

**Comment by NicoleYarroch** [comment]
Could be related to issue #672

**Comment by Lievesley** [comment]
The PR is ready for review

**Comment by joeljfischer** [comment]
Fixed in #1011
