### ISSUE TITLE
manager.screenManager.textField2 thru 4 don't update properly

### ISSUE THREAD

**Issue by JamaicanRumCream** [smartdevicelink/sdl_ios#1009]
### Bug Report
When using screenManager to update the screen display, lines 2, 3, 4 don't update properly.

##### Reproduction Steps
Use some code similar to this:

```swift
guard let substrings = ["1", "2", "3", "4"]
self.manager.screenManager.beginUpdates()
                
self.manager.screenManager.textField1 = substrings[0].trimmingCharacters(in: .whitespacesAndNewlines)
 self.manager.screenManager.textField2 = substrings[1].trimmingCharacters(in: .whitespacesAndNewlines)
self.manager.screenManager.textField3 = substrings[2].trimmingCharacters(in: .whitespacesAndNewlines)
self.manager.screenManager.textField4 = substrings[3].trimmingCharacters(in: .whitespacesAndNewlines)
        
self.manager.screenManager.endUpdates(completionHandler: { (error) in })
```

##### Expected Behavior
Line  2, 3, 4 display whatever I'm setting it to display

##### Observed Behavior
Line 2,3, 4 keep the text that was first displayed the first time the app showed any text in those fields. No new calls to the views will change the text.

##### OS & Version Information
* iOS Version: 10.3.3
* SDL iOS Version: 6.0.0
* Testing Against: Sync 3 TDK hardware unit

**Comment by JamaicanRumCream** [comment]
Even worse, the screenManager has a mind of it's own. A second test now just showed me that text I had previously displayed in the fields is somehow being "appended" to new text. IE: First display of line 4: "poop". Updating line 4: "eating burritos and chips... - poop". Also I've seen text in 2 separate items in an array be concatenated like "A - B". Something very weird is going on with text handling.

**Comment by joeljfischer** [comment]
Hi @JamaicanRumCream, unfortunately, we have not seen this behavior at any point in the past, nor in any of our unit tests, which are fairly extensive for this class. If it's being set the first time and not subsequent times, perhaps you are calling `beginUpdates` without an `endUpdates`. If you are seeing concatenation, then the manager believes the head unit has fewer lines than 4 available to it, and it will automatically concatenate to use the number of lines available. If you are using a template with fewer than 4 lines, this is why that will appear.

**Comment by JamaicanRumCream** [comment]
Hi Joel (it's Chris), do you think that using RPC calls and screenMgr in the same app would do this? B/c it is pretty consistent for me in a certain set of operations, and I am doing some RPCs for one code block and screenMgr for other ones. At this point I have reverted to using only RPCs b/c they didn't exhibit this issue. Hoping 6.0.1 might fix some things. FWIW I don't think the screenMgr should assume things and do concatenation on strings. At least that should be documented how and when it's going to do that.

**Comment by joeljfischer** [comment]
For the first part (lines not changing), it's possible but unlikely, for the second (concatenation), definitely not. I hear what you're saying about automatic concatenation, but you have to understand that there is not just one head unit compatible with SDL. If the one you test against supports 4 lines of text and another on the market supports 3, then either a line will be missing, or you'll have to do the hundreds of lines of code we wrote yourself. The screen manager doesn't "assume" anything. It reads the `setDisplayLayout` response `displayCapabilities` to find the exact number of supported lines of text for the current template and adjusts accordingly. In the future, we may make the system more flexible, but I doubt we'll ever remove the automatic adjustment for the simple reason that having every developer do the compatibility checks themselves is unlikely to turn out well.

Multiple lines set, 1 available: "1 - 2 - 3 - 4"
Multiple set, 2 available: "1" "2 - 3" or "1 - 2" "3 - 4"
Multiple set, 3 available: "1" "2" "3 - 4"

The system is fairly simple, you can read it in the code if you'd like and debug. However, if you can create a minimum case app or (even better) unit test case displaying the issue, then we'll be able to solve your problem faster. As I said, this is not an issue we've seen on any of our test apps or unit tests.

**Comment by JamaicanRumCream** [comment]
OK, then just documenting that it'll concatenate "somehow" would be sufficient. It would seem a little non-intutive to set X lines, and then have it automatically concat, if I didn't expect that to happen. :-)
