### ISSUE TITLE
Enable Documentation Comments warning

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#101]
And fix all the warnings. So many warnings.

**Comment by justinjdickow** [comment]
We're going to need this at the same time that we're going to deliver an SDL developer portal documentation set. Not sure of the date yet

**Comment by NicoleYarroch** [comment]
@joel How do I re-enable the documentation comments warnings in Xcode?

**Comment by joeljfischer** [comment]
@NicoleYarroch The old setting appears to be gone, the new setting is currently enabled
