### ISSUE TITLE
Soft button activates handler function multiple times

### ISSUE THREAD

**Issue by JamaicanRumCream** [smartdevicelink/sdl_ios#1012]
Soft button #2 thru #4 fires the handler code 3 times, any time it is pressed.

##### Reproduction Steps
1. Build buttons and add them to `screenManager` with handlers that call a function by passing an integer.
2. Run app.
3. Press soft button on screen.
4. Soft button #1 works properly.
5. Soft button #2, 3, or 4 fires code multiple times.
6. Using voice command or menu cell works properly, only calls code 1x

See setup code below.

##### Expected Behavior
Any time a soft button is pressed, it activates the handler code 1 time.

##### Observed Behavior
On our layout we have 2 soft buttons + Menu button. Soft button #1 properly activates only 1 time when pressed. Soft button #2 fires the handler code 3 times, reliably. All soft buttons are "built" in the same fashion and added to the screenManager.softButtonObject arrays. Also test in layout with 4 soft buttons (and menu button in upper right), same behavior.

##### OS & Version Information
* iOS Version: 10.3.3 and 11.2.6
* SDL iOS Version: 6.0.0
* Testing Against: Sync 3 TDK hardware unit

Here is code for setting up the buttons. The plist is parsed which holds the commandIDs, translated strings for the buttons, etc. The parsedItems is an struct with string values where shown.
```
@objc func buildCommandsAndButtons() {
        guard let path = Bundle.main.path(forResource: "AWFordSyncCommands", ofType: "plist") else { return }
        guard let majorFunctionGroups = NSArray(contentsOfFile:path) else { return }
        let functionGroups = majorFunctionGroups as! [[String : Any]]
        
        var softButtons = [SDLSoftButtonObject]()
        var menuButtons = [SDLMenuCell]()
        var helpArray = [SDLTTSChunk]()
        
        for thisMenuItem in functionGroups {
            guard let parsedItems = commandObjects(from: thisMenuItem) else { continue }
            let commandID = parsedItems.commandID
                        
            //BUTTON
            var buttonImage: SDLArtwork? = nil
            if let iconImage = UIImage(named: parsedItems.softIconName) {
                buttonImage = SDLArtwork.init(image: iconImage, persistent: true, as: SDLArtworkImageFormat.PNG)
            }
            let softButtonObj = SDLSoftButtonObject.init(name: parsedItems.commandName, state: SDLSoftButtonState.init(stateName: "default", text: parsedItems.displayName, artwork: buttonImage)) { (onButtonPress, onButtonEvent) in
                    self.doCommandNamed(commandID)
            }
            softButtons.append(softButtonObj)
            
            //MENU BUTTON
            // for menus use long commandName instead of short soft(button)Name
            // VR commands are now triggered from the menu items (if menu item is present)
            let menuButton = SDLMenuCell.init(title: parsedItems.commandName, icon: buttonImage, voiceCommands: parsedItems.vrStrings) { (triggerSource) in
                self.doCommandNamed(commandID)
            }
            menuButtons.append(menuButton)
            
            //HELP ITEM
            if let cleanedString = AWFordTTSClean.cleanNoMinutes(parsedItems.vrStrings.first) {
                let help = SDLTTSChunk.init(text: cleanedString, type: SDLSpeechCapabilities.text)
                helpArray.append(help)
            }     
        }
        
        //add the created commands to the screen manager
        manager.screenManager.softButtonObjects = softButtons
        manager.screenManager.menu = menuButtons
        
        let globalProperties = SDLSetGlobalProperties()
        globalProperties.helpPrompt = helpArray
        manager.send(globalProperties)
    }
```

This is the code to fire the command. I am attaching breakpoints at the top of the method and in each case. BUTTON 2 IS MAPPED TO MINUTECAST FUNCTION  for me. I get breakpoint hits 3x on `displayMinuteCast()` method.
```
/** Perform the specific action, and log which one */
    @objc func doCommandNamed(_ commandID: Int) {
        var logName = "Ford AppLink - unknown"
        switch commandID {
        case FordCommandID.alerts.rawValue:
            displayAlertInformation()
            logName = "Ford AppLink - Alerts Screen"
        case FordCommandID.minuteCast.rawValue:
            displayMinuteCast()
            logName = "Ford AppLink - MinuteCast Screen"
        case FordCommandID.dailyForecast.rawValue:
            displayTodaysForecast(withSpeaking: true)
            logName = "Ford AppLink - Today Forecast Screen"
        case FordCommandID.lookingAhead.rawValue:
            displayLookingAheadForecast()
            logName = "Ford AppLink - Looking Ahead Screen"
        default:
            displayTodaysForecast(withSpeaking: true)
        }
        AWAnalyticsController.shared().logAction(ofType: AnalyticEventType.navigation, withName: logName, withTrigger: "Ford Screen")
    }
```

**Comment by SatbirTanda** [comment]
Check this line:
```swift
let softButtonObj = SDLSoftButtonObject.init(name: parsedItems.commandName, state: SDLSoftButtonState.init(stateName: "default", text: parsedItems.displayName, artwork: buttonImage)) { (onButtonPress, onButtonEvent) in
    self.doCommandNamed(commandID)
}
```

Notice you get a `onButtonPress, onButtonEvent` in the handler.
You must handle the gesture state, just like handling a regular iOS gesture:
```swift
 guard let buttonPress = onButtonPress else { return }
 switch buttonPress.buttonPressMode {
    case .short:
        print("Short Press!")
    default:
        print("Error!")
 }
```

**Comment by joeljfischer** [comment]
@SatbirTanda is correct. You are receiving 3 events. The touch down, the touch up, and the button press short, all of which occur in that event handler. This is noted [in the guides](https://smartdevicelink.com/en/guides/iOS/displaying-information/creating-the-user-interface/):

```swift
let softButtonObject = SDLSoftButtonObject(name: "<#Soft Button Object Name#>", states: [softButtonState1, softButtonState2], initialStateName: "") { (buttonPress, buttonEvent) in
    guard buttonPress != nil else { return }
    <#Button Selected#>
}
```

You usually want to ignore the event (touchdown / touchup) in favor of the buttonPress (short / long finished).

**Comment by joeljfischer** [comment]
@JamaicanRumCream Are the buttons different types of buttons? e.g. some are soft buttons, others are menu buttons? Menu buttons don't have that granular detail, they just tell you if they were pressed, so you'd only receive the notification once.

**Comment by JamaicanRumCream** [comment]
All the buttons I am talking about are the same type. I have menu cell "buttons" and they work correctly. So it's just the first button of the 4 **soft buttons** that acts differently. But all the soft buttons are built together the same way (code I showed). Which is why I considered this a bug, as 1 was different. I'd understand if all 4 gave me 3 responses, that would make sense I was not handling the return event correctly.
