### ISSUE TITLE
RPC operation queue decreases performance

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_ios#1020]
### Bug Report
Sometimes I have noticed a poor performance on some iOS apps using the lifecycle manager. An app partner just reported a very bad performance in one of their use cases where Show requests are delayed heavily.

Reviewing the code I found a concurrent limit [here](https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLLifecycleManager.m#L117)

```objc
    _rpcOperationQueue.maxConcurrentOperationCount = 3;
```

This reduces the number of concurrent operations to three. Worse case each operation handles a single request. The performance issue can be seen with hello_sdl_ios in version 6.

I can understand the idea behind the limit but from my point of view it's too aggressive. It's also not protecting the library or the head unit from too many requests. Last the limit is not really visible to app developer being surprised about the poor performance.

Not sure why the limit is set to 3. I would expect the limit to be increased (16? 50?) and related to requests, not operations.

##### Reproduction Steps
1. Build and install Hello SDL on your iPhone
2. Connect your iPhone to a head unit
3. Wait for Hello SDL to register
4. Start Hello SDL then tap on the soft buttons as soon as they are shown
5. Wait ~30 seconds then tap on the soft buttons again

##### Expected Behavior
In step 4 and 5 the buttons should change the screen immediately
(Show requests should be sent right after the button is tapped)

##### Observed Behavior
In step 4 the screen changes take a few seconds
In step 5 the screen changes appear (almost) immediately

##### OS & Version Information
* iOS Version: 11.4 (but should appear on any version)
* SDL iOS Version: 6.0 (but should appear since 5.2.0)
* Testing Against: Hello SDL iOS

**Comment by joeljfischer** [comment]
The limit has been removed and is now handled by iOS; do you see the same issue on the sdl_ios 6.5.0?

**Comment by E-SAITO-TMC** [comment]
@kshala-ford -san  Is this issue resolved?  Is this occur in the latest version? 
@theresalech -san  This issue is a medium priority for Toyota. If this issue is not resolved, could you please include this in your plan? Thank you.

**Comment by joeljfischer** [comment]
@E-SAITO-TMC The issue as reported has been resolved. We have been waiting for the reporter to respond to the issue. There is no longer a 3 operation limit on the concurrent queue. If you are seeing different behavior, please let us know. We will close the issue as resolved unless yourself or the reporter responds.
