### ISSUE TITLE
[SDL 0167] App Services

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#1023]
Proposal: [App Services](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md)

> SmartDeviceLink has always been limited to a 1 - 1 relationship between module and smartphone apps. However, to create truly compelling experiences this should be expanded. This proposal will aim to introduce a paradigm that allows apps to advertise a "service" they offer that the module and other apps can leverage. This allows users to augment their vehicle's IVI system with off-board solutions. This proposal also details how SDL apps can communicate with each other through the module.

> This proposal is extremely lengthy as it is a big feature. The recommended review process would be to review the high level process first (publish, subscribe, etc). Then following the agreement on how services work in general, moving to review each service type for its exhaustiveness of functionality per that specific service.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/485

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions, pending individual service reviews. Separate evolution issues will be raised for each of the services in the upcoming weeks, with 1 service being reviewed per week. The revisions to this proposal are outlined in this comment and this comment.
> The proposal was revised to incorporate these revisions on July 12, 2018.

**Comment by theresalech** [comment]
Closing this issue for now, as Steering Committee reviews of individual services included in the proposal will need to take place before the implementation of the proposal can begin.

**Comment by jordynmackool** [comment]
The below PR revisions have been accepted and implemented: 

https://github.com/smartdevicelink/sdl_evolution/pull/679
https://github.com/smartdevicelink/sdl_evolution/pull/673
https://github.com/smartdevicelink/sdl_evolution/pull/671
