### ISSUE TITLE
SDL crashes on [EASession initWithAccessory:forProtocol:]

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1025]
[2018-06-17_21-29-12.0027_-0700-96b048f07dabb8b196808f33f9c9205b5cb0cec1.txt](https://github.com/smartdevicelink/sdl_ios/files/2190426/2018-06-17_21-29-12.0027_-0700-96b048f07dabb8b196808f33f9c9205b5cb0cec1.txt)

### Bug Report
TIDAL app crashes occasionally at `[EASession initWithAccessory:forProtocol:]` 

##### Reproduction Steps
Unknown

##### Expected Behavior
App does not crash

##### Observed Behavior
App crashes

##### OS & Version Information
* iOS Version: 11.4.0
* SDL iOS Version: 5.2.0
* Testing Against: iPhone X; Unknown Head Unit

**Comment by brettywhite** [comment]
Hi @SatbirTanda 

Could you please provide more information? Can you reproduce this on any other SDL app? It is difficult to tell if it is a problem with the implementation or the library itself. Knowing the head unit type would probably also help.

Thanks

**Comment by joeljfischer** [comment]
Without more information, we are unfortunately unable to reproduce this issue. Please update with additional information and we can reopen this issue.
