### ISSUE TITLE
Assets are not downloaded when using `.../Swift` to install library via CocoaPods

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1026]
### Bug Report
The lock screen assets are not downloaded when using `SmartDeviceLink/Swift` to install the library via CocoaPods. This causes a crash if the developer is using the default lock screen.

##### Reproduction Steps
1. Install library in project using `pod 'SmartDeviceLink/Swift', '~> 6.0'`.
2. Use the default lock screen when setting up the`SDLConfiguration`.
3. Connect to a head unit.

##### Expected Behavior
The app should not crash

##### Observed Behavior
The app crashes

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.0 and probably previous versions
* Testing Against: n/a

**Comment by MichaelCrimando** [comment]
Hmm, so is it possible to get a lock screen working on a swift project? We were hitting issues with this

**Comment by NicoleYarroch** [comment]
@MichaelCrimando `pod SmartDeviceLink/Swift` is only if you want to add custom SDL logging to a Swift project. Use `pod 'SmartDeviceLink'` for both Swift and Obj-C projects.

**Comment by rbright55** [comment]
Added both pods to the project. Crash occurs when using CarWindow with the lockscreen enabled.

**Comment by NicoleYarroch** [comment]
@rbright55 What kind of error are you seeing in the Xcode logs? Is it crashing because the lock screen assets are not in the project or for some other reason?

**Comment by rbright55** [comment]
@NicoleYarroch I added both `pod 'SmartDeviceLink','~> 6.0.1'` and `pod 'SmartDeviceLink/Swift','~> 6.0.1'`  which added the lock screen assets. 
The crash comes when the app tries to dismiss the lock screen.

**Comment by NicoleYarroch** [comment]
@rbright55 Are you using the default lock screen configuration or a custom lock screen config? I'm not seeing any issues with the the default lock screen and `CarWindow` in v.6.0.1. What error message do you get on crash?

**Comment by NicoleYarroch** [comment]
I think the crash is happening because the `imageWidth` (375)  and `imageHeight` (618)  are different from the `imageRef`s width and height (800, 348). Does your `rootViewController` subclass the `SDLCarWindowViewController`?

**Comment by rbright55** [comment]
yes it is a SDLCarWindowViewController

**Comment by rbright55** [comment]
It is set in the `viewDidAppear` method

**Comment by NicoleYarroch** [comment]
Hmm. I'm not sure what is causing the crash then. I need more detail about what is happening. Can we move this discussion to the iOS SDL slack channel (http://slack.smartdevicelink.com)?

1. Are you connecting to a TDK via iAP or to an emulator via TCP?
1. The default configuration lock screen is showing correctly, but it crashes when dismissed with an `OnDriverDistraction` notification?
1. Did you rotate the device before the lock screen was dismissed?
1. Is the `rootViewController` a mirror of what is being displayed on the phone app or is it an off-screen view controller?
