### ISSUE TITLE
SDLLogModel Not included in public header files

### ISSUE THREAD

**Issue by rbright55** [smartdevicelink/sdl_ios#1041]
### Bug Report
SDLLogModel.h is not included in the public header files. This is useful to get more information than just the formatted log string when creating a new SDLLogTarget.

##### Reproduction Steps
1. Setup new SDLLogTarget
2. Try to access the message or loglevel property of the SDLLogModel in the logWithLog function 

##### Expected Behavior
should be able to access the SDLLogModel variable

##### Observed Behavior
Properties from log:SDLLogModel object included in the logWithLog function cannot be accessed

##### OS & Version Information
* SDL iOS Version: 6.0.1

##### Test Case, Sample Code, and / or Example App
* Tested while updating Ford internal test app

**Comment by joeljfischer** [comment]
Hi @rbright55, thanks for the issue. However, this is not a bug, it was an intentional feature design to allow us to change the internal model as needed without version changes. If you want this to change, it would need to be through an [SDL Evolution Proposal](https://github.com/smartdevicelink/sdl_evolution).

**Comment by rbright55** [comment]
Without this file included, I had to manually move it to the public header files and add it in the SmartDeviceLink-umbrella.h  so that I could setup a SDLLogTarget in swift. 

Otherwise xCode will display the error "cannot conform to protocol 'SDLLogTarget' because it has requirements that cannot be satisfied"

**Comment by joeljfischer** [comment]
I understand, but this isn't the right forum for a feature request / API change.
