### ISSUE TITLE
Video streaming notifications not sent when light sensor is covered/uncovered

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1044]
### Bug Report
When the light sensor is covered, a `sdlVideoStreamDidStop` notification is broadcasted, however, when the light sensor is uncovered, the corresponding `sdlVideoStreamDidStart` notification is not broadcasted. 

##### Reproduction Steps
1. Connect phone to head unit
1. Open video streaming app on head unit. Video should be streaming
1. Cover the light sensor on the phone. The screen will go black. A `sdlVideoStreamDidStop` notification is broadcasted
1. Uncover the light sensor on the phone.

##### Expected Behavior
When the light sensor is covered the `sdlVideoStreamSuspended` notification should be sent; `sdlVideoStreamDidStart` on uncovering.

##### Observed Behavior
When the light sensor is covered the `sdlVideoStreamDidStop` notification is sent; no notification is sent on uncovering.

##### OS & Version Information
* iOS Version: ??
* SDL iOS Version: ??
* Testing Against: ??

**Comment by NicoleYarroch** [comment]
@Lievesley 
So this only happens when:
1. The phone is connected to the head unit & video is streaming
1. The user accepts a phone call or makes a phone call
1. The user somehow covers the proximity sensor on the phone during the phone call
1. When the phone call ends, the SDL app returns to the foreground on the head unit and the app on the phone returns to the foreground but the video does not resume.

**Comment by theresalech** [comment]
Closing as unreproducible.
