### ISSUE TITLE
Add the ability to use static icons to the Screen Manager

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1045]
### Bug Report
Developers using the `ScreenManager` API can not use static icons in their menus or soft buttons.  
1. A variant of `SDLArtwork` should be created that will take a static icon name.
1. Since static icons do not need to be uploaded before being shown, the `ScreenManager` needs to skip uploading the `SDLArtwork` if it is a static icon. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.0
* Testing Against: n/a

**Comment by joeljfischer** [comment]
This is not a bug. Because it is a feature, it would have to be proposed through the SDL Evolution process.
