### ISSUE TITLE
Video session is not closed in suspended state when HMI level become BACKGROUND or NONE

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#1047]
### Bug Report
Video session is not closed in suspended state when HMI level become BACKGROUND or NONE. Session should be closed even in suspended state.

Most HMI have only 1 video resource (decorder, screen, etc.). So, SDL proxy and SDLCore should close session (send Navigation.StopStream to HMI from SDLCore) at appropriate timing. 

##### Reproduction Steps
1. Activate VPM app1 to FULL. App1 starts video streaming
2. Make app1 inactive. Video streaming state of app1 becomes SUSPENDED.
3. Activate VPM app2 to FULL and VPM app1 is changed to BACKGROUND

##### Expected Behavior
4. VPM app1 stops video streaming session

##### Observed Behavior
4. VPM app1 does NOT stop video streaming session

##### OS & Version Information
* iOS Version: 10.3.3, 11.1
* SDL iOS Version: v6.0.1
* Testing Against: Our internal devboard HU

##### Test Case, Sample Code, and / or Example App
I will create PR and will update test case.

**Comment by joeljfischer** [comment]
@t-yoshii Many changes have been made to these classes on the `develop` branch. Please take a look and let us know if this is still an issue on that branch.

**Comment by joeljfischer** [comment]
Never mind, I see that this is against develop. Your `SDL iOS Version` is therefore incorrect. It should have specified `6.1-develop` or a commit entry, not `6.0.1` which has a very different streaming manager. If it affects both, then let us know. It may be worth a hotfix against `master`.

**Comment by t-yoshii** [comment]
@joeljfischer Thanks for your comments and sorry for incorrect version.

I confirmed that this issue occurs both on 6.0.1 and 6.1-dev (3cb0f3be950203b8c0737ffe36debb2628d8d707). Should I create different PR for master?

**Comment by joeljfischer** [comment]
Yes, that would be helpful.

**Comment by t-yoshii** [comment]
Created PR #1049 for master branch.
