### ISSUE TITLE
How does Heartbeat work on iOS?

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#106]
When I was testing [App Launching](https://github.com/smartdevicelink/sdl_core/tree/develop#app-launching), I noticed that if the [Heartbeat Timeout](https://github.com/smartdevicelink/sdl_core/blob/develop/src/appMain/smartDeviceLink.ini#L53) is set to anything but 0, the iOS applications disconnect after the configured number of seconds before reconnecting.

Does the developer have some responsibilities to implement or enable heartbeat?

**Comment by joeljfischer** [comment]
@smartdevicelink/ios We are still looking for an answer here

**Comment by justinjdickow** [comment]
@hugh22 @adein Could we please get an answer here?

**Comment by justinjdickow** [comment]
@hugh22 @adein Bump

**Comment by adein** [comment]
I have no idea.  I'll see if Stefan or someone can give me some info.

**Comment by Heath-FoMoCo** [comment]
@khburdette
Adding Kevin.  He did much of the architecture behind Heartbeat.

**Comment by khburdette** [comment]
- The heartbeat is a protocol V3 feature and is sent on the control service (0x00) as protocol messages.
- Heartbeat should start immediately after first StartService.
- Every session is responsible for it’s own heartbeat.
- Both the mobile proxy and core need to have the capability to send a heartbeat and respond to a heartbeat.
- Each side is responsible for letting the other side know it’s there. Sending data and/or RPC’s satisfies this requirement.
- If no data or RPC’s are being exchanged from either side, it is the responsibility of the mobile to send the heartbeat.
    - Use case: Media app finishes all the command and control it needs and begins streaming via A2DP
        - App could play an entire song before sending another RPC
        - Mobile should send a heartbeat every X seconds to keep it’s connection alive
    - Use case: Navigation app is streaming H.264
        - If core relies on another component for it’s service data ACK (eg. a gstreamer callback), it could wait longer on this component than the heartbeat allows for
        - Because the mobile is sending the H.264, it is satisfying it’s requirement to let core know it’s still there
        - Core should send a heartbeat every X seconds to keep it’s connection alive
    - Use case: mobile is sending something to core that doesn’t require a response (doesn’t currently exist)
        - Because the mobile is sending this, it is satisfying it’s requirement to let core know it’s still there
        - Core should send a heartbeat every X seconds to keep it’s connection alive
- Both the mobile proxy and core should keep track of the heartbeat in both directions:
    - If the mobile proxy hasn’t sent a message to core in X seconds it should send a heartbeat and if core hasn’t sent a message to the mobile proxy in X seconds it should send a heartbeat.
    - If the mobile proxy doesn’t see a message from core in N seconds it should close the connection and if core hasn’t seen a message from the mobile proxy in N seconds it should close the connection.
- Any and all activity will reset the heartbeat timer.

**Comment by justinjdickow** [comment]
@khburdette For iOS specifically, is the app developer responsible for sending and responding to heartbeats?

I see [sendHeartbeat](https://github.com/smartdevicelink/SmartDeviceLink-iOS/blob/develop/SmartDeviceLink-iOS/SmartDeviceLink/SDLProtocol.h#L14) in the `SDLProtocol` class but it doesn't have any callers. Besides that I noticed

```obj-c
    if (self.version >= 3) {
        // start hearbeat
    }
```

In the `-[handleProtocolSessionStarted:sessionID:version]` method, so it seems like it's an incomplete implementation?

**Comment by joeljfischer** [comment]
@khburdette @hugh22 @Heath-FoMoCo We're still waiting for an answer here

**Comment by justinjdickow** [comment]
@khburdette @adein 
We have a proxy that is negotiating Version 4 right now, and if there are head units that say version 3 to start sending heartbeats which disconnect after the timeout we're going to have a problem. We need to figure out the priority on this issue and select and milestone and assign someone asap.
