### ISSUE TITLE
Build fails in SDLStreamingVideoLifecycleManagerSpec.m on latest `develop` branch

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_ios#1063]
### Bug Report
On latest `develop` branch, build fails with a unit test file (SDLStreamingVideoLifecycleManagerSpec.m.)

##### Reproduction Steps
1. Check out commit 4b343d37705f495eb782a8b0798c2c27d4314a87
2. Start unit testing on Xcode

##### Expected Behavior
Unit tests are compiled and tests run.

##### Observed Behavior
Xcode detects following errors during build:
```
/path/to/sdl_ios/SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:322:78: Too few arguments to block call, expected 2, have 1
```
```
/path/to/sdl_ios/SmartDeviceLinkTests/DevAPISpecs/SDLStreamingVideoLifecycleManagerSpec.m:326:96: Use of undeclared identifier 'SDLVideoStreamStateShuttingDown'; did you mean 'SDLVideoStreamManagerStateShuttingDown'?
```

##### OS & Version Information
* Xcode Version: 9.4.1
* SDL iOS Version: latest `develop` branch, commit 4b343d37705f495eb782a8b0798c2c27d4314a87
* Testing Against: N/A

**Comment by NicoleYarroch** [comment]
Fixed with pull request #1040
