### ISSUE TITLE
[SDL 0198] - Media Skip Indicators

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_ios#1080]
Proposal: [Media Skip Indicators](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0198-media-skip-indicators.md)

> This feature is similar to [SDL-0109 Audio Streaming Indicator](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0109-set-audio-streaming-indicator.md) except that it affects the next and previous buttons. These buttons should have the ability to show time skip buttons that are commonly used by podcast & audiobook media. 

Review: https://github.com/smartdevicelink/sdl_evolution/issues/596

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the following revisions:
- Incorporate the feedback agreed to [in this comment](https://github.com/smartdevicelink/sdl_evolution/issues/596#issuecomment-418749992) by the author.
 - Ensure that conditions of `SeekIndicatorType` are documented, as requested [in this comment](https://github.com/smartdevicelink/sdl_evolution/issues/596#issuecomment-418755274). 

> The proposal .md file was updated to reflect these revisions on 9/20/18.

**Comment by NicoleYarroch** [comment]
Fixed in PR #1865.
