### ISSUE TITLE
[SDL 0199]-Adding-GPS-Shift-support 

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_ios#1083]
Proposal: [Adding GPS Shift support](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0199-Adding-GPS-Shift-support.md)

> To add shifted param for GPS data struct so that HMI can communicate to app when GPS data is shifted using an algorithm

Review: https://github.com/smartdevicelink/sdl_evolution/issues/598

Steering Committee Decision:

> The Steering Committee fully agreed to accept this proposal on 2018-09-25.

**Comment by theresalech** [comment]
Closed via #1299
