### ISSUE TITLE
App keeps trying to register even though it gets unregistered with a response of SDLAppInterfaceUnregisteredReasonAppUnauthorized

### ISSUE THREAD

**Issue by MichaelCrimando** [smartdevicelink/sdl_ios#1084]
##### Reproduction Steps
1. Connect iphone to a Ford 4" SYNC3 system via USB
2. Launch the test navigation app on the phone.
3. Observe the app traces

##### Expected Behavior
App registers once, the system unregisters it with reason When app gets unregistered with a response of SDLAppInterfaceUnregisteredReasonAppUnauthorized, the App doesn't try to register again until next ignition cycle.

##### Observed Behavior
App registers once, the system unregisters it with reason When app gets unregistered with a response of SDLAppInterfaceUnregisteredReasonAppUnauthorized, and the app keeps trying to register over and over again. (About once every 5 seconds)

##### OS & Version Information
* iOS Version: 11.4.1
* SDL iOS 6.0.1
* Testing Against: Using our Ford Mobile Navigation test app (Antelope v4) On Ford SYNC3 4", Mobile Navigation is not supported. So the system is trying to unregister the apps with reason SDLAppInterfaceUnregisteredReasonAppUnauthorized, but the app keeps trying infinitely over and over again

##### Test Case, Sample Code, and / or Example App
6.0.1 has a tiny bit of extra code on top of this, but we're trying to utilize this fix:
https://github.com/smartdevicelink/sdl_ios/pull/978/files

The system successfully goes into this call, but the behavior is not correct
[self.lifecycleStateMachine transitionToState:SDLLifecycleStateStopped];

**Comment by MichaelCrimando** [comment]
Heres the log from our app
[AntelopeLog_20180927_101920.zip](https://github.com/smartdevicelink/sdl_ios/files/2424965/AntelopeLog_20180927_101920.zip)

**Comment by joeljfischer** [comment]
In what way is that behavior not correct? It should not be attempting to reconnect if it transitions to the stopped state, right?

**Comment by MichaelCrimando** [comment]
Yea, I expect the app to stop registering when it goes to the stopped state. The problem is that it gets sent to the stopped state but then tries to re-register over and over again.  

We actually ended up doing a work around in SYNC where SYNC just tells the app that it registered, but doesn't show it on the display

**Comment by NicoleYarroch** [comment]
See related issue #1097

**Comment by NicoleYarroch** [comment]
Fixed in PR #1232
