### ISSUE TITLE
Switching from iAP connection to TCP/IP locks up app for ~5 minutes or until app connects to headhunt

### ISSUE THREAD

**Issue by MichaelCrimando** [smartdevicelink/sdl_ios#1086]
### Bug Report
Switching from iAP connection to TCP/IP locks up app for ~5 minutes or until app connects to headhunt

##### Reproduction Steps
1. Have a test app that can toggle between iAP or TCP/IP connection
2. Have the app set to iAP connection
3. Get the app setup to connect via TCP/IP
4. Cycle the proxy using 

##### Expected Behavior
App searches for TCP/IP connection in the background

##### Observed Behavior
App locks up for 5 minutes or until app connects to headunit

##### OS & Version Information
* iOS Version: 11.4.1
* SDL iOS 6.0.1
* Testing Against: Using our not-quite-released Ford Mobile Navigation test app (Antelope v4.X) On SYNC3 Emulator

##### Test Case, Sample Code, and / or Example App
Related PR #818 
Wrapping the SDLTCPTransport.m code in an Async background thread call seems to fix the problem

```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        __strong typeof(self) strongself = weakself;
        SDLLogD(@"Attemping to connect");

        int sock_fd = call_socket([self.hostName UTF8String], [self.portNumber UTF8String]);
        if (sock_fd < 0) {
            SDLLogE(@"Server not ready, connection failed");
            return;
        }
        
        CFSocketContext socketCtxt = {0, (__bridge void *)(self), NULL, NULL, NULL};
        strongself->socket = CFSocketCreateWithNative(kCFAllocatorDefault, sock_fd, kCFSocketDataCallBack | kCFSocketConnectCallBack, (CFSocketCallBack)&TCPCallback, &socketCtxt);
        CFRunLoopSourceRef source = CFSocketCreateRunLoopSource(kCFAllocatorDefault, strongself->socket, 0);
        CFRunLoopRef loop = CFRunLoopGetCurrent();
        CFRunLoopAddSource(loop, source, kCFRunLoopDefaultMode);
        CFRelease(source);
    });

```

**Comment by MichaelCrimando** [comment]
I'll get a hello SDL app made up with this specific thing

**Comment by MichaelCrimando** [comment]
Well before trying this out with Hello SDL, I gave the develop branch a try in our navigation app, Antelope.  The develop version TCP library works just fine and doesn't have this issue. 
Another job well done.

@joeljfischer Any ideas as to when this will be released?

**Comment by joeljfischer** [comment]
@MichaelCrimando You can see upcoming releases and dates here: https://github.com/smartdevicelink/sdl_ios/projects

Also, as a reminder, hello_sdl is no longer supported, and the repository has been deleted. Use the example apps within the sdl_ios repository instead.
