### ISSUE TITLE
If ChoiceSetManager gets a `nil` displayCapabilities it should fail gracefully

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1089]
### Bug Report
There's a bug in current gen Generic_HMI (v. 0.4.1) causing any `SetDisplayLayoutResponse` to pass `nil` `displayCapabilities`. This causes some oddities in the `ChoiceSetManager`. We should disable functionality if this occurs and send errors to the dev's attention.

##### Reproduction Steps
1. Connect to an HMI that doesn't sent `displayCapabilities`
2. Attempt to upload choices through the `ChoiceSetManager`

##### Expected Behavior
Clear error logs are logged

##### Observed Behavior
Choices fail to upload, interactions to present, etc.

##### OS & Version Information
* iOS Version: 12.0.0
* SDL iOS Version: 6.1-develop
* Testing Against: Manticore (Core v4.5 / Generic HMI 0.4.1)

**Comment by NicoleYarroch** [comment]
@joeljfischer Didn't this issue get fixed in #1108?

**Comment by joeljfischer** [comment]
Yep!
