### ISSUE TITLE
Manager reconnects after receiving a `OnAppInterfaceUnregistered` notification

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1097]
### Bug Report
The lifecycle manager attempts to reconnect to Core after receiving a `OnAppInterfaceUnregistered` notification with a reason code of `PROTOCOL_VIOLATION`. 

Currently the `SDLLifecycleManager` only stops the manager if the reason code is `APP_UNAUTHORIZED`. It should also stop the manager if the reason code is a `PROTOCOL_VIOLATION`. 

##### Reproduction Steps
1. Connect a video streaming app with `appType` of `NAVIGATION` to a head unit that does not support video streaming. When the video streaming manager sends a video start service request, Core responds with following error:
```
[Proxy] Unregistration forced by module. {
    notification =     {
        correlationID = 4294967295;
        name = OnAppInterfaceUnregistered;
        parameters =         {
            reason = "PROTOCOL_VIOLATION";
        };
    };
}
```

##### Expected Behavior
The lifecycle manager should stop and not attempt to reconnect to Core.

##### Observed Behavior
The lifecycle manager attempts to reconnect to Core.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.1
* Testing Against: Generic HMI + SDL Core v5.0

**Comment by NicoleYarroch** [comment]
Looks like it is more complicated than I originally thought as there appears to be a race condition in the lifecycle manager. 
When the proxy closes, the lifecycle manager transitions to state reconnecting (L647). Then immediately afterwards, when the `SDLOnAppInterfaceUnregistered` notification is received, it transitions to state stopped (L728). However the lifecycle manager has already been restarted and a connection is established...

**Comment by joeljfischer** [comment]
Perhaps we should be delaying reconnecting based on a proxy closing to see if we get an unregister notification?
