### ISSUE TITLE
Crash occurs if SDLSoftButtonObject has SDLSoftButtonState with both nil text and image

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1126]
### Bug Report
Create a softButtonObject with a SDLSoftButtonState that has nil for text and image.  SDL Crashes at `sdl_hasTwoStatesOfSameName:(NSArray<SDLSoftButtonState *> *)states` in `SDLSoftButtonObject` and crashes the app/

##### Reproduction Steps
1. Call screenManager.beginUpdates()
2. Create a softButtonObject with a SDLSoftButtonState that has nil for text and image.  Set softButtonObjects property of screenManager.
3. Call screenManager.endUpdates()

##### Expected Behavior
Display empty button?

##### Observed Behavior
App crashes

##### OS & Version Information
* iOS Version: 11.0
* SDL iOS Version: 6.1.0
* Testing Against: SYNC 3 MY 18

**Comment by NicoleYarroch** [comment]
If you try to create a `SDLSoftButtonState` with both `text` and `image` as `nil`, the object will not be created and will return `nil`. Currently we expect the user to check if their `SDLSoftButtonState` object is `nil` before passing it to the screen manager.

https://github.com/smartdevicelink/sdl_ios/blob/4741ad60a90dbcc9d2065b1cdd4954486773d9b5/SmartDeviceLink/SDLSoftButtonState.m#L39-L54

**Comment by joeljfischer** [comment]
Instead of returning `nil`, we should probably assert to help with debugging.

**Comment by joeljfischer** [comment]
@BrettyWhite Is this an issue with android as well?

**Comment by NicoleYarroch** [comment]
Fixed in PR #1135
