### ISSUE TITLE
SDLChoiceSetManager does not remove InteractionChoiceSet (ID: 0) after sdl_sendTestChoices

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#1129]
### Bug Report
SDLChoiceSetManager does not remove InteractionChoiceSet (ID: 0) after sdl_sendTestChoices.

SDLChoiceSetManager creates following choice set and does not delete it.
https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLCheckChoiceVROptionalOperation.m#L73

##### Reproduction Steps
1. Connect SDL iOS app using SDL manager
2. Send CreateInteractionChoiceSet with id 0
3. Send PerformInteraction with ChoiceSet id 0

##### Expected Behavior
2. RPC succeed.
3. User see the choices list which are sent at Step 2.

##### Observed Behavior
2. RPC fails with "INVALID_ID" because ID:0 is already used.
3. User see unexpected list "Test cell" and "Test VR".

##### OS & Version Information
* iOS Version: iOS11, 12
* SDL iOS Version: 6.1.1
* Testing Against: Our intenal devboard. Ford SYNC devboard

##### Test Case, Sample Code, and / or Example App
https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLCheckChoiceVROptionalOperation.m#L73

**Comment by joeljfischer** [comment]
Generally, you should not mix using a manager with using the RPC directly, so this bug is minor. However, we will fix it for the next minor release.
