### ISSUE TITLE
[SDL 0211]-Service Status Update to HMI

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_ios#1141]
Proposal: [Service Status Update to HMI](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0211-ServiceStatusUpdateToHMI.md)

> This proposal is about adding a new RPC called 'OnServiceUpdate' which will be used by the HMI layer to know the status of certain services from SDL Core.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/641

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions on 2018-12-18. The author is to update the proposal to include both the Audio and RPC services discussed in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/641#issuecomment-447112795) and adding an optional 'appID' parameter to the OnServiceUpdate RPC as noted in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/641#issuecomment-448337280). 

Revisions were made on 2018-12-20

**Comment by theresalech** [comment]
It was determined updates`android` are not required for this feature, as it only makes changes to the hmi_api and core.
