### ISSUE TITLE
[SDL 0208]- Block Old SDL Head Units from Mobile

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_ios#1142]
Proposal: [Block Old SDL Head Units from Mobile](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0208-block-sdl-head-units.md)

> This proposal adds a way for proxy apps to block older head units via protocols or RPC versions.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/635

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions on 2018-12-11. The author will alter the proposal to have the protocol and RPC versions changed to be version objects like the Android native version object.

Revisions were made on 2018-12-20

**Comment by NicoleYarroch** [comment]
Closed via PR #1164
