### ISSUE TITLE
Crash if car doesn't support vr

### ISSUE THREAD

**Issue by mvyrko** [smartdevicelink/sdl_ios#1153]
if car doesn't support vr then app crashed.
 
### Bug Report
In function `- (void)sdl_registerResponse:(SDLRPCResponseNotification *)notification `
when we try to set self.vrCapability and check number of capabilities then we crash with 
`[NSNull count]: unrecognized selector sent to instance`

##### Reproduction Steps
1. run app
2. connect car without vr

##### Expected Behavior
No, crash here

##### Observed Behavior
Crash

##### OS & Version Information
* iOS Version: Any
* SDL iOS Version: 6.1.0

##### Test Case, Sample Code, and / or Example App
![screen shot 2019-02-06 at 15 38 42](https://user-images.githubusercontent.com/11045737/52342052-5cc3c080-2a25-11e9-9018-eff28db0aecc.png)

**Comment by mvyrko** [comment]
Hello, @kshala-ford.
Last month we have 50k crashes with problem above and we really need to have a fix of problem.
Unfortunately, I don't know car models that send `"displayCapabilities" { "vrCapabilities": null, .... }`. I tried to analyze SDL documentation but I haven't found information about it.
Anyway `"displayCapabilities" { "vrCapabilities": null, .... }` is valid JSON format and we need to correct work with it. Please, take a look my solution for all places where can be NSNull instead of expected object.
Thank you

**Comment by kshala-ford** [comment]
@mvyrko I'm sorry. I actually was saying that SDL doesn't use "null" within JSON (though it's valid JSON format). The car should not send "vrCapabilities" instead of using `null` to inform the app about "No VR support". I was hoping to identify the manufacturer to inform about the issue and in the same time fix the issue in sdl_ios to be protected from JSON null.

Anyways for you it should be transparent. I am currently working on a solution that fixes null issues.

**Comment by mvyrko** [comment]
@kshala-ford as far as I see problem the problem is wider the null in vrCapabilities.
On our project we have a lot of crashes where SDL cast value from dictionary to property without checking type of it. `- (nullable id)sdl_objectForName:(SDLName)name`
```-[NSNull count]: unrecognized selector sent to instance 0x1e99699d0```
```-[__NSDictionaryI firstObject]: unrecognized selector sent to instance 0x282447e80```
```-[__NSCFNumber isEqualToEnum:]: unrecognized selector sent to instance 0xecbbf7f37a5c3eb2```
All of these crashes because dictionary contains another value then sdl_ios expect.
I suggest to remove method above at all.

**Comment by NicoleYarroch** [comment]
@mvyrko Can you tell me where `-[__NSDictionaryI firstObject]: unrecognized selector sent to instance 0x282447e80` crash is happening?

**Comment by NicoleYarroch** [comment]
@mvyrko Also can you tell me where the `-[NSNull count]: unrecognized selector sent to instance 0x1e99699d0` is happening?

**Comment by NicoleYarroch** [comment]
> @mvyrko Also can you tell me where the `-[NSNull count]: unrecognized selector sent to instance 0x1e99699d0` is happening?

I assume this crash is happening after you applied [kshala-ford](/kshala-ford)'s fix in this PR.

**Comment by mvyrko** [comment]
Crash [NSNull count] happens on **SDL iOS Version: 6.1.0**
In SDLSystemCapabilityManager line 104(you can see on screenshot above)
 ```self.vrCapability = (response.vrCapabilities.count > 0 && [response.vrCapabilities.firstObject isEqualToEnum:SDLVRCapabilitiesText]) ? YES : NO;``` 
I think that `vrCapabilities` is `NSNull` and when code tries check number of items in it(`response.vrCapabilities.count > 0`) then crash happens

**Comment by mvyrko** [comment]
About [NSDictionary firstObject]:
![screen shot 2019-02-13 at 12 18 11](https://user-images.githubusercontent.com/11045737/52700733-b2e6b580-2f89-11e9-9290-59e08609f1b5.png)
NSMutableDictionary+Store.m line 40
`} else if (array.count < 1 || [array.firstObject isMemberOfClass:classType]) {`

**Comment by mvyrko** [comment]
In my view, all these bugs can be fixed by PR https://github.com/smartdevicelink/sdl_ios/pull/1158

**Comment by kshala-ford** [comment]
@mvyrko can you please create another issue regarding the NSDictionary crash? Here's my offer: We should be able to provide you a hotfix release very soon with all three issues fixed so the app won't crash anymore. Your PR #1158 is definitely the right way to got for long term, however it requires a minor version release.

**Comment by mvyrko** [comment]
@kshala-ford NSDictionary crash issue - https://github.com/smartdevicelink/sdl_ios/issues/1161
