### ISSUE TITLE
SDL Ford Sync3 iOS, app is crashing randomly

### ISSUE THREAD

**Issue by nakatal** [smartdevicelink/sdl_ios#1169]
### Bug Report
Crash is in SDLLifecycleManager.m class, in sdl_sendRequest withResponseHandler method for NSParameterAssert(request != nil); this code.
And, we are getting reason of crash in log is : 'Invalid parameter not satisfying: request != nil' 

And also getting warnings in logs:

[Screen/TextAndGraphic] SetDisplayLayout succeeded but didn't send a display capabilities. A lot of things will probably break.
[Screen/SoftButton] SetDisplayLayout succeeded but didn't send a display capabilities. A lot of things will probably break.
[Screen/Menu] SetDisplayLayout succeeded but didn't send a display capabilities. A lot of things will probably break.
[Screen/ChoiceSet] SetDisplayLayout succeeded but didn't send a display capabilities. A lot of things will probably break.

##### Reproduction Steps
We are updating Soft buttons in every seconds to update image and text, and its crashing randomly. 

##### Expected Behavior
This should not crash because it is handling when request is nil.
##### Observed Behavior
Some time request is nil.

##### OS & Version Information
* iOS Version: 12.1.2
* SDL iOS Version: 6.1.2
* Testing Against: We are testing this on Emulator and Car as well(Synch3)

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by joeljfischer** [comment]
It appears that you are trying to send an SDL RPC that is `nil` after it's created. Are those warnings in the logs occurring when you're testing against Ford's Sync Gen 3, or against an emulator, or both? What version of Sync (Settings -> About -> Version information) or emulator are you using? Are you attempting to create a soft button without text or graphic? What is the RPC that you are trying to send but is failing? Can you provide a stack trace?

**Comment by nakatal** [comment]
These warnings and crash is occurring on Emulator and in Car both.

On Emulator, we are not able to check version of SYNC as General option is not redirecting next.

We have implemented Ford Sync3 in our application and we are using templates TilesWithGraphics. 

For testing on Emulator, we have used TCP/IP connection and for testing in car, we have used USB connection. We have made connection as soon as app has launched and after that we are doing steps in sequence, please check following steps:

1.  Screen manager beginUpdates.

2.  Adding soft buttons with text and Image with state “AlertSoftButtonImageState” .

3.  Set SDLSetDisplayLayout i.e TilesWithGraphics.

4.  Send RPCRequest.

5.  endUpdates.

 
Also, we are updating images and text of Soft buttons(Adding soft button) every second and app is crashing randomly. 
We are sending RPC request only once when add soft button first time, after that we are changing image and text of soft button.

From where RPC request can be nil as we are sending request only once?

**Comment by joeljfischer** [comment]
You should not be setting display layouts or sending RPC requests within a `screenManager.beginUpdates()` and `endUpdates()`. Only update the screen manager's text, images, and soft button properties in that block. This does not appear to be a bug with the library, but a misuse of the API. I'd recommend looking at the example apps and guide documentation on smartdevicelink.com. Further questions can be directed to the [SDL Slack](http://slack.smartdevicelink.com).
