### ISSUE TITLE
Update `SendLocation` request RPC documentation

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1170]
Update the `SendLocation` request RPC documentation to reflect that longitude and latitude are not required (it currently says that they are required). While all parameters are optional, either a longitude/latitude **OR** an address must be provided, otherwise Core will reject the request as invalid data (i.e. either `longitudeDegrees` and `latitudeDegrees` must be set **OR** `address` must be set)

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.1
* Testing Against: n/a

**Comment by joeljfischer** [comment]
@NicoleYarroch Do you know if this is the `addressLines` or the `address`? I would assume the `address`.

**Comment by NicoleYarroch** [comment]
It is the `address` parameter.

**Comment by theresalech** [comment]
@joeljfischer can this issue be closed, given the merge of #1196?

**Comment by joeljfischer** [comment]
![](https://media.giphy.com/media/6cFcUiCG5eONW/giphy.gif)
