### ISSUE TITLE
The soft button manager can enter an infinite loop when artwork upload fails

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1177]
### Bug Report
If the phone is disconnected from Core while soft button images are being uploaded, the soft button manager will enter an infinite loop trying to upload images. It should only attempt to upload the artworks the number of times set by the user in the `SDLFileManagerConfiguration`.  I assume this bug will also occur if any of the soft button artwork uploads fail. 

##### Reproduction Steps
1. Connect the example app to Core
2. Disconnect the example app from Core while the soft button images are being uploaded. Do not close the app.

##### Expected Behavior
The soft button manager stops attempting to upload images after the max number of uploads attempts has been reached (as set by the user in the `SDLFileManagerConfiguration`).

##### Observed Behavior
The soft button manager enters an infinite loop of trying to upload the image. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.1
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App

[Soft Button Manager Infinite Loop.log.zip](https://github.com/smartdevicelink/sdl_ios/files/2941549/Soft.Button.Manager.Infinite.Loop.log.zip)

**Comment by NicoleYarroch** [comment]
In the soft button manager's `sdl_updateWithCompletionHandler:` method, when an artwork fails to upload (either because the image upload fails or the file manager is not in the ready state) the manager enters an infinite recursive loop where it attempts to upload the same artworks again and again. The `sdl_uploadInitialStateImages:` and `sdl_uploadOtherStateImages:` methods called from `sdl_updateWithCompletionHandler:` do not take into account that the file manager is responsible for the re-upload attempts so logic should be added to make sure the soft button manager only attempts to upload the artworks once.

**Comment by theresalech** [comment]
Closed via #1251
