### ISSUE TITLE
Add helpful convenience inits and documentation to `SDLRadioControlData`

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1206]
### Bug Report
The `SDLRadioControlData` struct has a convenience init for all possible radio data but setting all the values results in an `INVALID_DATA` result from Core. There should be convenience inits for setting a FM channel, AM channel, and HD channel.

Additionally, Core will reject a channel if the set value is out of bounds. The documentation for `frequencyInteger` , `frequencyFraction` and `band` do not have the min and max bounds for each value.   

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: n/a

**Comment by theresalech** [comment]
Closed via #1525
