### ISSUE TITLE
Using the haptic input feature freezes the app when a single tap is detected

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1207]
### Bug Report
When using the haptic input feature to detect the tapped view in a navigation app, the app freezes whenever a single tap is detected. This is because the library does not check on main thread if a view was tapped.

##### Reproduction Steps
1. Create a navigation app with some `UIViews` in the `rootViewController` (Make sure to send a SDLDidUpdateProjectionView notification to the library)
1. Connect to Core
1. Perform a single tap on a view on the SDL app

##### Expected Behavior
The touch manager should notify the subscriber right away that a view was tapped.

##### Observed Behavior
The app freezes for a few seconds before the notification is sent by the touch manager.

In the `SDLFocusableItemLocator` class, the `viewForPoint:` method should check if a tap is inside a view on the main thread.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: SYNC 3 and SDL_Core 5.1.0 + sdl_hmi

**Comment by theresalech** [comment]
Closed via #1209
