### ISSUE TITLE
Update the System Capability Manager to handle `OnSystemCapability` notifications and auto-caching

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1212]
### Bug Report
Use `OnSystemCapability` when available to auto-update stored system capability properties. the `update` method would then simply return the cached property in the callback immediately instead of going to get the newest value (on v5.1+ systems only, older systems would have to still get the value by polling).

The app services capability, when updated (only exists on v5.1+ systems) will need to be merged since it only contains the updates, not a full new object.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: n/a

**Comment by theresalech** [comment]
Closed via #1215
