### ISSUE TITLE
Choice set manager should return a `nil` `SDLCreateInteractionChoiceSet` object if mandatory parameters are missing

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1220]
### Bug Report
The `menuName` parameter is required for a `SDLChoice` request RPC. However, in the *SDLPreloadChoicesOperation* class, the `menuName` is only set if the `displayCapabilities` has a textfield of name `SDLTextFieldNameMenuName`. If the `menuName` is not set, there is no point in sending a `SDLCreateInteractionChoiceSet` request as Core will reject the request. Instead the `sdl_choiceFromCell:` method should return a `nil` object.   

##### Reproduction Steps
1. Connect LMP to sdl_core + generic_hmi
2. Open the menu and select "artists"

##### Expected Behavior
The popup menu should show.

##### Observed Behavior
All the `SDLCreateInteractionChoiceSet` RPCS fail because the `menuName` is not set by the choice set manager. This is due to generic_hmi not returning a valid display capability when the template is changed.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: sdl_core (v.5.1) + generic_hmi (develop)

**Comment by justingluck93** [comment]
Correct me if I'm wrong
If menuName is nil we should return nil object right away. However, in `sdl_preloadedCells` it would add nil to the Array so   
```
NSMutableArray<SDLCreateInteractionChoiceSet *> *choiceRPCs = [NSMutableArray arrayWithCapacity:self.cellsToUpload.count];
    for (SDLChoiceCell *cell in self.cellsToUpload) {
        [choiceRPCs addObject:[self sdl_choiceFromCell:cell]];
    }
``` 

should become 

```
NSMutableArray<SDLCreateInteractionChoiceSet *> *choiceRPCs = [NSMutableArray arrayWithCapacity:self.cellsToUpload.count];
    for (SDLChoiceCell *cell in self.cellsToUpload) {
        SDLCreateInteractionChoiceSet *csCell =  [self sdl_choiceFromCell:cell];
        if(csCell != nil) {
            [choiceRPCs addObject:csCell];
        }
    } 
```

and inside sdl_choiceFromCell if menuName is nil

``` 
NSString *menuName = [self.displayCapabilities hasTextFieldOfName:SDLTextFieldNameMenuName] ? cell.text : nil;
   
    if(!menuName) {
        return nil;
    }
```

is this correct?

**Comment by NicoleYarroch** [comment]
@justingluck93 Yes, you will have to change the `SDLPreloadChoicesOperation` class as well. If one cell is `nil`, it is likely that all will be `nil` so I would also add a check to make sure `choiceRPCs` is not empty before proceeding to the next step. If it is, log an error message.
