### ISSUE TITLE
Previous SDLIAPTransport instance steals new accessory connected event

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#1221]
### Bug Report
During HU (iAP) continuous connection test (Bluetooth <=> USB), we encounter an issue that SDLProxy cannot connect to SDL Core.

On our OEM's HU (iAP device), as USB cable connects and switches to USB iAP connection while HS has been connected with SDL Core by Bluetooth, HU and HS become the state where connected with both connection types of Bluetooth and USB. This is a temporary transition state when switching to iAP connection by USB connection from iAP connection by Bluetooth. 
We found that this temporal state causes this problem.

The current implementation of SDLIAPTransport attempts to process the events of Accessory connection even if it is already connected to HU. Then, when the connection with SDL Core by Bluetooth is lost, SDLProxy and SDLIAPTransport will be newly created and try to connect. 
In this case, the two instances of SDLIAPTransport try to connect to an accessory and cause conflict depending on connection/disconnection timings.

##### Reproduction Steps
1. SDLLifecycleManager starts and SDLProxy-A and SDLIAPTransport-A are created.

2. SDLIAPTransport-A handles the first accessory connected by Bluetooth event.

3. When the USB cable is plugged, USB accessory connected event is delivered before the disconnection event of Bluetooth. 

4. SDLIAPTransport-A also handles the 3. event because event listening is still active and SessionSetupInProgress flag is NO.
https://github.com/smartdevicelink/sdl_ios/blob/develop/SmartDeviceLink/SDLIAPTransport.m#L485

5. When Bluetooth connection to HU is disappearred, SDLProxy-A is deallocated and new SDLProxy-B and SDLIAPTransport-B instances are created.

6. SDLIAPTransport-B also tries to connect and create EA session. This causes some conflict with the behavior of SDLIAPTransport-A at 4. This depends on the timing and the `retryDelay` value at https://github.com/smartdevicelink/sdl_ios/blob/develop/SmartDeviceLink/SDLIAPTransport.m#L162

##### Expected Behavior
SDLIAPTransport-B opens an EA session

##### Observed Behavior
SDLIAPTransport-A opens an EA session and prevents SDLIAPTransport-B to open 

##### OS & Version Information
* iOS Version: iOS11, 12
* SDL iOS Version: 6.1.1
* Testing Against: Our internal HU devboard

##### Test Case, Sample Code, and / or Example App
n/a so far

**Comment by joeljfischer** [comment]
I believe something similar to this may have been fixed in the latest release (https://github.com/smartdevicelink/sdl_ios/issues/1079). Please retest against the latest SDL version.

**Comment by t-yoshii** [comment]
@joeljfischer thank you for your information!
#1079 is very similar to this issue. I will try the fix #1150 .

**Comment by t-yoshii** [comment]
I confirmed that #1150 fixes this issue. Closing.
