### ISSUE TITLE
Fix SDLAlert documentation

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1233]
### Bug Report
The SDL_iOS library documentation for `SDLAlert` is inaccurate. Currently it says:
> Although each Alert parameter is optional, in fact each SDLAlert request must supply at least one of the following parameters:
alertText1
alertText2
alertText3
ttsChunks

However, [the RPC spec](https://github.com/smartdevicelink/rpc_spec#alert) says 
> At least either alertText1, alertText2 or TTSChunks need to be provided.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.1
* Testing Against: n/a

**Comment by theresalech** [comment]
Fixed via #1242
