### ISSUE TITLE
Transitioning multiple soft buttons to the next state in the Soft Button manager fails

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1234]
### Bug Report
1. If two soft buttons transition to the new state at the same time, the second button state will not be sent in the `updateWithCompletionHandler:` method because the `isDirty` param is set to `NO` by the first button transition. 

##### Reproduction Steps
1. Use the `ScreenManager` to set two buttons, buttonA and buttonB, with multiple states. When buttonA is tapped, transition buttonA to the next state and buttonB to the next state.
2. Connect the app to Core
3. Tap on buttonA on the SDL app

##### Expected Behavior
Both button states transition successfully to the next state.

##### Observed Behavior
Only buttonA transitions to the next state. ButtonB stays in its current state.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.1
* Testing Against: Manticore

**Comment by theresalech** [comment]
Fixed via #1251
