### ISSUE TITLE
SoftButtonManager does not handle head units that don't support images

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1249]
### Bug Report
`DisplayCapabilities` tells us if the soft button image is supported with the `ImageFieldName`, however the `SoftButtonManager` always sends an image if it's set.

##### Reproduction Steps
1. Have a head unit return `DisplayCapabilities` without the `SoftButtonImage` image field.
2. Set a soft button with an image in the SoftButtonManager

##### Expected Behavior
The soft button should not be sent, or should only send the text if it's available.

##### Observed Behavior
The soft button is sent

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: n/a

**Comment by joeljfischer** [comment]
`SoftButtonCapabilities` also describes if images are supported

**Comment by theresalech** [comment]
Resolved via #1251
