### ISSUE TITLE
The `SDLAudioStreamManager` public property `queue` is inaccessible

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1283]
### Bug Report
The `SDLAudioStreamManager` public property `queue` is inaccessible.

1. The `SDLAudioFile` is header is not public.
1. The `SDLAudioStreamManager` header file imports the `SDLAudioFile.h` using a `@class` when it needs to import using `#import`

##### Reproduction Steps
1. Create an example app implementing the `SDLAudioStreamManagerDelegate`.
1. In one of the delegate method, attempt to access the public `queue` property.

##### Expected Behavior
The `queue` property should be accessible since it is a public property in the `SDLAudioStreamManager` class.

##### Observed Behavior
Get a compiler warning `Value of type 'SDLAudioStreamManager' has no member 'queue'`

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.2
* Testing Against: n/a

**Comment by joeljfischer** [comment]
It appears to me that `queue` is accessible, at least in Obj-C. However, the audio files are certainly private and can't be used properly.
