### ISSUE TITLE
[SDL 0236] Update mismatch in TireStatus structure

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#1297]
Proposal: [Update mismatch in TireStatus structure](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0236-TireStatus-Mismatch.md)

> This proposal is about correcting a mismatch between HMI_API and MOBILE_API for the `TireStatus` structure.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/743

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revision: clarify that this update will be a breaking change.

> The proposal .md file was updated to reflect these revisions on 6/6/19.

**Comment by yoooriii** [comment]
iOS implementation, PR: https://github.com/smartdevicelink/sdl_ios/pull/1867
