### ISSUE TITLE
Cloud app icon overwritten on very first connection

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1305]
### Bug Report
If connecting a cloud SDL app to Core for the **first** time, the downloaded cloud app icon sent in the `SystemRequest` RPC is overwritten by the `SetAppIcon` RPC sent by the lifecycle manager. All subsequent connections to Core show the correct (i.e. the cloud app icon) app icon. This is due to the library not sending a `SetAppIcon` because the `isResumed` property is set to true in the RAI response. 

Perhaps there should be a convenience init for cloud apps in the `SDLLifecycleConfiguration` class that does not take an app icon.

##### Reproduction Steps
1. Clear Core's cache
1. Set up the policy table for a cloud app. Make sure to set the cloud app icon url.
1. Connect the SDL app to Core

##### Expected Behavior
The icon that shows up on the hmi should be the cloud app icon.

##### Observed Behavior
The icon that shows up on the hmi is the local app icon sent by the app. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.3
* Testing Against: sdl_core 5.1.0 + sdl_hmi

**Comment by joeljfischer** [comment]
Closing as not reproducible
