### ISSUE TITLE
Queueing Choice Preloads while Checking VR Optional Fails

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1308]
### Bug Report
Queueing a choice preload while in the Checking VR Optional state currently fails, but it should succeed. Queueing a preload should only fail if we are in the shutdown state

##### Reproduction Steps
1. Immediately upon connection, queue a preload

##### Expected Behavior
The preload is queued and occurs after the choice VR optional finishes

##### Observed Behavior
The preload fails

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.3-develop
* Testing Against: Sync Gen 3 x2 TDK

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by theresalech** [comment]
Closed via #1309
