### ISSUE TITLE
EAAccessory event is not notified after SDLIAPTransport dealloc

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#1311]
### Bug Report
We tested with the `develop` branch which includes the #1248 fix.

EAAccessory event is not notified after SDLIAPTransport deallocation because it calls `[[EAAccessoryManager sharedAccessoryManager] unregisterForLocalNotifications];` at https://github.com/smartdevicelink/sdl_ios/blob/develop/SmartDeviceLink/SDLIAPTransport.m#L127

Multiple SDLIAPTransport instances can exist at the same time. SDLIAPTransport have a background task and it holds a reference to `self`, so, the deallocation of SDLIAPTransport is delayed until the background task ends when it runs in the background. At that timing, next SDLIAPTransport can be listening for EA events. `unregisterForLocalNotifications` affects these new instances.

##### Reproduction Steps
1. Start SDL app in HU (HS app is running in the background on HS) with USB connection.
2. Disconnect USB, the connection will change from USB to Bluetooth.
3. Wait for more than 3 minutes.
4. Connect USB

##### Expected Behavior
App successfully connected with USB

##### Observed Behavior
App cannot detect the connection change. During the wait at 3, `dealloc` of old SDLIAPTransport instance is called and `unregisterForLocalNotifications` is called. Therefore, EAAcccessoryLeft and EAAccessoryArrirved at 4 are not handled.

##### OS & Version Information
* iOS Version: iOS11, 12
* SDL iOS Version: develop branch daa57de82b90992cc72120ba5cee3f1c48f84df4 (6.2.3 +)
* Testing Against: Our internal devboard/OEM HU

##### Test Case, Sample Code, and / or Example App
none

**Comment by theresalech** [comment]
Closing as resolved by #1317
