### ISSUE TITLE
Cell Icons are a no show the first time a menu is set

### ISSUE THREAD

**Issue by justingluck93** [smartdevicelink/sdl_ios#1312]
### Bug Report
It only happens the first time I send a menu if I send 1 menu item with artwork or 100 menu items with the same artwork, the DeleteCommands are never sent. If I send 100 menu items with different artworks, the DeleteCommands are sent.

##### Reproduction Steps
1. Set a menu with artwork 
2. Open menu and notice cells have no icon

##### Expected Behavior
Cells should have icons

##### Observed Behavior
Cells have no icons

**Comment by theresalech** [comment]
Closed via #1313
