### ISSUE TITLE
A new transport session is not created if a background task is not ongoing

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1316]
### Bug Report
If app on device is closed when trying to create a connection with the SDL enabled accessory: 
1. The connection attempt can fail if the background task is not started.
2. The reconnection attempt can fail due to the background task being destroyed in the dealloc method of the `SDLIAPTransport` object. 

##### Reproduction Steps
1. Configure 13 apps with v.6.3 of the library 
2. Connect the phone to SYNC 3.4 TDK with BT
3. Go to apps tab and wait for all 13 apps to show up
  
##### Expected Behavior
All 13 apps show up on the SDL HMI.

##### Observed Behavior
Between 1 and 3 apps will sometimes fail to show up. From the logs it looks like the background task expires, so even though a reconnection attempt should be made by the lifecycle manager, nothing happens. 

##### OS & Version Information
* iOS Version: 12.1.4
* SDL iOS Version: 6.3
* Testing Against: SYNC 3.4 TDK (Build 19126_DEVTEST) + iPhone XS Max (iOS 12.1.4)

**Comment by NicoleYarroch** [comment]
All the logs for the apps the fail to connect to the TDK show that the a data session is established but the start session times out because no response is received from Core. The transport is destroyed and a new transport should be created, however, since the background task was destroyed in the dealloc method, the new transport is not created.

**Comment by t-yoshii** [comment]
Is this same as https://github.com/smartdevicelink/sdl_ios/issues/1311 ?
