### ISSUE TITLE
Update primaryGraphic

### ISSUE THREAD

**Issue by JoaquimOliveira-AG** [smartdevicelink/sdl_ios#1325]
**Bug Report**
I'm developing a media app and I wish to update the primary graphic with the cover of the current playing item but if I set the display layout SDLPredefinedLayoutMedia the image doesn't appear. 

I have followed the sample code and created a similar implementation:
```swift
class func connectIAP() -> SDLConfiguration {
        let lifecycleConfiguration = SDLLifecycleConfiguration(appName: <appname>, fullAppId: <fullappid>)
        return setupManagerConfiguration(with: lifecycleConfiguration)
    }
    
    class func setupManagerConfiguration(with lifecycleConfiguration: SDLLifecycleConfiguration) -> SDLConfiguration {
.......
        lifecycleConfiguration.appType = .media
......
    }

func hmiLevel(_ oldLevel: SDLHMILevel, didChangeToLevel newLevel: SDLHMILevel) {
        switch newLevel {
        case .full:      
            showInitialData()
        }
    }

 func showInitialData() {
        let setDisplayLayout = SDLSetDisplayLayout(predefinedLayout: .media)
        sdlManager.send(request: setDisplayLayout) { (_, _, error) in
            if let e = error {
                print("sdl debug \(e.localizedDescription)")
            }else{
                self.updateScreen()
            }
    }

func updateScreen() {
        guard sdlManager.hmiLevel == .full else { return }
        let screenManager = sdlManager.screenManager
        screenManager.beginUpdates()
        screenManager.textAlignment = .center
        screenManager.textField1 = obj.title
        screenManager.textField2 = obj.subtitle
        screenManager.endUpdates()

        updatePrimaryImage(withUrl:obj.imageURL)
    }

func updatePrimaryImage(withUrl url:URL) {
        if sdlManager.systemCapabilityManager.displayCapabilities?.graphicSupported.boolValue ?? false {
            downloadImage(with: url, completed: {(image) in
                guard let image = image else {return}
                print("sdl debug  image -> beginUpdates")
                screenManager.beginUpdates()
                let artwork = SDLArtwork(image:  image.withRenderingMode(.alwaysOriginal), persistent: false, as: .PNG)
                screenManager.primaryGraphic = artwork
                
                screenManager.endUpdates(completionHandler: { (error) in
                    print("sdl debug image -> endUpdate")
                    if let error = error {
                        print("sdl debug image -> \(error)")
                    }else{
                        print("sdl debug image -> success")
                    }
                })
            })
        }
    }

func objectDidSelectedHandler() {
        updateScreen()
}
```

The title and subtitle are updated but the cover doesn't. If before update the image I check if the primaryGraphic is supported the return is true the other the return is false. 

```swift
func imageFieldSupported(imageFieldName: SDLImageFieldName) -> Bool {
        return sdlManager.systemCapabilityManager.displayCapabilities?.imageFields?.first { $0.name == imageFieldName } != nil ? true : false
    }
```
If I set the display layout for SDLPredefinedLayoutNonMedia everything works well. 

##### Expected Behavior
Whenever the current playing item changes the context (title, subtitle and cover) is updated. 

##### Observed Behavior
Just the title and subtitle are updated. The cover is not appear. 

##### OS & Version Information
* iOS Version: 12.3.1
* SDL iOS Version: 6.2.3
* Testing Against: SYNC 3, sowftware version 3.3 Build 19052_DEVTEST

**Comment by joeljfischer** [comment]
If the head unit claims that it doesn't support a primary graphic, the library won't attempt to upload and display the artwork in order to conserve data. We are unaware of any head units in production that display this issue and have tested against Sync 3.0 and 3.4.

So with that said, if this is an issue in production, we can build a compatibility. However, if this is not, it would be better to notify your Ford contact that they have faulty head unit software.

**Comment by joeljfischer** [comment]
Closed as an OEM issue

**Comment by barisyazganc** [comment]
Hi,

I have the same issue, in displayLayout .media type, primary and secondry images not supported, only .appIcon is supported... any ideas?

**Comment by joeljfischer** [comment]
@barisyazganc What are you testing against? We know that this works so it must either be an issue with your code or with the HMI you are testing against.

**Comment by barisyazganc** [comment]
Hi, I'm using a Ford SYNC TDK (x2.1) device for development...  here is the basic code... Maybe i'm doing something wrong..

        ```
let display = SDLSetDisplayLayout(predefinedLayout: .media)
        sdlManager.send(display)
        self.sdlManager.screenManager.beginUpdates()
        self.sdlManager.screenManager.textField1 = artistTitle
        self.sdlManager.screenManager.textField2 = songTitle
        self.sdlManager.screenManager.endUpdates()
        
        updatePrimaryImage()

func updatePrimaryImage(_ artWork : Image? = nil) {
            self.sdlManager.screenManager.beginUpdates()
            let artwork = SDLArtwork(image: UIImage(named: "TestImage")!.withRenderingMode(.alwaysOriginal), name: "placeHolderImage", persistent: false, as: .PNG)
            self.sdlManager.screenManager.primaryGraphic = artwork
            self.sdlManager.screenManager.endUpdates()
}
```

**Comment by JoaquimOliveira-AG** [comment]
@barisyazganc Check if you are set the display layout to media (SDLSetDisplayLayout(predefinedLayout: .media)). Remove this code and be sure on backoffice your app is defined like media. I think It solve the issue

**Comment by barisyazganc** [comment]
> @barisyazganc Check if you are set the display layout to media (SDLSetDisplayLayout(predefinedLayout: .media)). Remove this code and be sure on backoffice your app is defined like media. I think It solve the issue

if i remove this code, screen doesnt changes to media player
