### ISSUE TITLE
RAIR returns error APPLICATION_REGISTERED_ALREADY after switching between USB and BT transports several times

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1331]
When switching between USB and BT transports, sometimes the `RegisterAppInterface` request fails with the error `APPLICATION_REGISTERED_ALREADY`.

### Bug Report
Not sure if this is a library issue or a Core issue. As far as I can tell when examining the logs, the sessions are being closed successfully before a new session is created.

##### Reproduction Steps
1. Test with 14 SDL apps
1. Connect phone to head unit that supports both USB and BT transports using USB
1. Rapidly switch between USB and BT transports by pulling and unplugging the USB cord

##### Expected Behavior
All apps show up as expected.

##### Observed Behavior
Eventually, after several transport switches, one or two apps will get a RAI response with a `resultCode` of `APPLICATION_REGISTERED_ALREADY`. The library shuts down the data session successfully however the app name still shows up on the SDL HMI with no app icon. Pressing on the app name on the SDL HMI does nothing. 

##### OS & Version Information
* iOS Version: 6.3.0
* SDL iOS Version: 11.4.1 (iPhone SE), 12 (XS Max)
* Testing Against: SYNC 3.4 (Build 19126_DEVTEST)

**Comment by NicoleYarroch** [comment]
@SatbirTanda have you noticed this issue in your testing of SYNC 3.4? I have had this happen almost every time I test with 10+ apps.

**Comment by NicoleYarroch** [comment]
Logs from iPhone SE (iOS 11.4.1)
[2019-07-09-12:50:32-smartdevicelink-iOS11.4.1iPhoneSE.log](https://github.com/smartdevicelink/sdl_ios/files/3374298/2019-07-09-12.50.32-smartdevicelink-iOS11.4.1iPhoneSE.log)

**Comment by SatbirTanda** [comment]
@NicoleYarroch I haven't seen this in this on 3.4 for apps not appearing.  Usually I see this when I have an app that has the same SDL app Id / app Name as another on my phone

**Comment by E-SAITO-TMC** [comment]
@joeygrover -san @theresalech -san This issue is a top priority for Toyota. I would like know if it will be reproduced in the latest version.

**Comment by joeljfischer** [comment]
I tested this recently and was unable to reproduce. @E-SAITO-TMC if you are seeing this issue, please provide reproduction steps and logs.
