### ISSUE TITLE
The choice set manager does not handle a success result with an error

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1363]
# Bug Report
The `SDLChoiceSetManager` is not setup to handle both an error and a success result for a `PerformInteraction` response, so a subscriber is not notified when a choice set item is selected.

##### Reproduction Steps
1. Connect the SDL_iOS Swift example app to sdl_core + sdl_hmi 
2. Click on the first PICS item in the menu

##### Expected Behavior
The subscriber should be notified that a choice set item was selected.

##### Observed Behavior
The subscriber is not notified that a choice set item was selected.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.4
* Testing Against: sdl_core + sdl_hmi

##### Test Case, Sample Code, and / or Example App
Tested using the library's Swift example app

**Comment by joeljfischer** [comment]
Closed as fixed in sdl_hmi
