### ISSUE TITLE
Reflect bitrate value returned from HMI to video encoder setting

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#1392]
### Bug Report
Currently SDL iOS proxy ignores the bitrate value returned from HMI. This value should be reflected in the video encoder setting to perform VPM encoding/decoding smoothly. 

##### Reproduction Steps
Connect VPM app to SDL Core.

##### Expected Behavior
1. Connect the VPM app to SDL Core.
2. Encoder setting reflects the value of bitrate in video streaming capabilities. 

##### Observed Behavior
1. Connect the VPM app to SDL Core.
2. Encoder setting does not reflect the value of bitrate in video streaming capabilities. 

##### OS & Version Information
* iOS Version: all
* SDL iOS Version: 6.3.1
* Testing Against: Our internal devboard and OEM HMIs.

##### Test Case, Sample Code, and / or Example App
I will create PR.

**Comment by NicoleYarroch** [comment]
Fixed in PR #1393

**Comment by NicoleYarroch** [comment]
Fixed in PR #1413
