### ISSUE TITLE
If certificate is valid but Core rejects the certificate for some reason an infinite handshake loop starts

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1394]
### Bug Report
If the certificate downloaded in the security manager is a valid certificate but Core rejects the certificate for some reason an infinite handshake loop starts with Core.

##### Reproduction Steps
1. Configure the SDL app to start an encrypted RPC service.
2. Use an `appID` for the SDL app that is different from the one used to generate the certificate.

##### Expected Behavior
The app gets a NACK for the start session request.

##### Observed Behavior
The app gets a NACK for the start session request, but then starts an infinite handshake loop with core. I believe it is because when the library parses the handshake message for an error it also needs to check if the handshake data is empty as well as if it is `nil`. However I am not sure if there are other situations where the `serverHandshakeData` could be empty.

Possible solution:
In `sdl_processSecurityMessage:` of the `SDLProtocol` class we should also check if `serverHandshakeData.length == 0`:

```
// If the handshake went bad and the security library ain't happy, send over the failure to the module. This should result in an ACK with encryption off.
SDLProtocolMessage *serverSecurityMessage = nil;
if (serverHandshakeData == nil || serverHandshakeData.length == 0) {
    SDLLogE(@"Error running TLS handshake procedure. Sending error to module. Error: %@", handshakeError);

    serverSecurityMessage = [self.class sdl_serverSecurityFailedMessageWithClientMessageHeader:clientHandshakeMessage.header messageId:++_messageID];
} 
```

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: #1320 PR  
* Testing Against: sdl_core v5.1

**Comment by joeljfischer** [comment]
Unable to replicate on Core 8.1.0 / SDL_iOS 7.4.0
