### ISSUE TITLE
Travis is "succeeding" by not running at all

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1399]
### Bug Report
According to Travis – `xcodebuild: error: SDK "iphonesimulator11.0" cannot be located.` We need to update which iPhoneSimulator we're using.

**Comment by yLeonid** [comment]
Travis script updated and waiting for review
"Implement SDL 0179 - Pixel density and Scale"
https://github.com/smartdevicelink/sdl_ios/pull/1401/files/ec2e1ba676f7a874fbbcd530ae42d053882d9435#diff-03d0329385b623648a673c1bdddc3cfd

**Comment by NicoleYarroch** [comment]
Fixed with PR #1400
