### ISSUE TITLE
iOS 13 makes the lock screen dismissible by default

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1422]
Due to changes in iOS 13, all modal presentations are basically pageSheet/formSheet by default.  This makes the lock screen become dismissible by default by swiping down.

1. Create SDL app with latest SDK and install on an iOS 13 device 
2. Connect the app to a TDK and simulate speed to show the lock screen

##### Expected Behavior
Lockscreen should appear over full screen

##### Observed Behavior
Lockscreen is dismissible because modal presentation is a form

##### OS & Version Information
* iOS Version: 13
* SDL iOS Version: 6.3.1
* Testing Against: SYNC

See app below for issue
[TripleA.zip](https://github.com/smartdevicelink/sdl_ios/files/3673732/TripleA.zip)

**Comment by joeljfischer** [comment]
Thanks for the report, we will investigate and fix in the next release
