### ISSUE TITLE
Index 0 beyond bounds for empty array crashes in SDL library (6.3.1)

### ISSUE THREAD

**Issue by SunXiaoShan** [smartdevicelink/sdl_ios#1430]
### Bug Report
My project got two crashes from SDL library (iOS).
The number line are difference, but the root cause are same.
And it only happens on the **iOS 13+.**

*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array
SDLScreenshotViewController.m line 37
SDLScreenshotViewController.m line 50

I leave some screen shots on the slack.
[https://smartdevicelink.slack.com/archives/C0K32T48Y/p1569995789023500](https://smartdevicelink.slack.com/archives/C0K32T48Y/p1569995789023500)

##### Reproduction Steps
1. Launch the app
2. Wait a moment (2 min)
3. Crash(Random)

##### Expected Behavior
Not crash

##### OS & Version Information
* iOS Version: 13.1+
* SDL iOS Version: 6.3.1
* Test Mobile: iPhone X, iPhone MS MAX 
* XCode: 11.0

**Comment by joeljfischer** [comment]
@SunXiaoShan Hello, can you please provide us with additional information or sample code that you've used to test. Do you know if the app you used supports the iOS 13+ `UIWindowScene` API (e.g. multiple windows)?

**Comment by SunXiaoShan** [comment]
Test & Verify the v6.4.1.
This ticket could not reproduce again.
