### ISSUE TITLE
If 2 phones are connected to head unit via USB and BT, the connected apps for the connected phone are disconnected when the other phone disconnects 

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1431]
### Bug Report
Phone 1 was connected via USB and all the SDL apps showed up on the head unit. Then phone 2 connected via bluetooth replaced all the SDL apps with phone 2's apps. When I disconnected phone 1's USB cord, all of phone 2's apps disconnected too. This shouldn't have happened.

This can probably be fixed by comparing the session id of the disconnected session with the currently open session id and only closing the session if they match.

##### Reproduction Steps
1. Pair phone 2 with the head unit using BT. Then turn off BT on the phone.
1. Connect phone 1 to the head unit using a USB cord. The phone should register and all the SDL apps should show up.
1. Turn on BT on phone 2. Phone 2 should register on the head unit and all of phone 2's SDL apps should replace phone 1 apps
1. Pull the USB cord from phone 1.

##### Expected Behavior
Nothing should happen as phone 2 is still connected to the head unit.

##### Observed Behavior
The SDL app sessions on phone 2 are closed.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.3
* Testing Against: SYNC 3 TDK (v.3.4 Build 19274_DEVTEST)

**Comment by theresalech** [comment]
Closed via #1453
