### ISSUE TITLE
Crash: Extends beyond bounds for empty array

### ISSUE THREAD

**Issue by rbright55** [smartdevicelink/sdl_ios#1433]
## Bug Report
Reason: 
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM removeObjectsInRange:]: range {0, 1} extends beyond bounds for empty array' 
Location: 
\- [SDLMutableDataQueue popBuffer], line 57 

##### Reproduction Steps
N/A
##### Expected Behavior
Within the `popBuffer` function of the `SDLMutableDataQueue.m` file, a check should be added to see if the array is empty.

##### Observed Behavior
App crashes because the function is trying to remove an object from an empty array

##### Frequency
1/5

##### OS & Version Information
* Device: iPhone 7
* iOS Version: 13.2
* SDL iOS Version: 6.3.1
* Testing Against: SYNC 3, Ford Explorer

**Comment by theresalech** [comment]
Closed via #1435
