### ISSUE TITLE
Example app warning alert shown even when template changed successfully

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1456]
### Bug Report
1. Since the `SDLSetDisplayLayout` RPC is deprecated in RPC v.6.0, an alert is shown saying setting the template did not work since the `resultCode` is `WARNINGS` instead of `SUCCESS`.
2. Both the Swift and Obj-C example apps should be updated to use `SDLShow`'s `templateConfiguration` instead of the deprecated `SDLSetDisplayLayout`.

##### Reproduction Steps
1. Connect app to SDLSecurityStatic_core with RPC v.6.0 implemented
1. From the menu, select one of the options to change the template

##### Expected Behavior
The template changes.

##### Observed Behavior
The template changes but an alert pops up saying the template did not change.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.3
* Testing Against: sdl_core v.6.0.0

##### Test Case, Sample Code, and / or Example App
Tested using the Swift example app in the SDL_iOS library.

**Comment by joeljfischer** [comment]
> Both the Swift and Obj-C example apps should be updated to use SDLShow's templateConfiguration instead of the deprecated SDLSetDisplayLayout.

Note that if you do this, changing templates will cease to work on any < 6.0 system.

**Comment by NicoleYarroch** [comment]
So we can either:
1. Check the head unit's RPC version and do and send a `SetDisplayLayout` if older than v6.0 and a `Show` if v6.0+.
1. Send the `Show` request by default and try the `SetDisplayLayout` if the `Show` fails (Might not work - not sure if you will get an error message if you attempt to change the template via `Show` on older head units).
