### ISSUE TITLE
Revert data session delay

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1462]
### Bug Report
Due to [this comment from the Ford team](https://github.com/smartdevicelink/sdl_ios/pull/1343#issuecomment-546969237) we will revert #1240 / #1385 until additional testing can be performed.

##### Reproduction Steps
n/a

##### Expected Behavior
n/a

##### Observed Behavior
n/a

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: n/a
* Testing Against: n/a

**Comment by theresalech** [comment]
Closed via #1463
