### ISSUE TITLE
When using iOS 13 multi-window scene API, the lock screen doesn't work correctly

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1469]
### Bug Report
When presenting the default lock screen on iOS 13 on an iPhone app that uses the multi-window API, only a black screen displays and is not animated. This may be related to #1430.

##### Reproduction Steps
1. Set up a new example app through Xcode that uses the default multi-window API.
2. For the lock screen configuration, use the `.enabled()` default configuration
3. Alter the driver distraction state on the module to toggle the lock screen

##### Expected Behavior
Equivalent behavior to iOS 12

##### Observed Behavior
A black screen appears / disappears over the existing screen without animation

##### OS & Version Information
* iOS Version: 13.1.3
* SDL iOS Version: 6.4.0
* Testing Against: Sync Gen 3 (but this does not matter)

##### Test Case, Sample Code, and / or Example App
n/a at this time

**Comment by SunXiaoShan** [comment]
@joeljfischer 
There are two points.
You only correct one. Could you modify it on line 50 also?

SDLScreenshotViewController.m line 37
SDLScreenshotViewController.m line 50

**Comment by SunXiaoShan** [comment]
> @joeljfischer
> There are two points.
> You only correct one. Could you modify it on line 50 also?
> 
> SDLScreenshotViewController.m line 37
> SDLScreenshotViewController.m line 50

This is my mistake. I'll confirm it.
