### ISSUE TITLE
If the application is switched to the background and then to the foreground, video streaming timeout occurs.

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_ios#1471]
### Bug Report
If the application is switched to the background and then to the foreground,
video streaming timeout occurs.

##### Preconditions
1.Primary transport: BT
    Secondary transport: WIFI
※If it connected via USB, there is no problem.

##### Reproduction Steps
1. Register App:
・App: navigation App for iOS
2. Activate App
3. Switch App to the background on iPhone
4. Switch App to the foreground on iPhone

##### Expected Behavior
1. SDL->App.OnHMIStatus(NONE->FULL,STREAMABLE)
2. App starts video streaming
3. Switch App to the background
4. SDL<-App.OnHMIStatus(BACKGROUND)
5. SDL<-App.OnServiceEndedCallback(11)
6. App.resetStatus()
```
video protocol = nil;
videoStreamState = NotStreamable;
```
7. Switch App to the foreground
8. App.didEnterStateVideoStreamReady()
9. App.sdl_startTCPSecondaryTransport()
10. SDL<-App.OnHMIStatus(FULL)
11. App restarts video streaming

##### Observed Behavior
There is no video data because the step8(App.didEnterStateVideoStreamReady)
is not called.

##### OS & Version Information
* iOS Version: 10.2
* SDL iOS Version: 6.3.0
* Testing Against: SDL Core 5.1.3 + HMI running on our development environment.

##### Test Case, Sample Code, and / or Example App
Logs:[Log.zip](https://github.com/smartdevicelink/sdl_ios/files/3844246/Log.zip)

##### Occurrence
100%

##### Recovery Method
None

**Comment by E-SAITO-TMC** [comment]
This is one of the issues that Toyota reported at the 11/18 Roadmap workshop.

**Comment by NicoleYarroch** [comment]
@E-SAITO-TMC is the Toyota team working on a fix for this issue?

**Comment by NicoleYarroch** [comment]
@stefanek22 can you let us know if Ford is experiencing this issue as well?

**Comment by theresalech** [comment]
Toyota team confirmed via email that they will be submitting a PR to resolve this issue by 2020-01-24.

**Comment by NicoleYarroch** [comment]
@zhouxin627 I believe this issue was fixed in PR #1566. I know you submitted a PR (#1528) to fix the issue but I had to do an extensive refactor the secondary transport manager to fix some bugs. Can you test with PR #1566 to see if this bug has been fixed? Thank you.

**Comment by joeljfischer** [comment]
Hello @zhouxin627, could you please take a look at Nicole's comment above and check this bug? We believe it has been fixed. If it is still valid, it can be re-opened.

**Comment by zhouxin627** [comment]
Hi @NicoleYarroch @joeljfischer, I'm sorry for the late reply. We have confirmed that #1471 has been fixed. But #1479 is still being confirmed. I'll let you know the result as soon as possible.
