### ISSUE TITLE
Unable to compile if the ProxyManager is in objective c++

### ISSUE THREAD

**Issue by ed-h** [smartdevicelink/sdl_ios#1478]
### Bug Report
Due to our project needs, our proxy manager is in objective c++, this will cause compile error due to the template keyword that is used in SDLTemplateConfiguration.h.
This wasn't an issue in older version since SDLTemplateConfiguration class is added in 6.4.0

##### Reproduction Steps
1. Rename ProxyManager.m to ProxyManager.mm so it will be compiled as objective c++
2. Import SmartDeviceLink.h as documented
3. Compile error will occur.
Pods/Headers/Public/SmartDeviceLink/SDLTemplateConfiguration.h:40:46: error: expected identifier; 'template' is a keyword in Objective-C++

Pods/Headers/Public/SmartDeviceLink/SDLTemplateConfiguration.h:45:41: error: expected member name or ';' after declaration specifiers; 'template' is a keyword in Objective-C++
@property (strong, nonatomic) NSString *template;

Suggest to rename this variable to templateName instead of template

##### Expected Behavior
Project should compile fine.

##### Observed Behavior
Compoile failed

##### OS & Version Information
Xcode 11.2.1
SDL iOS SDK 6.4.0/6.4.1

**Comment by braveS** [comment]
Same here

**Comment by joeljfischer** [comment]
@ed-h @braveS We have a bug fix in the PR #1485. Could you please verify that branch fixes your bugs? It may be a few weeks before release due to the holidays and CES, but until that point, hopefully you can continue development using the provided PR and branch.

**Comment by braveS** [comment]
@joeljfischer sorry for late response. This fix works for me just fine, thank you!
