### ISSUE TITLE
Turn off the Wi-Fi on the phone, then turn on the Wi-Fi on the phone, video streaming can not continue

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_ios#1479]
### Bug Report
Turn off the Wi-Fi on the phone, then turn on the Wi-Fi on the phone, video streaming can not continue.

##### Reproduction Steps
1. Connect the head unit to the phone via BT+WiFi
2. Register a NaviAPP
3. Activate a NaviAPP, start video steaming
4. Turn off the WiFi on the phone
5. Turn on the WiFi on the phone, connect to the head unit

##### Expected Behavior
Video streaming can continue.

##### Observed Behavior
Video streaming can not continue.
When users turn off the WiFi on the phone, Proxy sets VideoStream = NOTStreamable.
After restoring the WiFi Connection, Proxy does not set VideoStream = Streamable.

##### OS & Version Information
* iOS Version:10.2
* SDL iOS Version: 6.3.0
* Testing Against: Testing Against: SDL Core 5.1.3 + HMI running on our development environment

##### Test Case, Sample Code, and / or Example App
![image](https://user-images.githubusercontent.com/35795928/69767948-e5346d00-11c1-11ea-884c-8fed391ce9ef.png)

**Comment by theresalech** [comment]
@E-SAITO-TMC is the Toyota team working on a fix for this issue?  If so, can you please let us know when the fix will be ready for Livio review?

@stefanek22 can you let us know if Ford is experiencing this issue as well?

**Comment by E-SAITO-TMC** [comment]
@theresalech 
I'm sorry, I found a bug.
It has not been fixed yet.
We will let you know when a solution is found.

**Comment by theresalech** [comment]
Toyota team confirmed via email that they will be submitting a PR to resolve this issue by 2020-01-24.

**Comment by NicoleYarroch** [comment]
@zhouxin627 I believe this issue was fixed in PR #1566. I know you submitted a PR (#1528) to fix the issue but I had to do an extensive refactor the secondary transport manager to fix some bugs. Can you test with PR #1566 to see if this bug has been fixed? Thank you.

**Comment by zhouxin627** [comment]
@NicoleYarroch Certainly, I will test with PR #1566 and give you feedback.

**Comment by zhouxin627** [comment]
@NicoleYarroch Hi, this issue has been fixed. Thank you.
