### ISSUE TITLE
SDL lockscreen UIWindow create too early sometimes block app popview.

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#1496]
### Bug Report
[Summary]
SDL created an UIWindow when SDLManager is initialized, it's too early.
This hided UIWindow in some case will block main app's viewcontroller show.

(Suggestion: lockscreen UIWindow can be created just when it needs to present)

##### Reproduction Steps
Just see the demo link below.

##### Expected Behavior
Main app pop view controller can show well.

##### Observed Behavior
Main app pop view controller always can not showed.

##### OS & Version Information
* iOS Version: [What version of iOS are you using when the bug occurred]
v13.1.3
* SDL iOS Version: [What version of the library has this bug been seen on]
v6.4.1

##### Test Case, Sample Code, and / or Example App
https://github.com/84798012/SDL_Window_Rotate_Bug_Reproduce_Demo/tree/master/blockPopIssue

**Comment by NicoleYarroch** [comment]
@84798012 What branch were you using when you found this bug? Where you using branch `bugfix/issue-1480-recreate-lockVC-every-time` used in the [Recreate the lock screen view controller](https://github.com/smartdevicelink/sdl_ios/pull/1483) PR or were you using the master branch (v.6.4.1)?

**Comment by 84798012** [comment]
Thanks.
Seems been fixed.

**Comment by 84798012** [comment]
fixed, so close it.

**Comment by joeljfischer** [comment]
@84798012 Could you please re-test this bug using PR #1509? We ended up doing a large refactor of the lock screen code and would like to confirm that it still fixes all of your issues. Thank you!

**Comment by 84798012** [comment]
I have test on 1509, the issue fixed. Thanks!
