### ISSUE TITLE
When presets is shown, the Proxy sends ShowRPC to the Core, then the displayed presets is disappeared

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_ios#1500]
### Bug Report
When presets is shown, the Proxy sends ShowRPC to the Core, then the displayed presets is disappeared

##### Preconditions
The app uses presets

##### Reproduction Steps
1. Register the app
2. Activate the app
3. Click the Presets button

##### Expected Behavior
`Custompresets `are displayed normally

##### Observed Behavior
`Custompresets `are shown but disappeared in a flash.

1. The SDLScreenManager does not support `custompresets`, so the app has to deal with 
`Graphic/Text/Softbutton` and `customPresets `separately.
2. `Custompresets`'s rule is `If omitted on supported displays, the presets will be shown as not defined`.
App developers might be feeling confused about `custompresets `since it is not consistent with other components(for example `softButtons`).
I suggest that it should be changed to `If omitted on supported displays, the displayed presets shall not change`.

##### OS & Version Information
* iOS Version: 12.3
* SDL iOS Version: 6.3.0
* Testing Against: SDL Core 5.1.3 + HMI running on our development environment.

##### Test Case, Sample Code, and / or Example App
![image](https://user-images.githubusercontent.com/35795928/70579228-4b25e900-1bf3-11ea-8370-3e648bed4847.png)

**Comment by joeljfischer** [comment]
This isn't a bug with this project. There are two possible resolutions to your issue:

1. Add a proposal to add Custom Preset support to the ScreenManager.
2. Add a proposal to change custom preset behavior.

Neither of those is an issue with the sdl_ios repository.
