### ISSUE TITLE
Lock screen dismiss animation breaks

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1504]
### Bug Report
The lock screen dismiss animation breaks the first time the lock screen is shown. 

##### Reproduction Steps
1. App is open on phone
1. TDK is set to "parked"
1. Connect app to TDK (SYNC 3 v3.0)

##### Expected Behavior
The lock screen should show and be dismissed since the vehicle is not moving. The dismissal of the lock screen should be animated. 

##### Observed Behavior
The lock screen should show and be dismissed since the vehicle is not moving. The lock screen dismissal is not animated. 

I believe this is because `dismiss` is called twice in quick succession
due to two driver distraction notifications coming in one right after another. We should probably check if the lock screen is already in the process of being dismissed before doing the dismissal.

##### OS & Version Information
* iOS Version: 13
* SDL iOS Version: 6.4.1
* Testing Against: TDK, SYNC 3, v3.0

**Comment by NicoleYarroch** [comment]
I think this was the bug @SatbirTanda was describing in another lockscreen PR?

**Comment by NicoleYarroch** [comment]
[lockscreen dismissal animation.mov.zip](https://github.com/smartdevicelink/sdl_ios/files/3952576/lockscreen.dismissal.animation.mov.zip)

**Comment by joeljfischer** [comment]
@NicoleYarroch Does #1509 fix this?

**Comment by NicoleYarroch** [comment]
Note: I believe this bug can only be reproduced on SYNC 3 v.3.0
