### ISSUE TITLE
when iphone locked, SDL.iostream always crash.

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#1506]
Using SDL v6.4.1 crash issue. When using v6.3.1 no this issue.
Case1:
when HU side uploading resource, then lock iphone, it will crash.

Case2:
when lock iphone, on HU show alert with ttsChunks, after this will crash.

here attached the crash log. please check it.

[SDL_iostream_crash1.txt](https://github.com/smartdevicelink/sdl_ios/files/3955506/SDL_iostream_crash1.txt)
[SDL_iostream_crash2.txt](https://github.com/smartdevicelink/sdl_ios/files/3955507/SDL_iostream_crash2.txt)
[SDL_iostream_crash3.txt](https://github.com/smartdevicelink/sdl_ios/files/3955508/SDL_iostream_crash3.txt)

**Comment by joeljfischer** [comment]
Hi @84798012, unfortunately, the logs you've provided are not desymbolicated, so we cannot investigate this issue. Additionally, please try to fill out all the information requested in the issue template, including clear reproduction steps. I'm not sure what you mean by "when HU side uploading resource." Is "when lock iphone, on HU show alert with ttsChunks, after this will crash" a separate crash, or related?

**Comment by 84798012** [comment]
I can reproduce easily in my app, but I can not send it here.
So I need some time to make a simple demo to reproduce the case.

**Comment by 84798012** [comment]
I can only reproduce it with (SDL v6.4.1 + iOS 13.1.3) in our app's debug version. But can not reproduce it when release version and iOS 13.2/13.3. So just close it.
