### ISSUE TITLE
[SDL 0269] New vehicle data ClimateData

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_ios#1511]
Proposal: [New vehicle data ClimateData](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0269-New-vehicle-data-ClimateData.md)

> This proposal is to add new vehicle data ClimateData to know cabin temperature, atmospheric pressure and external temperature.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/891

Steering Committee Decision:
>The Steering Committee voted to accept this proposal with the following revisions:

> - Atmospheric pressure range should be extended to `minvalue="0"` and `maxValue="2000"`.
> - Add history tags to the deprecated values.
> - Use existing `Temperature`struct in `externalTemperature` and `cabinTemperature` parameters

The proposal .md file was updated to reflect these revisions on 12/19/19.

**Comment by NicoleYarroch** [comment]
Fixed in PR #1851
