### ISSUE TITLE
"Debug" preprocessor macros

### ISSUE THREAD

**Issue by alekseypotapov-dev** [smartdevicelink/sdl_ios#1514]
### Bug Report
In case if `xcodeproj` doesn't have a `Debug=1` Preprocessor Macros defined inside of its Build Settings/Apple Clang Processing/Preprocessor Macros, the attempt to build a project that uses `sdl_ios` framework will end up with a compile-time error:

> SmartDeviceLink.framework/Headers/SDLLogMacros.h:40:10: error: expected value in expression #if DEBUG

##### Expected Behavior
Project builds with no errors

##### Observed Behavior
An error occurs

##### OS & Version Information
* iOS Version: 13.3
* SDL iOS Version: 6.4.1
* Testing Against: SYNC 3 // actually, this was an attempt to build a project. So I even didn't reach this step.

##### Test Case, Sample Code, and / or Example App
Honestly tried to reproduce it on a new project, but seems like this is a local problem (xcodeproject's custom settings)
Even though this could be fixed easily:
in `SDLLogMacros.h` file on the line **40** replace the following:
```objc
#if DEBUG
```
with
```objc
#if (DEBUG+0) || defined(DEBUG)
```

I will look into it more deeply and provide more updates.

**Comment by joeljfischer** [comment]
@alekseypotapov-dev Unfortunately, I cannot reproduce this even after removing the `DEBUG=1` preprocessor macro.

**Comment by alekseypotapov-dev** [comment]
@joeljfischer neither could I reproduce this error in a sample app to describe the behaviour.
This happens only in our project. Because in some third-party lib header we do `#undef DEBUG` and then `#define DEBUG` without any value assigned. Eventually this happens before import (and compile) of `SmartDeviceLink.framework`. As we use your library without Cocoapods. So the error persists.

I could only offer the next improvement. Replace
```
#if DEBUG
```
with
```
#if DEBUG+0
```
In this case the `#if` directive will not cause an error: `Expected value in expression` when `DUBUG` has no value.

**Comment by alekseypotapov-dev** [comment]
Scenario 1:
```
#undef DEBUG
#define DEBUG 1

#if DEBUG
    #import "non-existing.h" // error here: "'non-existing.h' file not found"
#else
    #import "non-existing-2.h"
#endif
```
---
Scenario 2:
```
#undef DEBUG
#define DEBUG

#if DEBUG // error here: "Expected value in expression" -> exactly this error we are trying to solve
    #import "non-existing.h"
#else
    #import "non-existing-2.h" // also error here: "'non-existing-2.h' file not found"
#endif
```
---
Scenario 3:
```
#undef DEBUG
#define DEBUG

#if DEBUG+0
    #import "non-existing.h"
#else
    #import "non-existing-2.h" // error here: "'non-existing-2.h' file not found" -> what we actually need
#endif
```
---
Scenario 4:
```
#undef DEBUG
#define DEBUG 1

#if DEBUG+0
    #import "non-existing.h" // error here: "'non-existing.h' file not found" -> what we actually need
#else
    #import "non-existing-2.h"
#endif
```

**Comment by alekseypotapov-dev** [comment]
Closing as PR was closed [here](https://github.com/smartdevicelink/sdl_ios/pull/1533).
