### ISSUE TITLE
Fix warnings on storyboard from constraints referencing items not installed

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1521]
### Bug Report
A few warnings are being thrown from SDLLockScreen.storyboard due to constraints being installed that reference items that are not installed.

##### Reproduction Steps
n/a, part of compilation

##### Expected Behavior
No warnings thrown

##### Observed Behavior
Warnings thrown

##### OS & Version Information
* iOS Version: Xcode 11.1.1
* SDL iOS Version: 6.5.0
* Testing Against: n/a

**Comment by theresalech** [comment]
Closed via #1530
