### ISSUE TITLE
[SDL 0266] New vehicle data GearStatus

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#1522]
Proposal: [New vehicle data GearStatus](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0266-New-vehicle-data-GearStatus.md)

> This proposal is to add new vehicle data `GearStatus` to know drive mode and actual gear the transmission has selected.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/881

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions: use `userSelectedGear` in place of `selectedGear` and use the descriptions  for `GearStatus` included in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/881#issuecomment-573838656).
> The proposal .md file was updated to reflect these revisions on 1/21/2020.

**Comment by NicoleYarroch** [comment]
Fixed in PR #1690
