### ISSUE TITLE
The Swift example app shows a warning message when the slider times out

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1526]
### Bug Report
The Swift example app shows a warning message when the slider times out.

##### Reproduction Steps
1. Connect the Swift example app to a SYNC 3 head unit.
2. Display the slider by selecting the option from the menu.
3. Let the slider time-out (i.e. don't dismiss the slider by selecting a button).

##### Expected Behavior
The slider modal should be dismissed when the slider times out. Nothing else should happen.

##### Observed Behavior
The slider modal dismisses but then an alert shows up saying the slider could not be displayed. 

##### OS & Version Information
* iOS Version: 13.0
* SDL iOS Version: 6.5
* Testing Against: SYNC 3.4

**Comment by NicoleYarroch** [comment]
Should check the Obj-C Example app as well for the same behavior.

**Comment by theresalech** [comment]
Closed via #1548
