### ISSUE TITLE
Video Stream does not start when HU tries to Resume an App

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1527]
# Bug Report
When you pull into a gas station while you were streaming a navigation app, you turn off ignition and your phone will lock by itself (or you locked it). Then  you put your gas in your car, turn on your car, and unlock your phone and you would expect the streaming app to continue as normal.  Unfortunately the app does not resume.  Even after hitting cancel on 'Waiting for device' and trying to relaunch the app.  It requires you to force close the app on iOS and reopen it.

The error appears as:

Unable to send video start service request.  
Video State must be in  state STOPPED: VideoStreamingStarting
HMI must be in LIMITED or FULL: FULL

##### Reproduction Steps
1. Launch an encrypted video streaming app on HU
2. Turn off ignition, wait till screen goes off, then turn off the TDK. 
3. Lock your phone with the streaming app still open.
4. Turn on your TDK, start ignition and then unlock your phone
5. Now on SYNC it should say resuming "Streaming App"
6. Expected that video stream should continue, but it fails to even after you tap it again, gets stuck on Waiting for device

##### Expected Behavior
Video Stream should start and succeed

##### Observed Behavior
Video Stream fails to start and succeed

##### OS & Version Information
* iOS Version: 13.1.2
* SDL iOS Version: 6.5.0
* Testing Against: iOS Streaming app called Antelope that uses SDLSecurity for encrypted stream and SYNC 3 V3.4 19220_devtest_r127296

##### Test Case, Sample Code, and / or Example App
Unfortunately we cannot provide the app, but any app with encrypted streaming should work.

logs:
![IMG_0029](https://user-images.githubusercontent.com/22843358/73024469-80247e80-3de2-11ea-9d05-008f8ddc0ffa.PNG)

[AntelopeLog_20200123_130143(HMI).csv.zip](https://github.com/smartdevicelink/sdl_ios/files/4105496/AntelopeLog_20200123_130143.HMI.csv.zip)

**Comment by SatbirTanda** [comment]
Looks like `sdl_startVideoSession` is being called twice

**Comment by NicoleYarroch** [comment]
After some investigation I believe there is a race condition where the video streaming lifecycle manager sends and end service because the `hmiLevel` is NONE but the `hmiLevel` changes to `FULL` while waiting for a response from Core. This results in a video start service not being sent by the manager. I am working on PR to fix this issue.

**Comment by SatbirTanda** [comment]
After a NAK is received, it looks like SDL iOS keeps sending a payload with 12 bytes in response to SDL Core sending ERROR_INVALID_QUERY_SIZE but this error is not parsed out in `sdl_processSecurityMessage` in `SDLProtocol`. It only checks if the payload is nil.  This causes an infinite loop -  "Waiting for device" to appear and spin forever

**Comment by NicoleYarroch** [comment]
I have noticed that I sometimes get a `NAK` when I select the "Nav" button in tab bar and then select the video streaming SDL app. The SDL app does send an end service request but the "Waiting for Device" alert still shows. I will investigate.

**Comment by SatbirTanda** [comment]
These errors are not being handled in iOS:


error code | bytes | description
-- | -- | --
ERROR_SUCCESS | 0x00 | Internal SecuirtyManger value
ERROR_INVALID_QUERY_SIZE | 0x01 | wrong size of query data
ERROR_INVALID_QUERY_ID | 0x02 | unknown query id
ERROR_NOT_SUPPORTED | 0x03 | SDL does not support encryption
ERROR_SERVICE_ALREADY_PROTECTED | 0x04 | got request to protect a service that was protected before
ERROR_SERVICE_NOT_PROTECTED | 0x05 | got handshake or encrypted data for not protected service
ERROR_DECRYPTION_FAILED | 0x06 | decryption failed
ERROR_ENCRYPTION_FAILED | 0x07 | encryption failed
INVALID_CERT | 0x08 | handshake failed because certificate is invalid
EXPIRED_CERT | 0x09 | handshake failed because certificate is expired
ERROR_HANDSHAKE_FAILED | 0x10 | In case of all other handshake errors
ERROR_INTERNAL | 0xFF | internal error
ERROR_UNKNOWN_INTERNAL_ERROR | 0xFE | error value for testing
ERROR_SSL_INVALID_DATA | 0xF0 | SSL invalid data

 I am working on PR to fix this issue.  When these errors are seen, I will set the streaming state to STOPPED.

**Comment by SatbirTanda** [comment]
These errors are not being handled by iOS:


error code | bytes | description
-- | -- | --
ERROR_SUCCESS | 0x00 | Internal SecuirtyManger value
ERROR_INVALID_QUERY_SIZE | 0x01 | wrong size of query data
ERROR_INVALID_QUERY_ID | 0x02 | unknown query id
ERROR_NOT_SUPPORTED | 0x03 | SDL does not support encryption
ERROR_SERVICE_ALREADY_PROTECTED | 0x04 | got request to protect a service that was protected before
ERROR_SERVICE_NOT_PROTECTED | 0x05 | got handshake or encrypted data for not protected service
ERROR_DECRYPTION_FAILED | 0x06 | decryption failed
ERROR_ENCRYPTION_FAILED | 0x07 | encryption failed
INVALID_CERT | 0x08 | handshake failed because certificate is invalid
EXPIRED_CERT | 0x09 | handshake failed because certificate is expired
ERROR_HANDSHAKE_FAILED | 0x10 | In case of all other handshake errors
ERROR_INTERNAL | 0xFF | internal error
ERROR_UNKNOWN_INTERNAL_ERROR | 0xFE | error value for testing
ERROR_SSL_INVALID_DATA | 0xF0 | SSL invalid data

I am working on PR to fix this issue and will set the streaming state to STOPPED when it they are seen.

**Comment by standa1-ford** [comment]
```objc
    // Ask the security manager for server data based on the client data sent
    NSError *handshakeError = nil;
    NSData *serverHandshakeData = [self.securityManager runHandshakeWithClientData:clientHandshakeData error:&handshakeError];
```
handshakeError should be set by the security manager and we should be able to check this from SDL iOS to fail the handshake, however sometimes it is nil or returns `NSCocoaErrorDomain Code=3840 "Garbage at end."`. 

When it is `NSCocoaErrorDomain Code=3840 "Garbage at end."`, and we print out `clientHandshakeData`, we can see the garbage value at the end:
```swift
Optional("{\n   \"id\" : 1,\n   \"text\" : \"SendHandshakeData: null arguments size.\"\n}\n\u{01}")
```

This is causing trouble in trying to parse out the error, I'm trying to convert the `NSData` to an `NSDictionary` but it keeps failing.

**Comment by SatbirTanda** [comment]
```objc
    // Ask the security manager for server data based on the client data sent
    NSError *handshakeError = nil;
    NSData *serverHandshakeData = [self.securityManager runHandshakeWithClientData:clientHandshakeData error:&handshakeError];
```
handshakeError should be set by the security manager and we should be able to check this from SDL iOS to fail the handshake, however sometimes it is nil or returns `NSCocoaErrorDomain Code=3840 "Garbage at end."`. 

When it is `NSCocoaErrorDomain Code=3840 "Garbage at end."`, and we print out `clientHandshakeData`, we can see the garbage value at the end:
```swift
Optional("{\n   \"id\" : 1,\n   \"text\" : \"SendHandshakeData: null arguments size.\"\n}\n\u{01}")
```

This is causing trouble in trying to parse out the error, I'm trying to convert the `NSData` to an `NSDictionary` but it keeps failing.

**Comment by NicoleYarroch** [comment]
@SatbirTanda Were you able to figure out the issue with parsing out the error? If not, would it be helpful for us to look into the issue in the security library and see if it is an issue with how the error is created?

**Comment by SatbirTanda** [comment]
I added this check in `runHandshakeWithClientData` in the security library to handle errors:
```objc
    if (dataToSend.length <= 0) {
        return nil;
    }
```

Ford determined that the reason the streaming does not start successfully on resumption is because AppLink does not set the clock properly on resumption which invalidates the certs iOS downloads.  

However, after that we should be able to start streaming (after the NAK, and tapping cancel on "Waiting for device").  But still investigating if this check prevents video from starting again - all help is appreciated!

**Comment by NicoleYarroch** [comment]
@SatbirTanda Were you able to figure out why video does not stream after the `NAK` and tapping cancel on "Waiting for Device"?

**Comment by SatbirTanda** [comment]
@NicoleYarroch still investigating, my test environment stopped working

**Comment by joeljfischer** [comment]
@SatbirTanda Is this bug still valid? Have you continued work on it?

**Comment by SatbirTanda** [comment]
Yes we are still investigating, but having trouble because my TDK can't stream when WFH.

**Comment by theresalech** [comment]
Closing as inactive. Reporter can advise if issue is still present in iOS 7.2, and we can reopen if needed.
