### ISSUE TITLE
Empty displayCapabilities in setDisplayLayout response prevents display update

### ISSUE THREAD

**Issue by djs98052** [smartdevicelink/sdl_ios#1536]
### Bug Report
While processing the response to `setDisplayLayout`, the `sdl_displayLayoutResponse` method assumes the presence of `response.displayCapabilities` while the protocol specification indicates this is an optional field in the response. If the response contains an empty `displayCapabilities` field, then the cached value for `displayCapabilities` gets overwritten and subsequent attempts to update the display fail because the capabilities of the display cannot be determined. 

##### Reproduction Steps
1. Call `screenManager.setDisplayLayout`
2. Call `screenManager.beginUpdates()`
3. Call `screenManager.title = "Title"`
4. Call `screenManager.endUpdates()`

##### Expected Behavior
Title is shown on the screen

##### Observed Behavior
Title is not shown on the screen

##### OS & Version Information
* iOS Version: Simulator 11.4, iPhone 8+ 12.4
* SDL iOS Version: 6.4.1
* Testing Against: Emulator

##### Test Case, Sample Code, and / or Example App
```
smartDeviceLinkManager.sdlManager.send(request: setLayoutRequest) { _, response, error in
    guard response?.success.boolValue ?? false == true else {
        logError("Error setting display layout: \(String(describing: error))")
        return
    }
    let screenManager = self.smartDeviceLinkManager.sdlManager.screenManager
    screenManager.beginUpdates()
    screenManager.title = NSLocalizedString("My Title", comment: "")
    screenManager.primaryGraphic = self.logoArtwork
    screenManager.softButtonObjects = [self.meetingListButton, self.meetingRoomButton]
    screenManager.endUpdates()
}
```

**Comment by joeljfischer** [comment]
After investigation, this particular example appears to not be an issue. We always send the `templateTitle` even if the head unit doesn't support it. The emulator you are using probably does not support a template title.

With that said, in the course of the investigation, we found that the underlying issue is valid for other text fields and image fields.

**Comment by joeljfischer** [comment]
@djs98052 do you remember which emulator you were using?
