### ISSUE TITLE
The secondary transport manager should not end the audio service when device app is put in the background

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1544]
### Bug Report
The secondary transport manager should not end the audio service when the app on the device is put in the background. The video stream is suspended because of an iOS limitation with streaming video while the app on the device is backgrounded. However, audio should still be able to stream even if the app on the device is backgrounded  

##### Reproduction Steps
1. Connection a navigation app to a TDK that supports secondary transports. Launch the SDL app on the TDK by selecting the app icon.
1. Put app on device in background.

##### Expected Behavior
Audio should not be suspended.

##### Observed Behavior
An end audio service request is sent thus no audio can play while the app is backgrounded.  

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.5
* Testing Against: SYNC 4 (20016_DEVTEST)

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by NicoleYarroch** [comment]
Closing this issue because the TCP socket should be closed when the app is locked or backgrounded per [Apple's documentation](https://developer.apple.com/library/archive/technotes/tn2277/_index.html#//apple_ref/doc/uid/DTS40010841-CH1-SUBSECTION9) as socket's resources will get reclaimed by the kernel.

**Comment by mrapitis** [comment]
@NicoleYarroch would the app utilizing an iAP accessory be an exception to this rule though?
https://forums.developer.apple.com/thread/97824

**Comment by NicoleYarroch** [comment]
That is what I thought, however I've been testing this with SYNC 4 and every time I lock the iPhone, within a few seconds, I get an `NSStreamEventHasBytesAvailable` event. Then when I read from the input stream I get an error saying that the "socket is not connected". When this error happens, we must close the socket. However, we could investigate re-opening a new socket immediately.

**Comment by NicoleYarroch** [comment]
Reopening this issue to do some investigation on whether or not a socket can be recreated after the device is locked.

**Comment by NicoleYarroch** [comment]
After some investigation, I am closing this issue as it is currently impossible to keep the TCP socket alive longer than ~1 minute when the app on the device is backgrounded or the when the device is locked when the app on the device is in the foreground. Below is a summary of my findings.

### Current Implementation
* Currently the library stops video streaming and closes the TCP socket when app is put into the background. This solution was implemented because iOS can suspend the app any time the app is not in the foreground. When the app is suspended, the TCP socket errors due to the system reclaiming the socket's resources (https://stackoverflow.com/a/53256941).
* I attempted to keep the TCP socket open when the app is backgrounded. However, when testing with an iPhone 11 (iOS 13) and iPhone 6 (iOS 12), the socket always errors out within a few seconds of the device locking. If the app is backgrounded on the device by clicking the home button, the socket is usually (but not always) kept alive.

### Attempted Solutions
1. Starting a background task when the app on the device is backgrounded keeps the socket open for ~1 minute.
1. To keep the socket open, I tried starting a new background task when the old one expires, however as soon as the first background task expires, either the input or output stream errors with: `Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}` or with `Error Domain=NSPOSIXErrorDomain Code=32 "Broken pipe" UserInfo={_kCFStreamErrorCodeKey=32, _kCFStreamErrorDomainKey=1}`.
1. Since the current code only sends 30 background frames immediately when the app backgrounds, I thought the TCP socket might be closed by Core due to a heartbeat timeout. I tried sending a continuous stream of video frames (60fps) when the app was backgrounded, however this did not keep the socket from erroring. 
1. Enabling "Audio, AirPlay, and Picture in Picture" or the "VoIP" background modes did not prevent the socket from erroring when the device is locked.
