### ISSUE TITLE
Lock screen prevents CarWindow from streaming video

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1545]
## Bug Report
When a video streaming app using the `CarWindow` API connects to a head unit, the `CarWindow` class can not stream video due to it thinking that the lock screen is in the process of being dismissed. 

This only seems to be an issue on iOS 12. I can't reproduce with the same app on iOS 13. It looks like the completion handler is not called when `dismissViewControllerAnimated` is called on a view controller that is not presented.   

##### Reproduction Steps
1. Connect an iOS 12 phone with a video streaming SDL app to a TDK. The video streaming app should use the `CarWindow` API.

##### Expected Behavior
Video should start streaming

##### Observed Behavior
The `CarWindow` class does not stream video because it thinks the lockscreen is in the process of being dismissed. 

##### OS & Version Information
* iOS Version: iOS 12
* SDL iOS Version: 6.5
* Testing Against: SYNC 4 (20016_DEVTEST)

**Comment by joeljfischer** [comment]
Fixed in #1523
