### ISSUE TITLE
[SDL 0274] Add preferred FPS to VideoStreamingCapability

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#1553]
Proposal: [Add preferred FPS to VideoStreamingCapability](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0274-add-preferred-FPS.md)

> This proposal extends SDL video streaming feature by adding preferred FPS to `VideoStreamingCapability`, so that frame rate of video streaming can be adjusted per OEM.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/913

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions.  The revisions will include the items listed in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/913#issuecomment-579062117) from the author.

> The proposal .md file was updated to reflect these revisions on 2/10/2020.

**Comment by NicoleYarroch** [comment]
Fixed in PR #1613
