### ISSUE TITLE
Video Streaming

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#156]
We need to have a conversation around how this ought to be implemented

**Comment by Heath-FoMoCo** [comment]
What do you mean by "navigation"?

**Comment by joeljfischer** [comment]
@Heath-FoMoCo Fixed the title, sorry about that

**Comment by Heath-FoMoCo** [comment]
Thanks,
We have this "mostly" implemented.  @hugh22 can explain details.

**Comment by joeygrover** [comment]
@Heath-FoMoCo @hugh22 is it possible for you to create a pull request for this so the community can see progress?

**Comment by hugh22** [comment]
Which part? Raw h.264 Video streaming capability is in the pull request submitted since February 26. You can show the community some progress by pulling that in.

After our meeting with Julius I was under the impression that you folks were going to handle the migration of moving the hardware encoding in to the proxy. Is that correct?

**Comment by joeygrover** [comment]
I think we briefly discussed how it would be a lot easier to merge if that pull request  #105  was broken up into the specific pull requests that relate to their respective fixes/features. Then we can hopefully get all those changes into the main branch.

**Comment by idamaster** [comment]
perhaps we can discuss what was in the pull request at the next meeting and see what makes sense to logically break down?

**Comment by joeljfischer** [comment]
I would prefer to do it 'offline', since it might take a while and I don't think it's really beneficial to a public call. I also need a bit of time to look over it as well, which I haven't had time to do with the 4.0 features still running behind.

**Comment by justinjdickow** [comment]
We have the same issue here as #106 - need a priority because this is a v 3 feature. I also do not understand how an application figures out whether a head unit its connected to with v 3 or higher actually supports video streaming (by failing to open the video streaming service?)
