### ISSUE TITLE
Streaming video manager needs handle `EndSession` control frames 

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1562]
### Bug Report
Core expects an `EndServiceACK` control frame in response to an `EndService` control frame for video and audio.  If it does not get a response, then the SDL app is unregistered. 

We may have to ACK the `EndService` but then also send our own `EndService`. If we just ACK the `EndService` we might break existing head units. 

##### Reproduction Steps
1. Connect a video streaming app with secondary transports enabled to a head unit that supports secondary transports. Launch the SDL app if necessary and wait for video to start streaming.
1. Put the app on the device in the background. 
1. Bring the app to the foreground. 

##### Expected Behavior
The library handles the `EndService` control frame and attempts to create a new video/audio session.  

##### Observed Behavior
Video start service send by the library ACKs but soon after Core sends an `EndService` control frame for video and/or audio and the app is unregistered due to the library not handling this control frame.  

##### OS & Version Information
* iOS Version: 13
* SDL iOS Version: 6.5
* Testing Against: SYNC 4

**Comment by lapinskijw** [comment]
PR #1571 was tested, handling the EndSession control frames sent by Core does not prevent Core from unregistering the app with a PROTOCOL_VIOLATION.
