### ISSUE TITLE
Scale Workaround for legacy high-res displays

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_ios#1567]
### Bug Report

Requesting a workaround for two head units with high-resolution displays that don't support scale values. The reason is per user complaints but also (and more importantly) these displays won't meet driver distraction guidelines for SDL navigation apps. With "pixel density and scale" API the workaround is rather small allowing these head units to increase the appearance of the app UI elements.

##### Reproduction Steps
1. Start an IVI (see below affected 10" IVIs)
2. Register an SDL application with NAVIGATION HMI type
3. Start the application on the IVI 

##### Expected Behavior
- App UI should be of decent size.
- Button size should be big enough to hit.
- App performance should be decent.

##### Observed Behavior
- The app UI is very small. 
- Buttons are hard to hit.
- Framerate is very low

##### OS & Version Information
* iOS Version: Irrelevant
* SDL iOS Version: 6.5.0
* Testing Against: Ford Explorer 10" portrait or Lincoln Navigator 10" landscape

**Comment by theresalech** [comment]
Closed via #1585
