### ISSUE TITLE
[SDL 0282] Screen Manager Alert Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#1579]
Proposal: [Screen Manager Alert Manager](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0282-screen-manager-alerts.md)

> This proposal adds alert management (based on the Alert RPC) to the screen manager API.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/948

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the following revisions:

- Use a builder pattern as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/948#issuecomment-592122717).
- Change `SDLAlertAudioData` to be a subclass of `SDLAudioData`.
- Change the audio data property and initializer to take an array to allow for multiple pieces of audio data.
- Clarify "if the error value is present, then the alert failed to appear or the user aborted it, if not, then the alert dismissed without error." within the inline documentation for `presentAlert`.

> The proposal .md file was updated to reflect these revisions on 3/9/2020.

**Comment by jordynmackool** [comment]
The proposal markdown file has been updated per the revisions included in the accepted [Revise SDL-0282 Screen Manager Alert Manager](https://github.com/smartdevicelink/sdl_evolution/issues/1120). 

Accepted revisions can be reviewed in the merged PR here: https://github.com/smartdevicelink/sdl_evolution/pull/1111.
