### ISSUE TITLE
Race Condition Crash when Reconnecting in Text and Graphic Manager

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1595]
### Bug Report
There's a potential race condition crash in the Text and Graphic Manager when reconnecting due to `sdl_displayCapabilityDidUpdate` being called before the manager is ready and results in it sending text and graphics.

##### Reproduction Steps
1. Connect to a head unit using an app that has some text
2. Disconnect
3. Reconnect

##### Expected Behavior
No crash

##### Observed Behavior
Crash

##### OS & Version Information
* iOS Version: 13.3.1 (or n/a)
* SDL iOS Version: 6.6-develop
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

**Comment by NicoleYarroch** [comment]
Fixed in PR #1596
