### ISSUE TITLE
Deprecate SyncPData and SyncPDataResponse

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1599]
### Bug Report
These RPCs have been deprecated and removed from the RPC spec. We should deprecate and eventually remove them from the library as well.

**Comment by mrapitis** [comment]
@joeljfischer just a quick note, while its likely ok to deprecate the API's behind SyncP data we won't be able to actually remove the RPC's since existing Sync Generation 1.1 implementations actually use this RPC to perform a policy table update.

**Comment by joeljfischer** [comment]
@mrapitis Are you talking about `EncodedSyncPData` or `SyncPData`? `SyncPData` is already removed from the API, so I believe we should remove them. Additionally, `EncodedSyncPData` and `SyncPData` appear to already be removed from the Java Suite library.

**Comment by mrapitis** [comment]
@joeljfischer EncodedSyncPData is still used by Sync 1.1 which is still in use and supported in the field.  It looks like EncodedSyncPData is still present in the master and develop branches of the JavaSuite. 
 
https://github.com/smartdevicelink/sdl_java_suite/blob/93778656113f0023ec7025281b77e28000a1f5bd/base/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java#L43

https://github.com/smartdevicelink/sdl_java_suite/blob/develop/base/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java#L43

**Comment by joeljfischer** [comment]
Those are just the function IDs. I haven't been able to find any reference to the actual RPC. Let me know if you do.

**Comment by mrapitis** [comment]
https://github.com/smartdevicelink/sdl_java_suite/blob/master/base/src/main/java/com/smartdevicelink/proxy/rpc/SystemRequest.java#L100  
Even though the API is labeled as a SystemRequest, its actually using the EncodedSyncPData data function ID and data structure.

**Comment by joeljfischer** [comment]
Aha, that's probably why I missed it. Thanks. Just to make sure we're clear, we are okay to remove `SyncPData` in the next release, but not `EncodedSyncPData`. That was the eventual plan anyway, since `SyncPData` is removed from the RPC spec but `EncodedSyncPData` is only deprecated but still available.

**Comment by mrapitis** [comment]
> Aha, that's probably why I missed it. Thanks. Just to make sure we're clear, we are okay to remove SyncPData in the next release, but not EncodedSyncPData. That was the eventual plan anyway, since SyncPData is removed from the RPC spec but EncodedSyncPData is only deprecated but still available.

Yes, exactly. We are on the same page.
