### ISSUE TITLE
Deprecate SDLOnLockScreenStatus / SDLLockScreenStatus

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1601]
### Bug Report
As part of a pre-lock screen manager lock screen solution, these fake RPCs were created. We should deprecate them so that we may remove them in the future.

**Comment by NicoleYarroch** [comment]
@joeljfischer The `SDLLockScreenStatus` enum is used extensively by the `SDLLockScreenStatusManager` and the `SDLLockScreenManager` to determine whether or not the lock screen should be presented. I think the `SDLLockScreenStatus` enum should be kept as it will be needed even when the `SDLOnLockScreenStatus` notification is removed.

**Comment by joeljfischer** [comment]
@NicoleYarroch I think something like it will probably be kept (as a private enum, so it should still be deprecated), but it won’t be a fake SDL enum. It will probably be turned into a standard iOS enum instead. The lock screen status manager will eventually go away as well and / or moved into a sub-object of the LSM. All the logic should be captured by the LSM.
