### ISSUE TITLE
SDLStreamingMediaManagerDataSource methods should be marked as optional

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1630]
### Bug Report
The `SDLStreamingMediaManagerDataSource`'s methods  should be marked as optional otherwise if the developer wants to use the default screen size they have to use the now deprecated `registerResponse.displayCapabilities.screenParams.resolution` or make a request for the `videoCapability`. Setting an empty array stops the video stream manager. 

##### Reproduction Steps
1. If the developer just wants to use the `SDLStreamingMediaManagerDataSource` to set a `preferredVideoFormatOrder` but not the screen resolution they still have to implement the `resolution:` method since it is non-optional. They then have find the module's screen resolution themselves and set it.   

##### Expected Behavior
Both methods on the `SDLStreamingMediaManagerDataSource` protocol should be optional. 

##### Observed Behavior
Both methods on the `SDLStreamingMediaManagerDataSource` protocol are required. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.5
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by joeljfischer** [comment]
Closing as invalid. The developer can just implement something like this, there's no need for them to look at the `registerResponse` or anything like that:

```objc
- (NSArray<SDLImageResolution *> *)resolutionFromHeadUnitPreferredResolution:(SDLImageResolution *)headUnitPreferredResolution {
    return @[headUnitPreferredResolution];
}
```
