### ISSUE TITLE
MainThread checker warning at `sdl_handleSystemRequestLaunchApp` function

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#1662]
### Bug Report
`sdl_handleSystemRequestLaunchApp` function in `SDLProxy.m` calls `[[UIApplication sharedApplication] openURL]`, this call can cause warning by Xcode main thread checker because it can be executed other than the main thread.

`sdl_handleSystemRequestLaunchApp` should be called only in the main thread.

##### Reproduction Steps
1. Enable “Main Thread Checker” in Xcode, and run application in debug mode.
2. Connect app to HU 
3. Make app foreground on HS
 4. Run app on HU 
5. Run another app on HU 
6. Observe console log in HS

##### Expected Behavior
MainThread checker warning is NOT logged.

##### Observed Behavior
MainThread checker warning is logged.

##### OS & Version Information
* iOS Version: 13.0
* SDL iOS Version: 6.3.1
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App
I will create PR

**Comment by NicoleYarroch** [comment]
Fixed in PR #1663
