### ISSUE TITLE
use MD5 in SmartDeviceLink will cause integrate failed 

### ISSUE THREAD

**Issue by blzhu** [smartdevicelink/sdl_ios#1668]
[SDLIAPTransport sdl_retryDelay] calls _CC_MD5()
[SDLArtwork sdl_md5HashFromNSData:] calls _CC_MD5()
when we integrate SDL, scanning tool report this defect, it easy to fix, but if have these defects , our app can not integrate SDL for security concern. I hope you fix it soon

**Comment by joeljfischer** [comment]
Duplicate of #1673
