### ISSUE TITLE
Encrypted RPC service invalid state machine transition of target SDLEncryptionLifecycleManager after transport disconnect

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_ios#1675]
### Bug Report
 Once a connection is successful established by our test app with encryption on the startRPCEncryption method is called, where the EncryptionLifeCycleManager class handles the state of encryption machine. Once the connection is disrupted (e.g. transport disconnect) the EncryptionLifeCycleManager is stopped, but the encryption state is not updated to "EncryptionStopped" and is left in the "EncryptionReady" state. Hence, the next time the app tries to reconnect and start encryption the following exception is thrown "Invalid state machine SDLStateMachine transition of target SDLEncryptionLifecycleManager occurred from EncryptionReady to EncryptionStarting".

##### Reproduction Steps
Build a test app that leverages the startRPCEncryption method utilizing the encrypted RPC service
Register with the headunit and successfully start the encrypted RPC service
Disconnect the transport
Re-Register with the headunit and attempt to start the encrypted RPC service
Take note of the exception thrown mentioned above 

Please note adding the following code above the line linked seems to have resolved the exception
`` [self.encryptionStateMachine transitionToState:SDLEncryptionLifecycleManagerStateStopped];``
https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLEncryptionLifecycleManager.m#L80

##### Expected Behavior
Application successfully starts the encrypted RPC service after a transport disconnect with no exception

##### Observed Behavior
An exception is thrown when trying to start the encrypted RPC service after a transport disconnect

##### OS & Version Information
* iOS Version: 13.5.1
* SDL iOS Version: 6.6.0
* Testing Against: Sync HU

**Comment by theresalech** [comment]
We were able to reproduce this issue, and then confirmed it fixed with PR #1699.  Closing as fixed.  @mrapitis, if you are still seeing this issue, please let us know and we can re-open.
