### ISSUE TITLE
Set `VTSessionSetProperty` when the compression session is recreated 

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1683]
### Bug Report
I tried to set `VTSessionSetProperty` in `sdl_resetCompressionSession` method, it works fine, issue is fixed.
I found that `sdl_resetCompressionSession` will be called when received `startNaviServiceACK` from HeadUnit.

##### Reproduction Steps
1. SDLStreamingVideoLifecycleManager.m->didEnterStateVideoStreamReady
1. SDLH264VideoEncoder.m->initWithProtocol
1. SDLH264VideoEncoder.m->newPixelBuffer
1. SDLH264VideoEncoder.m->pixelBufferPool
1. SDLH264VideoEncoder.m->sdl_resetCompressionSession

##### Expected Behavior
Video playback is smooth.

##### Observed Behavior
Video playback is not smooth.

##### OS & Version Information
* iOS Version: unknown
* SDL iOS Version: 6.6
* Testing Against: unknown

**Comment by outoraei** [comment]
iOS Version: 13.2.3 iPhone11Pro 
Testing Against: SDL Core 6.1.1 + HMI running on our development environment.

**Comment by NicoleYarroch** [comment]
@outoraei Can you check if PR #1700 fixes your issue?
