### ISSUE TITLE
Investigate dropped frames in video stream

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1701]
### Bug Report
Take a look at this video, seems like some frames are being lost (or not shown). While I am sending 9 images back and forth, the animation sometimes is not full.

[sdl-ball-animation.mov.zip](https://github.com/smartdevicelink/sdl_ios/files/4851489/sdl-ball-animation.mov.zip)

##### Reproduction Steps
1. While I am sending 9 images back and forth, the animation sometimes is not full.

##### Expected Behavior
All video frames should be shown.

##### Observed Behavior
Some video frames are dropped.

##### OS & Version Information
* iOS Version: iOS 13.5 (iPhone XSMax)
* SDL iOS Version: 6.6
* Testing Against: SYNC 3.3 (build 19016_Devtest)

##### Example Project
https://www.dropbox.com/s/adisrkej09122nr/Sygic-sample-project.zip?dl=0

**Comment by joeljfischer** [comment]
Closed for inactivity
