### ISSUE TITLE
RPC spec generator should add required/optional to each parameter's documentation

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1721]
### Bug Report
The RPC spec generator should add "Required" or "Options" to each parameter's documentation like so:

```
/**
 * See TurnSignal
 * 
 * Optional
 *
 * @since SDL 5.0.0
 */
@property (nullable, strong, nonatomic) NSNumber<SDLBool> *turnSignal;
```
##### Reproduction Steps
1. Run the generator script in the "generator" folder of the library.

##### Expected Behavior
The generated documentation for each parameter in the class or struct should include "Required" or "Optional".

##### Observed Behavior
The generated documentation for each parameter does not include whether or not the parameter is required.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.6
* Testing Against: n/a

**Comment by joeljfischer** [comment]
This isn't necessary. The nullability adequately describes if it's required or optional.
