### ISSUE TITLE
RPC spec generator uses VehicleData twice in the SDLVehicleDataType enums

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1737]
### Bug Report
The RPC spec generator uses `VehicleData` twice in the name for `SDLVehicleDataType` enums. 

##### Reproduction Steps
1. Run the generator script in the "generator" folder of the library.

##### Expected Behavior
For the new `VehicleDataType` enum `VEHICLEDATA_PRNDL`, it should create an enum called `SDLVehicleDataTypePrndl`.

##### Observed Behavior
It names the enum `SDLVehicleDataTypeVehicledataPrndl`.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.6
* Testing Against: n/a

**Comment by joeljfischer** [comment]
This is a known issue and we aren’t doing exceptions to the general rule. This should be closed.
