### ISSUE TITLE
RPC spec generator strips text after @TODO

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1744]
### Bug Report
The RPC spec generator is designed to strip any `@TODO`s from the documentation, however if the `@TODO` comes in the middle of a sentence, then the rest of text after the `@TODO` is not preserved.

The code to strip `@TODO`s is in the **common_producer.py** script in the `extract_description` method.

##### Reproduction Steps
1. Run the generator script in the "generator" folder of the library.

##### Expected Behavior
The `@TODO` should be stripped from the sentence. 

For example, in the RPC Spec for the `RegisterAppInterface` request, the `ttsName` description has a `@TODO`. 

```
<param name="ttsName" type="TTSChunk" minsize="1" maxsize="100" array="true" mandatory="false" since="2.0">
    <description>
        TTS string for VR recognition of the mobile application name, e.g. "My S D L App".
        Meant to overcome any failing on speech engine in properly pronouncing / understanding app name.
        Needs to be unique over all applications from the same device.
        May not be empty.
        May not start with a new line character.
        Only characters from char set [@TODO: Create char set (character/hex value) for each ACM and refer to] are supported.
    </description>
</param>
```

It should generate:
```
/**
 * TTS string for VR recognition of the mobile application name, e.g. "My S D L App". Meant to overcome any failing on speech engine in properly pronouncing / understanding app name. Needs to be unique over all applications from the same device. May not be empty. May not start with a new line character. Only characters from char set are supported
 *
 * @since SDL 2.0.0
 */
```

##### Observed Behavior
The rest of the sentence is stripped after `@TODO`

```
/**
 * TTS string for VR recognition of the mobile application name, e.g. "My S D L App". Meant to overcome any failing on speech engine in properly pronouncing / understanding app name. Needs to be unique over all applications from the same device. May not be empty. May not start with a new line character. Only characters from char set
 *
 * @since SDL 2.0.0
 */
```

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.7
* Testing Against: n/a

**Comment by joeljfischer** [comment]
I disagree here. Trying to strip the `@TODO` based on the `[]` is pretty complicated and won't necessarily work in all cases. Instead of trying to write some regex that will do that and will be brittle, we should just show the `@TODO`. I don't see a compelling reason not to, and we can always fix the documentation by hand if we don't like it.
