### ISSUE TITLE
Feature Request: Compile BiSON with bitcode enabled YES

### ISSUE THREAD

**Issue by alekseypotapov-dev** [smartdevicelink/sdl_ios#1746]
### Feature request
Build BiSON framework with bitcode enabled flag

##### Reproduction Steps
1. Install SmartDeviceLink via Cocoapods
2. Setup Xcode project settings with bitcode enabled YES
3. Build the project

##### Expected Behavior
Project builds

##### Observed Behavior
An error occured:
> ld: bitcode bundle could not be generated because ‘/Users/username/Library/Developer/Xcode/DerivedData/App-bhkscctlydeerxfkchcmksrzlrhn/Build/Products/Debug-iphoneos/BiSON/BiSON.framework/BiSON’ was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file ‘/Users/username/Library/Developer/Xcode/DerivedData/App-bhkscctlydeerxfkchcmksrzlrhn/Build/Products/Debug-iphoneos/BiSON/BiSON.framework/BiSON’ for architecture arm64

##### OS & Version Information
* iOS Version: 13.5.1
* SDL iOS Version: 6.7
* Testing Against: N/A

##### Additional info:
There is a possibility to override cmake compiler, [like it was done for OpenSSL (line 82) ](https://gist.github.com/felix-schwarz/c61c0f7d9ab60f53ebb0#file-openssl-build-sh-L82).

**Comment by joeljfischer** [comment]
Hello, we have an iOS app with Bitcode enabled that uses Cocoapods for SDL and is submitted to the app store and does not exhibit this error when archived or submitted. I also tested with a test app and the issue didn't appear there either.

Is there another way that this may have happened to your app? What is the minimum version of your app? What is the version of Cocoapods you are using?

**Comment by joeljfischer** [comment]
This is being closed due to inactivity
