### ISSUE TITLE
SDL Lock screen prevents calls to presentViewController

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_ios#1748]
### Bug Report
An app partner reported that the native app experience presents another view controller in order to execute a feature. Now in the SDL experience, calling `presentViewController:animated:completion:` has no effect but a log line

> Attempt to present <0x125955400> on <SDLLockScreenRootViewController: 0x129846210> whose view is not in the window hierarchy!

We are working on possible refactoring to decouple the need of that view controller, however this is pretty inconvenient for any app partner. Appreciate any feedback or ideas to improve the situation for the partner.

##### Reproduction Steps
1. Connect iPhone to SYNC
2. Start the Test App
3. Tap on button so that app calls present View Controller

##### Expected Behavior
Either: The presenting view controller becomes visible above the lock screen.
Or ideally: The presenting view controller starts behind the lock screen (probably impossible).

##### Observed Behavior
The call has no effect except an error log (see above)

##### OS & Version Information
* iOS Version: 13.6
* SDL iOS Version: reported against 6.5.0 
* Testing Against: Ford SYNC3 systems

##### Test Case, Sample Code, and / or Example App
Proprietary app available and can be shared for testing. It should be easy to reproduce with Hello SDL as well (a soft button which presents some view controller).

**Comment by joeljfischer** [comment]
Hi, I tried to replicate the issue and was unable to. Presenting a VC underneath the lock screen seemed to work fine on SDL v7.0.0-develop.

See here: https://github.com/smartdevicelink/sdl_ios/tree/testing/issue-1748

1. Use the Swift example app. 
2. Open Manticore and turn driver distraction on.
3. Connect the app to Manticore. 
4. Put the app into FULL
5. See the `VIEW DID LOAD` and `VIEW DID APPEAR` logs show up 3 seconds later from the presented VC.
6. Turn off driver distraction. See the VC displayed.

**Comment by kshala-ford** [comment]
@joeljfischer I'm sorry. I am afraid I missed the most important information to this bug. This bug only appears to happen for mobile navigation apps. I just retested it again (but against 6.7.0) and the issue still occurs.

**Comment by joeljfischer** [comment]
I did more testing for this additional use-case, and I'm still not seeing the issue. I used a video streaming app (off-screen streaming, as is recommended), then presented a view controller while the lock screen was present, dismissed the lock screen, and could see the VC (barring one issue – there seems to be a bug in iOS where the default backing view of the VC is transparent and cannot be made to be opaque). I then dismissed that VC and it dismissed correctly.

**Comment by kshala-ford** [comment]
@mjuarez-ford FYI

@joeljfischer to my knowledge off-screen rendering wasn't an option for the partner but things might have changed since they refactored to use scenes. We will try to create a new main view controller and see if presentViewController works.

**Comment by joeljfischer** [comment]
@kshala-ford, I'm going to close this issue due to inactivity. Please let me know if it should be reopened!
