### ISSUE TITLE
RPC spec generator should not add the patch version to the generated docs for a parameter

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1752]
### Bug Report
The RPC spec generator should not add the patch version to the generated docs for a parameter.

##### Reproduction Steps
1. Run the generator script in the "generator" folder of the library.

##### Expected Behavior
For the `SDLImageFieldName` enum `SDLImageFieldNameSubtleAlertIcon`, It should not add the SDL patch version to the documentation like so:

```
/**
 * The image of the subtle alert; applies to `SubtleAlert` `alertImage`
 *
 * @since SDL 7.0
 */
extern SDLImageFieldName const SDLImageFieldNameSubtleAlertIcon;
```

##### Observed Behavior
It adds the patch version: 

```
/**
 * The image of the subtle alert; applies to `SubtleAlert` `alertImage`
 *
 * @since SDL 7.0.0
 */
extern SDLImageFieldName const SDLImageFieldNameSubtleAlertIcon;
```

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.8
* Testing Against: n/a

**Comment by joeljfischer** [comment]
Decided not to fix after discussion with broader team.
