### ISSUE TITLE
`SetGlobalProperties` init is missing `userLocation`

### ISSUE THREAD

**Issue by FrankElias77** [smartdevicelink/sdl_ios#1771]
### Bug Report
`userLocation` variable is not included when initializing `SetGlobalProperties`.

##### Reproduction Steps
1. Look for SDLSetGlobalProperties.
2. Check init function.

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: [What version of the library has this bug been seen on]
* Testing Against: N/A

**Comment by NicoleYarroch** [comment]
Fixed in PR #1775
