### ISSUE TITLE
SDL 4.0 RegisterAppInterface Response "sdlVersion" / "systemSoftwareVersion"

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#178]
I have heard some discussion today that this may/should go away. We need to have a discussion around what this is, what developers can/should do with it, and if it ought to exist.

I'm looking at this spec: http://pastebin.com/F8Eyknjy

**Comment by stefanek22** [comment]
While there are a few motivating factors behind providing the versions of both the SDL release as well as the system's software, the biggest ones would be for both diagnostic and tracking purposes.  If there are issues seen in the field, these values could give better insight if problem lies in a specific release of SDL or head unit integration.  Furthermore, any local debugging would also have this clear information.

**Comment by joeljfischer** [comment]
Makes sense. The only issue that I would still bring up about these is that having them be a string brings up some complications. For instance if you to check against a few different version types for an extraordinarily critical bug fix, or whatever, then you would have to parse a semantic version from a string. I normally would not advocate for adding new types to the spec, but I perhaps an alternative would be a new struct that looks like:

SemVersion:
Major: Int
Minor: Int
Patch: Int
Prerelease (optional): String (For instance, alpha-1, beta-3, RC-4)

This could make it easier to parse and check versions if we had to at runtime, while still making it trivial to print the string, since we're just concatenating the struct like: "(major).(minor).(patch)-(prerelease)".

Any thoughts on this?

**Comment by stefanek22** [comment]
No arguments there (with the better formatted sdlVersion)... but systemSoftwareVersion would remain a string, correct?

**Comment by joeljfischer** [comment]
Well that depends on what systemSoftwareVersion is. Is it the version of core that is running on the head unit that we're connected to? If so, then I imagine it would be the same semantic versioning type. If not, then what precisely is it?

**Comment by stefanek22** [comment]
It would be the module's software version (that integrated whatever version of SDL Core).  The reasoning here is there is no way to guarantee (or expect) it follows this format, since we do not control that.

**Comment by joeljfischer** [comment]
Right, since it would only be for debugging purposes to pass on to the developer, I think that's okay.

So we have: 
* systemSoftwareVersion: Head Unit version - String
* sdlVersion: Version of Core (or equivalent) running on Head Unit (SemVer)?

Agree on those two points? @joeygrover @justinjdickow any other thoughts?

**Comment by justinjdickow** [comment]
![giphy](https://cloud.githubusercontent.com/assets/3627664/7187378/0c5f9d20-e43e-11e4-9a6a-a2213a735a8d.gif)

**Comment by joeljfischer** [comment]
Now I'm actually thinking about this again. If the sdlVersion is the version of Core or equivalent, if it's a version of equivalent (for instance Joey's SDL Android port), then I'm not sure how we'd differentiate between what is a Core version vs. Not a Core version.

If we consider this as purely debug information for the developer / analytics information, then this works, with both as a string.

However, if we had planned to use the sdlVersion to work around potential bugs (which I still don't really think is a good idea) then we will need to come up with some way to differentiate. I don't think that's a good idea because of the open nature of the project, to try to identify individual versions of individual radios to work around sounds like an exercise in futility to me.

**Comment by justinjdickow** [comment]
I think including the SDL version is necessary in the case that something does go awfully wrong with a specific version of SDL that makes a production release.  Since we have an automotive context it seems right to make sure that we can target software versions of SDL.

My concern with system version is that I don't want to introduce corner cases into the mobile proxies that are specific to an OEM's implementation of SDL. I'm not sure how we can guarantee that doesn't happen, but as long as system version is for debugging only, then it seems okay.

**Comment by joeljfischer** [comment]
> I think including the SDL version is necessary in the case that something does go awfully wrong with a specific version of SDL that makes a production release. Since we have an automotive context it seems right to make sure that we can target software versions of SDL.

This issue with the above, is that I think it will *cause* the below:

> My concern with system version is that I don't want to introduce corner cases into the mobile proxies that are specific to an OEM's implementation of SDL.

What do we do when an OEM builds a custom "Core", as we did for the SDL Android demo? How do we differentiate versions between them? What if a bug in core only causes one or a very few head units to have a bug? Where do we draw the line? This creates vast tracts of gray area, and I think, possibly even opens us up for liability if we start fixing bugs on our side caused by some implementations, but don't for others. It's better to avoid this altogether.

**Comment by justinjdickow** [comment]
They are both strings.
