### ISSUE TITLE
SYNC 3.0 bug with iAP transport

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1795]
### Bug Report
When connecting 15 SDL apps to SYNC 3.0 using iAP (USB) transport and the multisession protocol, between 1-3 apps fail to connect during the first or second connection due to module not responding to the request to start an RPC service. 

This is probably related to issue #1783

##### Reproduction Steps
1. Create 15+ SDL apps configured to use iAP transport.
1. Install all 15+ apps on an iPhone and connect the iPhone to the SYNC 3.0 module using USB cord.

##### Expected Behavior
All SDL apps should show up every time the app is connected and reconnected to the module.

##### Observed Behavior
Sometimes a few apps fail to show up. The logs show that the module never responded to the SDL app's request to start an RPC service. 

##### OS & Version Information
* iOS Version: 14.0
* SDL iOS Version: 7.0
* Testing Against: SYNC 3.0 (17276_DEVTEST)

**Comment by kshala-ford** [comment]
Hi @NicoleYarroch is it possible to provide test results as to what applications failed to connect? The reference to #1783 could be confirmed if certain apps consistently failed to connect and if the test is performed right after SYNC bootup. 

To me this issues sounds more like based on race conditions of app retryDelay being very close to each other. Therefore changing the boundaries to 10-15 seconds actually lowers the range increasing risk of the race condition let alone the impact to user experience to wait at least 10 seconds before apps appear.

I think we will need to discuss how to resolve the issue(s) before continuing work on a pull request.

**Comment by NicoleYarroch** [comment]
@kshala-ford I was just testing using multiple targets of a very basic test apps. I only saw the issue once I started connecting 15 or more apps. I didn't have issues with removing the retry delay (i.e. setting it to zero) or with upping the retry delay, which is stumping me. As I don't have access to the core logs I can only hypothesize as to a hack to fix the issue. Perhaps the best tack would be for someone who has access to the logs for SYNC 3.0 to figure out where the race condition is occuring?

This PR is currently a draft and hasn't been tested thoroughly. I have only tested so far with iOS 14 so I have no idea if it works with previous iOS versions.

**Comment by kshala-ford** [comment]
I request to have this issue focusing on connectivity issues with +15 applications to connect. I found that #1783 is a simple timing issue and the issue should focus on resolving that. This issue's PR should not remove the retry delay as this would be a duplicate to #1240 and it should not add a StartService retry mechanism as it breaks with the resolution effort in #1783. Please remove the reference to #1783

**Comment by kshala-ford** [comment]
As recommended in #1783, #1847 is not needed as well as this issue as removing the timeout from StartSession fixes apps not resuming as well as +15 apps not connecting. The attempt to remove the connection delay is part of #1240.

**Comment by joeljfischer** [comment]
Fixed by #1951
