### ISSUE TITLE
Unknown call appears when using audio 

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#1811]
Unknown telephone call appears when app registers

### Bug Report
HU will auto start an unknown call when any app using audio(Record and Play) service, and webex using this audio service.
Setting -> Device -> Discover Devices (This feature is for pairing TP device, it need using audio service to do) (If disable this feature, need kill the app, run app again)
When waiting to start meeting(This UI show’s microphone icon, video icon, Start button in below), audio service have started, so it will cause HU show an unknown call.

##### Reproduction Steps
Video:
https://drive.google.com/file/d/1JE2Kayto6X5MQRegAlUqFyQLjD4ujjTh/view

##### Expected Behavior
No phone call

##### Observed Behavior
Gets unknown phone call

##### OS & Version Information
* iOS Version: iOS 14
* SDL iOS Version: 
* Testing Against: SYNC 3.2v2

##### Test Case, Sample Code, and / or Example App
https://drive.google.com/file/d/1JE2Kayto6X5MQRegAlUqFyQLjD4ujjTh/view

**Comment by joeljfischer** [comment]
Hello @SatbirTanda, I'm sorry, but you haven't shown that this is an SDL issue. Can you produce a test app (the link you provided in the "Test Case, Sample Code, and / or Example App" section is a video, not any of the things listed for that section).  I was unable to follow the logic in this bug report. Can you give additional details and context to explain what you mean?

Given the scant details, the video, and the fact that SDL doesn't start phone calls, I see no reason to think that this is an SDL issue but is more likely an issue with the app and / or your head unit.
