### ISSUE TITLE
Lockscreen passenger mode bugs

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1823]
## Bug Report
There are two different bugs where the user should be able to swipe to dismiss the lockscreen because passenger mode is active but cannot.

### Reproduction Steps for Bug 1
1. LockScreenConfiguration.displayMode has been set to `always`.
2. The last received `OnDriverDistraction.lockScreenDismissalEnabled` from the module was `true`. The user did not swipe to dismiss the lockscreen.
3. The module sends a `OnDriverDistraction` notification with `state = OFF` and `lockScreenDismissalEnabled` to `null`.

##### Expected Behavior
The lockscreen is shown with the `OnDriverDistraction.lockScreenDismissalWarning` and the user can dismiss the lockscreen by swiping.

##### Observed Behavior
The lockscreen is show without the `OnDriverDistraction.lockScreenDismissalWarning` and the user can not swipe to dismiss the lockscreen.

### Reproduction Steps for Bug 2
1. LockScreenConfiguration.displayMode has been set to `always`.
2. The last received `OnDriverDistraction.lockScreenDismissalEnabled` from the module was `true`. The user did not swipe to dismiss the lockscreen.
3. The module sends a `OnDriverDistraction` notification with `state = ON` and `lockScreenDismissalEnabled` to `null`.

##### Expected Behavior
The lockscreen is shown with the `OnDriverDistraction.lockScreenDismissalWarning` and the user can dismiss the lockscreen by swiping.

##### Observed Behavior
The lockscreen is show without the `OnDriverDistraction.lockScreenDismissalWarning` and the user can not swipe to dismiss the lockscreen.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.0
* Testing Against: n/a

**Comment by joeljfischer** [comment]
This is fixed as of v7.1.0
