### ISSUE TITLE
Lockscreen shown after user dismissal

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1826]
## Bug Report
There are four bugs with the lockscreen being shown after being dismissed by the user if a policy table update changes `lockScreenDismissalEnabled` in the `OnDriverDistraction` from `true` to `false`. 

### Reproduction Steps for Bug 1
1. LockScreenConfiguration.displayMode has been set to `always`.
2. The last received `OnDriverDistraction.lockScreenDismissalEnabled` from the module was `true`. The user swiped to dismiss the lockscreen.
3. The module sends a `OnDriverDistraction` notification with `state = OFF` and `lockScreenDismissalEnabled` to `null`.

##### Expected Behavior
Lockscreen is not shown.

##### Observed Behavior
Locks screen is shown with the `OnDriverDistraction.lockScreenDismissalWarning` message. User can swipe to dismiss the lockscreen.

### Reproduction Steps for Bug 2
1. LockScreenConfiguration.displayMode has been set to `always`.
2. The last received `OnDriverDistraction.lockScreenDismissalEnabled` from the module was `true`. The user swiped to dismiss the lockscreen.
3. The module sends a `OnDriverDistraction` notification with `state = OFF` and `lockScreenDismissalEnabled` to `false`.

##### Expected Behavior
Lockscreen is shown with the `OnDriverDistraction.lockScreenDismissalWarning` message. User **cannot** swipe to dismiss the lockscreen.

##### Observed Behavior
Locks screen is shown with the `OnDriverDistraction.lockScreenDismissalWarning` message. User can swipe to dismiss the lockscreen.

### Reproduction Steps for Bug 3
1. LockScreenConfiguration.displayMode has been set to `always`.
2. The last received `OnDriverDistraction.lockScreenDismissalEnabled` from the module was `true`. The user swiped to dismiss the lockscreen.
3. The module sends a `OnDriverDistraction` notification with `state = ON` and `lockScreenDismissalEnabled` to `null`.

##### Expected Behavior
Lockscreen is not shown.

##### Observed Behavior
Locks screen is shown with the `OnDriverDistraction.lockScreenDismissalWarning` message. User can swipe to dismiss the lockscreen.

### Reproduction Steps for Bug 4
1. LockScreenConfiguration.displayMode has been set to `always`.
2. The last received `OnDriverDistraction.lockScreenDismissalEnabled` from the module was `true`. The user swiped to dismiss the lockscreen.
3. The module sends a `OnDriverDistraction` notification with `state = ON` and `lockScreenDismissalEnabled` to `true`.

##### Expected Behavior
Lockscreen is not shown.

##### Observed Behavior
Locks screen is shown with the `OnDriverDistraction.lockScreenDismissalWarning` message. User can swipe to dismiss the lockscreen.

### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.0
* Testing Against: sdl_hmi and sdl_core.

**Comment by joeljfischer** [comment]
These issues are all currently fixed
