### ISSUE TITLE
SDLSystemCapabilityManager Should Check RPC Permissions

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1849]
### Bug Report
The `SDLSystemCapabilityManager` should use the `SDLPermissionManager` to check the app has permissions to send an RPC at the current `hmiLevel` instead of assuming that all RPCs can not be sent when the `hmiLevel` is `NONE`. 

##### Reproduction Steps
1. Connect the app to a module that allows the `GetSystemCapability` request when the `hmiLevel` is `NONE`. 
2. Try to subscribe to the system capability of type `SDLSystemCapabilityTypeAppServices` when the app's `hmiLevel` is `NONE` using the `SDLSystemCapabilityManager`.

##### Expected Behavior
The `SDLSystemCapabilityManager` sends the `GetSystemCapability` request since the app has the required permissions to use `GetSystemCapability` when the `hmiLevel` is `NONE`.

##### Observed Behavior
The `SDLSystemCapabilityManager` assumes the app does not have permission to send the `GetSystemCapability` request when the `hmiLevel` is `NONE`. An error is returned.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.0
* Testing Against: n/a

**Comment by joeljfischer** [comment]
Closing as not planned. Most modules only allow very few RPCs to be sent in HMI NONE. We won't want to send `GetSystemCapability` unless the app is activated.
