### ISSUE TITLE
SDL 0323 - Align video streaming parameters with VideoStreamingCapability

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_ios#1860]
Proposal: [Align video streaming parameters with VideoStreamingCapability](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md)

> When Android SDL application starts video streaming, a developer can specify VideoStreamingParameters, but before actually starting the streaming, those parameters need to be aligned with VideoStreamingCapability returned by head units. The same is true for iOS SDL application; i.e. a developer can specify customVideoEncoderSettings, but those settings need to be aligned with VideoStreamingCapability.

Steering Committee Decision: 
The Steering Committee voted to accept the proposal on 2020-11-24. Xevo, the authoring company of the proposal shared that this proposal's [motivation](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md#motivation) was found while working on the implementation for [SDL 0274](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0274-add-preferred-FPS.md) (an already accepted proposal).
 

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1094

**Comment by shiniwat** [comment]
As I mentioned at SDL 0274 PR, because SDL 0323 implementation needs to handle preferredFPS and max bitrate in the same way, and preferredFPS requires PR for SDL 0274, I have added the SDL 0323 implementation into SDL 0274 PR with [this commit](https://github.com/smartdevicelink/sdl_ios/pull/1613/commits/a2a77b21ef90412ccfebc55c0371f8d3e7d5153f).

**Comment by NicoleYarroch** [comment]
Fixed in PR #1878
