### ISSUE TITLE
Fix SDLChoiceSet default timeout

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1891]
### Bug Report
Currently, it's possible for `SDLChoiceSet` default timeouts to be used incorrectly.

##### Reproduction Steps
1. Create a `SDLChoiceSet` without the timeout set
2. Update the default timeout of `SDLChoiceSet`

##### Expected Behavior
The choice set created before the update uses the new default choice set time

##### Observed Behavior
The choice set uses the old default choice set time.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 7.1.0-develop
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

**Comment by NicoleYarroch** [comment]
Another issue I found was that if the `timeout` is set to `0.0`, getting the `timeout` value should return the default timeout value. Instead it returns `0.0`.

**Comment by NicoleYarroch** [comment]
Fixed in #1912
