### ISSUE TITLE
[SDLIAPDataSession destroySessionWithCompletionHandler:]_block_invoke () crash issue.

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#1892]
### Bug Report
[Summary] 
When integrate with our app, it shows 93 devices crash from apple Organizer Crash Report.

##### Reproduction Steps
Not sure about how to reproduce it.

##### Expected Behavior
No crash.

##### Observed Behavior
Show crash report.

##### OS & Version Information
* iOS Version: 13.7-14.2
* SDL iOS Version: v7.0.0

##### Test Case, Sample Code, and / or Example App
#5	(null) in __57-[SDLIAPDataSession destroySessionWithCompletionHandler:]_block_invoke ()
![Screen Shot 2021-01-18 at 3 27 59 PM](https://user-images.githubusercontent.com/3917323/104884737-d13d6300-59a1-11eb-8ee6-b3e580cbb56a.png)

**Comment by NicoleYarroch** [comment]
@84798012 Have you been able to reproduce this while testing? This crash log does not provide much information to reproduce so it would be difficult for us to find the bug or figure out if we fixed the issue.

Could you provide some more information to help us with our debugging:
1. Does this happen on certain models of iPhones or all models?
1. If you are able to reproduce, when does the crash occur (i.e. when the SDL app is connected, when a disconnection is made, when the app on the phone is backgrounded, etc.)?
1. If you are able to reproduce, does this happen over a Bluetooth or USB connection?
1. Can you provide a crash log?

**Comment by 84798012** [comment]
> @84798012 Have you been able to reproduce this while testing? This crash log does not provide much information to reproduce so it would be difficult for us to find the bug or figure out if we fixed the issue.
> 
> Could you provide some more information to help us with our debugging:
> 
> 1. Does this happen on certain models of iPhones or all models?
> 2. If you are able to reproduce, when does the crash occur (i.e. when the SDL app is connected, when a disconnection is made, when the app on the phone is backgrounded, etc.)?
> 3. If you are able to reproduce, does this happen over a Bluetooth or USB connection?
> 4. Can you provide a crash log?

1. this happen on all models iPhones and version.
2. I don't know how to reproduce it, I received these reports from apple's crash report. And the crash counts increased more.
4. Attached one log, please check it. 
[SDLCrashIssue.txt](https://github.com/smartdevicelink/sdl_ios/files/5902656/SDLCrashIssue.txt)
![Screen Shot 2021-02-01 at 4 06 10 PM](https://user-images.githubusercontent.com/3917323/106431749-b0e4cc80-64a8-11eb-9640-e47d3ee2edce.png)

**Comment by jordynmackool** [comment]
Pull request #1910 notes it should resolve this issue.

**Comment by theresalech** [comment]
Reopening based on #2008. @84798012, please provide more details, logs, and/or reproduction steps for your experience with this issue on iOS 7.1.1.

**Comment by theresalech** [comment]
@84798012, can you please retest using iOS 7.2 and advise if you are still experiencing the issue? Thank you!

**Comment by theresalech** [comment]
Closing as inactive. Reporter can advise if issue is still present in iOS 7.2, and we can reopen if needed.

**Comment by 84798012** [comment]
Hi, theesalech. This issue is reported by Apple's crash report from our product, not from myself. I'm sorry that I not sure what happens on our customers. Here I attached is all what I got. And it seems that your team have fixed this issue before, but in new version SDL, this issue not be fixed.
So we still need your help to check the root cause of this issue. This crash issue have become the mostly crash module in our app. If you close this issue, we can not fix the issue from myside and I can not explain it.

**Comment by theresalech** [comment]
Hi @84798012 , can you please confirm that you have updated your app to use SDL iOS 7.2.0? 

If you are still getting the crash report when using SDL iOS 7.2.0, we will need more details in order to work on finding the root cause. Please provide recent crash logs from the crash when using version 7.2.0, and any other details of the issue. You should be able to leave an additional comment on this closed issue with that information. We can then re-open the issue to investigate further. Thank you!

**Comment by 84798012** [comment]
Sorry theesalech, I can not use SDL 7.2.0 now. Because we have informed this issue been fixed in 7.1.0, and we have upgrade to 7.1.0. It caused more crash reports from apple, so we had to rollback to 7.0.0. I'm afraid that if upgrade to 7.2.0, this issue still not been fix. Our manager can not accept so many crash in our app, so please double confirm if this issue really been fixed. And are you sure you have make new fix in 7.2.0 ?

**Comment by cmckee16** [comment]
Attaching logs as requested
[crash-v7.2.zip](https://github.com/smartdevicelink/sdl_ios/files/7040037/crash-v7.2.zip)

**Comment by cmckee16** [comment]
This issue has been resolved.  Previous comment with logs attached were pertaining to a different issue and should be disregarded.
