### ISSUE TITLE
observerMock is deprecated

### ISSUE THREAD

**Issue by FrankElias77** [smartdevicelink/sdl_ios#1913]
### Bug Report
`'observerMock' is deprecated: Please use XCTNSNotificationExpectation instead.`
Looks like this was deprecated recently in OCMock v. 3.8 (https://ocmock.org/reference/)

##### Reproduction Steps
N/A

##### Expected Behavior
N/A

##### Observed Behavior
N/A

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: 7.0
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App
N/A

**Comment by NicoleYarroch** [comment]
Fixed in PR #1914
