### ISSUE TITLE
GPS subscription stops updating when moving in reverse

### ISSUE THREAD

**Issue by kylewludwig** [smartdevicelink/sdl_ios#1918]
### Bug Report
Vehicle GPS updates stop occurring when the vehicle moves in reverse. I have tested and observed this behavior in multiple vehicles from model years 2018-20.

##### Reproduction Steps
1. Setup a subscription to speed, PRNDL, and GPS to contrast the data dropout occurring when moving in reverse (seen in GPS.) Use a `.default` HMI type to run in the background (no SmartDeviceLink display is shown.)
2. Run an app from Xcode using the wireless debugger via a network connection.
3. Connect the phone via lightning USB to the vehicle.
4. Start the vehicle and await the connection and vehicle data subscription success response.
5. Put the vehicle in reverse, holding the brake. (You should observe GPS and PRNDL events now.)
6. Release the brake and move the vehicle in reverse. (You should now observe the issue; speed updates occur but GPS does not when moving in reverse.)
7. To contrast behaviors, put the vehicle in drive and move forward. (You should now observe GPS and speed resume while moving in drive.)

##### Expected Behavior
GPS subscription should continue to update when the vehicle is moving in reverse.

##### Observed Behavior
GPS subscription stops updating when the vehicle moves in reverse. When in reverse with the brake held, it works as expected.

##### OS & Version Information
* iOS Version: 13.0
* SDL iOS Version: 7.0.0
* Testing Against: n/a

**Comment by joeljfischer** [comment]
@kylewludwig Have you tested this with the Java Suite or JavaScript Suite libraries? This sounds like a module bug to me from first glance.

**Comment by kylewludwig** [comment]
I haven't tried Java or Javascript libraries. I've had someone look at the AppLink logs and it didn't show any issue but the log was very large.

**Comment by joeljfischer** [comment]
There is no logic in the library to deal with blocking subscriptions in any given situation. It simply passes along any values it receives. My strong suspicion is that this is a module issue. If you can, please test with the Java Suite (Android) library and let us know if the issue appears there as well. If it does, it's almost certainly a module issue. If not, we can do some deeper digging and go from there.

**Comment by kylewludwig** [comment]
Okay, I'll confirm the issue first with other libraries and report back.

**Comment by joeljfischer** [comment]
Hi @kylewludwig, I'm going to close this issue, please let us know if your results point to it still being an iOS issue!

**Comment by kylewludwig** [comment]
@joeljfischer It appears to be a module issue. The issue also occurred on Android.

**Comment by joeljfischer** [comment]
Thanks for doing the extra investigation to confirm that. I'll leave this issue closed.
