### ISSUE TITLE
SDLRPCRequestFactory always sends registerAppInterface with SyncMsgVersion 1.0

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#192]
It is currently hardcoded, if we are going to use this for RPC version, we will need to understand why it is hardcoded this way and the implications of altering it.

**Comment by joeljfischer** [comment]
@joeygrover thinks it's a situation where the request is always sent with 1.0, and the response gives the highest version it can use.

If that's the case, then how is that version negotiated after that point?

@adein @hugh22 @mrapitis @stefanek22 any idea?

**Comment by justinjdickow** [comment]
I also believe that legacy versions are always expecting 1.0 as the value. There isn't really any version negotiation for RPC version, the proxy is expected to be backward compatible and use the message version in the response. We could test this with all the TDKs and verify.

This also brings up another possible task. We should try to identify all of the officially released RPC specs that that need to be supported.

**Comment by joeljfischer** [comment]
So then what about forward compatibility? That is, if the radio sends a response with a version that the proxy doesn't support?
