### ISSUE TITLE
Fix Spelling of auxillary in SDLStaticIconName

### ISSUE THREAD

**Issue by FrankElias77** [smartdevicelink/sdl_ios#1938]
### Bug Report
The spelling of "auxillary" needs to be fixed in five places (including an actual type name) in the SDLStaticIconName.h file. 

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: N/A
* Testing Against: N/A

**Comment by NicoleYarroch** [comment]
Fixed in PR #1939
