### ISSUE TITLE
Need to confirm that proxy responds appropriately to a message coming over the hybrid service

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#194]
An [issue](https://github.com/smartdevicelink/sdl_core/issues/110) was raised that the service type for all messages coming from sdl core default to the RPC service and were never changed, even if the rpc message contained binary data.

A [pull request](https://github.com/smartdevicelink/sdl_core/pull/111) fixes this issue but validation of the proxy still needs to occur before it is merged.

**Comment by justinjdickow** [comment]
If we "at some point" update the libraries to differentiate packets based on Service Type (RPC vs. Hybrid) we will have a legacy issue that requires us to check version and accept all packets for version <= x because they'll all send RPC type even if they contain binary data.

**Comment by justinjdickow** [comment]
The other option is that we update the protocol_spec to remove the idea of the hybrid service because it's basically an abstract concept.

**Comment by joeljfischer** [comment]
@justinjdickow is this resolved?

**Comment by justinjdickow** [comment]
The pull request for core was merged and we confirmed on Android. I don't believe anyone has confirmed this is okay on iOS. I will get it tested today

**Comment by joeljfischer** [comment]
Fixed in #360
