### ISSUE TITLE
Lock Screen not dismissible

### ISSUE THREAD

**Issue by FrankElias77** [smartdevicelink/sdl_ios#1948]
### Bug Report
The lock screen should be dismissible in case DriverDistraction mode was `OFF`, `enableDismissGesture` was set to true and the lock screen's display mode is `always`.

##### Reproduction Steps
1. Set lockscreen config display mode to `always`
2. The default lock screen should appear correctly when the app is connected to Core with `DD_OFF`
3. Turn`DD_ON`
4. Turn `DD_OFF` again
5. Swipe to dismiss lock screen

##### Expected Behavior
Lock screen should be dismissable

##### Observed Behavior
Lock screen is not dismissable

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: Branch develop
* Testing Against: Manticore

**Comment by NicoleYarroch** [comment]
Fixed in PR #1949
