### ISSUE TITLE
SDL Test App does not connect to Gen 3 TDK

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#195]
On the develop branch (working toward the 4.0 release), the test app does not appear to be connecting to the Gen 3 TDK.

@adein Can you check the IAP implementation on the current develop branch? Altering the app Id and app name do not appear to make a difference. Any tips or help you could offer would be appreciated.

**Comment by adein** [comment]
@joeljfischer Is the source for the tester app you're using on Github?  Can I test using HelloSDL with the latest proxy source from the develop branch?

**Comment by justinjdickow** [comment]
@tomhoag @joeljfischer 

If you haven't done so already, in your app capabilities add External accessory communication as a supported background mode, then in your app's property list add the `UISupportedExternalAccessoryProtocols` ("Supported external accessory protocols" if you're not viewing raw values in your plist) array and add the following strings to the array:

```
com.ford.sync.prot0
com.smartdevicelink.prot0
com.smartdevicelink.prot1
com.smartdevicelink.prot2
com.smartdevicelink.prot3
com.smartdevicelink.prot4
com.smartdevicelink.prot5
com.smartdevicelink.prot6
com.smartdevicelink.prot7
com.smartdevicelink.prot8
com.smartdevicelink.prot9
com.smartdevicelink.prot10
com.smartdevicelink.prot11
com.smartdevicelink.prot12
com.smartdevicelink.prot13
com.smartdevicelink.prot14
com.smartdevicelink.prot15
com.smartdevicelink.prot16
com.smartdevicelink.prot17
com.smartdevicelink.prot18
com.smartdevicelink.prot19
com.smartdevicelink.prot20
com.smartdevicelink.prot21
com.smartdevicelink.prot22
com.smartdevicelink.prot23
com.smartdevicelink.prot24
com.smartdevicelink.prot25
com.smartdevicelink.prot26
com.smartdevicelink.prot27
com.smartdevicelink.prot28
com.smartdevicelink.prot29
```

**Comment by i-schuetz** [comment]
Super sorry to hijack this thread, but could I ask where do you get the protocol names from? Does the vendor have to register with the IMF to get them? Or is there another way?

**Comment by tpulatha** [comment]
please join the slack at slack.smartdevicelink.com for questions like that.
