### ISSUE TITLE
"CC_MD" Message Digest Generated Using Broken Cryptography API

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#1952]
The vulnerable code locations use the CC_MD hashing functions, which leverage hashing algorithms (including MD2 and MD5) that are proven to be vulnerable to collision attacks, and are unsuitable for modern use.

Apple has officially deprecated these APIs in the iOS 13.0 SDK. They state in the CommonCrypto headers:

"These functions are cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger)."

-[SDLArtwork sdl_md5HashFromNSData:] calls _CC_MD5()
-[SDLIAPTransport sdl_retryDelay] calls _CC_MD5()

And all others file those using CC_MD.

**Comment by joeljfischer** [comment]
Closing as duplicate of https://github.com/smartdevicelink/sdl_ios/issues/1673. We are not using MD5 hashing in any security context and fixing it would require a large amount of work for no gain. We have chosen not to consider this a bug, and it will not be fixed. If you have additional comments or concerns, please let us know!
