### ISSUE TITLE
Example app's menu not displayed correctly after app exit

### ISSUE THREAD

**Issue by FrankElias77** [smartdevicelink/sdl_ios#1967]
### Bug Report
When the user selects the "Exit <App Name>" from the menu on SYNC 3, the `hmiLevel` goes back to none. When the user re-opens the app, the menu is not sent because the SDL app did not set `firstHMILevelState` back to `.none` when notified via the `SDLManagerDelegate` that the `hmiLevel` changed back to none.

##### Reproduction Steps
1. Press "Exit <App Name>" from menu on SYNC 3
2. Enter the app again
3. Press the menu button

##### Expected Behavior
Menu gets populated after entering the app again(Step 2)

##### Observed Behavior
Menu doesn't shoq

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: Branch develop
* Testing Against: SYNC 3

**Comment by NicoleYarroch** [comment]
Fixed in PR #1968
