### ISSUE TITLE
File manager returns that files are not uploaded if the connection is > v4.4.0

### ISSUE THREAD

**Issue by FrankElias77** [smartdevicelink/sdl_ios#1978]
### Bug Report
Currently we send the initial text & images when the `hmiLevel` goes to `FULL` the first time. However, sometimes the image is not sent due to the file manager not yet being in the ready state. We should try to send the image again if the image upload failed due to this reason.

##### Reproduction Steps
1. Run iOS example app
2. Launch it on desired hmi

##### Expected Behavior
Images displayed correctly

##### Observed Behavior
Images not displayed

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: 7.1
* Testing Against: Manticore

**Comment by joeljfischer** [comment]
This bug doesn't look correct. The lifecycle manager should not be sending the HMI level change until after the file manager and all other managers are ready. If that's not happening, I think that's a manager bug not an example app bug.
