### ISSUE TITLE
Back-to-Back Choice Sets Can Fail

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#2018]
### Bug Report
I'm seeing a bug in the choice set manager where back-to-back choice sets can fail. Because the `SDLPresentChoiceSetOperation` uses the standard `completionBlock`, which runs after the operation completes and the next one starts, if two present operations are next to each other, the second should run, but I've seen cases where that does not happen. This is because the `completionBlock` clears the `pendingPresentationSet`, which may no longer be the running presentation set.

Instead, we should do as we do in the alert manager and add pending presentations to the queue and cancel previous non-executing ones if a new one is added.

##### Reproduction Steps
1. Create a choice set
2. Before an option is pressed, present a new choice set

##### Expected Behavior
The second choice set appears

##### Observed Behavior
The second choice set fails to appear because the choice set is `nil` in the `PresentChoiceSetOperation`. This is because it's set to `nil` in `sdl_presentChoiceSetWithMode` in the `completionBlock`.

##### OS & Version Information
* iOS Version: iOS 14.6
* SDL iOS Version: v7.2.0
* Testing Against: Manticore and Sync 3.4

##### Test Case, Sample Code, and / or Example App
n/a

**Comment by theresalech** [comment]
Corresponding Java Suite issue: https://github.com/smartdevicelink/sdl_java_suite/issues/1717.
