### ISSUE TITLE
Choice Set Present followed directly by a Delete can have undefined behavior

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#2020]
### Bug Report
In certain cases, a present can happen when the choices are not available on the head unit. The present operation should double-check when it starts that all cells are preloaded on the head unit. When a present the operation should be created along with the preload, and updated when the preload finishes. That way the delete will be slotted after the present.

##### Reproduction Steps
1. Send a present with a large number of choices
2. Immediately send a delete for several of those choices

##### Expected Behavior
The delete happens after the present

##### Observed Behavior
Undefined error behavior

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: v7.3.0-develop
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
See SDLChoiceSetManagerSpec L432 commented out test

**Comment by theresalech** [comment]
Corresponding app library issues:
- Java Suite: https://github.com/smartdevicelink/sdl_java_suite/issues/1718
- JavaScript Suite: https://github.com/smartdevicelink/sdl_javascript_suite/issues/474
