### ISSUE TITLE
Security queries are not implemented to spec

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_ios#2024]
### Bug Report
With the acceptance of [SDL 0317](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0317-sdl-protocol-security-specification.md), this library's implementation of security queries does not match the spec fully. Several issues exist with the current implementation such as:

1. When a security query is received from Core, its header is entirely ignored and the library assumes that it is a `Send Handshake Data` request. This causes issues if Core were to send another type of query, such as a `Send Internal Error` notification.

```objc
    // Tear off the binary header of the client protocol message to get at the actual TLS handshake
    // TODO: (Joel F.)[2016-02-15] Should check for errors
    NSData *clientHandshakeData = [clientHandshakeMessage.payload subdataWithRange:NSMakeRange(12, (clientHandshakeMessage.payload.length - 12))];
```

2. Hardcoded values are used when sending security queries for fields such as query type and query ID. Any predefined values should be properly added as constants.

```objc
    serverTLSPayload.functionID = 0x01; // TLS Handshake message
    serverTLSPayload.rpcType = 0x00;
    serverTLSPayload.correlationID = 0x00;
```

should be changed to something like

```objc
    serverTLSPayload.queryID = SDLQueryIDSendHandshakeData;
    serverTLSPayload.queryType = SDLQueryTypeResponse;
    serverTLSPayload.sequenceNumber = requestHeader.sequenceNumber;
```

3. Security queries are constructed using an RPC header, which has a slightly different format than a security query header. Security query headers should be implemented separate from RPC headers.

```objc
    // For a control service packet, we need a binary header with a function ID corresponding to what type of packet we're sending.
    SDLRPCPayload *serverTLSPayload = [[SDLRPCPayload alloc] init];
    ...
    NSData *binaryData = serverTLSPayload.data;

    return [SDLProtocolMessage messageWithHeader:serverMessageHeader andPayload:binaryData];
```

should be changed to something like

```objc
    // For a control service packet, we need a binary header with a function ID corresponding to what type of packet we're sending.
    SDLQueryPayload *serverTLSPayload = [[SDLQueryPayload alloc] init];
    ...
    NSData *binaryData = serverTLSPayload.data;

    return [SDLProtocolMessage messageWithHeader:serverMessageHeader andPayload:binaryData];
```

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: master
* Testing Against: N/A

**Comment by theresalech** [comment]
See Core issue https://github.com/smartdevicelink/sdl_core/issues/3755; the mobile libraries will need to account for this by accepting both the NOTIFICATION and REQUEST types for SendHandshakeData and just treating them as REQUEST type.
