### ISSUE TITLE
[develop] Pull SendLocation out or revise based on discussion

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#203]

**Comment by joeljfischer** [comment]
@stefanek22 @Heath-FoMoCo Have we made a decision on SendLocation at this point? Specifically, whether addresses are simply going to be cosmetic under "address lines" or if they will be split into "address" "state" "zip" etc.?

**Comment by stefanek22** [comment]
@tpulatha  We only addressed a short-term solution with the currently defined API, correct?  We have not landed on a formal replacement for the address data structure, yet, correct?

**Comment by tpulatha** [comment]
@stefanek22 @Heath-FoMoCo @joeljfischer We have both solutions spec'd out. SDL will accept an address with the following fields:
* longitudeDegrees
* latitudeDegrees
* locationName

These are sufficient to display a POI with a name and a precise location. 
We already spec'd out a future expansion that will include a struct with a more precise location information in the following format: 

* Street
* HouseNumber 
* City 
* PostalCode 
* State  
* Country

This will be in a future release.
