### ISSUE TITLE
sdl_notifyObserversOfCapabilityType:capability:error Crash

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#2036]
### Bug Report
We got many crash from apple's crash report.

##### Reproduction Steps
I'm not sure how to reproduce it, because its only from apple's report, and I don't know user how to make the crash.

##### Expected Behavior
No crash.

##### Observed Behavior
Crashed.

##### OS & Version Information
* iOS Version: 14.7.1
* SDL iOS Version: 7.2
* Testing Against: 

##### Test Case, Sample Code, and / or Example App
[Issue3.log](https://github.com/smartdevicelink/sdl_ios/files/7158452/Issue3.log)

**Comment by joeljfischer** [comment]
@84798012 We believe the merged PR will fix this issue. If you want to test and give us feedback here, we will take it into account. This will be released in v7.3.0 on October 27, 2021.
