### ISSUE TITLE
End Service ACK 0x05 and End Service NACK 0x06 are missing from SDLFrameData enum and not used

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#204]
I think the proxy doesn't check whether services are ended properly before disconnecting transports which might be fine, but for stopping h.264 and pcm data streaming, these will likely need to be implemented.

**Comment by joeljfischer** [comment]
So you mean that its not checking on the receiving end? As in, if the proxy sends an `endService` it doesn't actually check and see if it did? What currently happens, it doesn't appear to even disconnect the transport? Maybe that's something that's done Core side?

**Comment by justinjdickow** [comment]
When the proxy sends an End Service it will receive either an End Service ACK or NACK from SDL Core.  The iOS proxy doesn't capture either of those packets and do anything with them as far as I can tell, and it doesn't define those Frame Types in the [SDLFrameData enum](https://github.com/smartdevicelink/sdl_ios/blob/develop/SmartDeviceLink-iOS/SmartDeviceLink/SDLProtocolHeader.h#L19-L28). Not doing anything with the end sessions and disconnecting the transport is fine for the RPC service, but for Video and Audio streaming, when the app might remain connected after ending the services, it will probably want to know whether the end services were successful.

**Comment by joeljfischer** [comment]
@justinjdickow what milestone is this?
