### ISSUE TITLE
Fix `userDidSubmitInput` getting called multiple times after a search request is submitted

### ISSUE THREAD

**Issue by FrankElias77** [smartdevicelink/sdl_ios#2064]
### Bug Report
When the user submit a search request through a `searchableChoiceSet`, the `userDidSubmitInput` keyboard's delegate method gets called multiple times in case the `updateAutocomplete` method is implemented

##### Reproduction Steps
1. Present a searchable choice set
2. Submit a search through the search box in choice set or click on an autocomplete cell

##### Expected Behavior
`userDidSubmitInput` method gets called once with source `.submitted`

##### Observed Behavior
`userDidSubmitInput` method gets called multiple times with source `.submitted`

##### OS & Version Information
* iOS Version: 15.0
* SDL iOS Version: 7.3.0
* Testing Against: SYNC 3.0

**Comment by theresalech** [comment]
Closed via #2065
