### ISSUE TITLE
SDLSetDisplayLayout sometimes will got error, then can not show UI in TDK.

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#2069]
### Bug Report
SDLSetDisplayLayout sometimes will got error, then can not continue to show UI in TDK.
We received following error:
showPage, set display mode failed: GENERIC_ERROR:Invalid message received from vehicle

##### Reproduction Steps
1. For some time not connected to TDK or first time connected to TDK.
2. We always got error, then can not show normal UI in TDK.

##### Expected Behavior
No error post.

##### OS & Version Information
* iOS Version: [Any version]
* SDL iOS Version: [Sync3, Sync4]
* Testing Against: [Some time not connected TDK or first time connect TDK]

##### Test Case, Sample Code, and / or Example App

```
SDLSetDisplayLayout* display = [[SDLSetDisplayLayout alloc]initWithPredefinedLayout:SDLPredefinedLayoutTilesWithGraphic];
[self.SDLManager sendRequest:display withResponseHandler:^(SDLRPCRequest *request, SDLRPCResponse *response, NSError *error) 
{
    if ([response.resultCode isEqualToEnum:SDLResultSuccess]) 
    {
        [weakSelf _show:mode];
    }
    else 
    {
        NSLog(@"showPage, set display mode failed: %@:%@", response.resultCode, response.info);
    }
}];
```

**Comment by joeljfischer** [comment]
Hello @84798012, 

1. What do you mean by "cannot show normal UI"? This is a common pattern in apps, including our own (even the example apps that come with this repository), and we have not seen this error on TDKs. 
2. Can you please: (1) modify an existing example app to show this issue, (2) give more information about the version(s) of TDKs that you're using? There should be an about page on the TDK that shows additional version details. 
3. We also need to know the version of sdl_ios that you are using.

**Comment by 84798012** [comment]
@joeljfischer  Thanks for you feedback.
Sorry for missing attached the error, I've update the bug.
Here is the error we got : 
showPage, set display mode failed: GENERIC_ERROR:Invalid message received from vehicle

1. I means we must do "SDLManager sendRequest:display withResponseHandler" success, then can continue to show our app's UI. And this issue hard to reproduce, it may happens when 1st time connecting TDK, or for a long time not connect TDK then connect TDK. Once this issue happened, the app in Applink will not work and can not recover, only can restart TDK.
2. TDK version: Sync3, Building 17110_devtest, Sync4, Version: 21296_devtest Revision: 116. Both had ever happend.
3. We're using sdl_ios 7.2.0. But this issue existed long time ago, even at the begining when we integrated with SDL, may be since 2018 years.

**Comment by joeljfischer** [comment]
This also sounds like it's probably a TDK issue. I would contact Ford about it. You may also be overloading the system with requests, TDKs can sometimes stop responding for a while when that's the case. I suspect this is not an sdl_ios issue.
