### ISSUE TITLE
Support old devices with SDL Core 2.0 when using USB cable

### ISSUE THREAD

**Issue by peterkomar** [smartdevicelink/sdl_ios#2087]
### Bug Summary

The old Ford SYNC 1 with SDL core 2.0.0 does not show my application name in the list of apps on the head unit on a USB connection.

### Reproduction Steps

1. Connect the phone to the head unit via USB cable
2. Launch the app on the phone
3. Go to SYNC Applications -> Mobile Apps  Click  on 'Find apps'

Expected Behavior:
application name listed in the `SYNC Applications -> Mobile Apps`

Observed Behavior:

application name is not in the `SYNC Applications -> Mobile Apps`

### iOS Version(s)

15.4.1

### sdl_ios Version

7.3.0

### Testing Environment(s)

```markdown
Ford Head Unit SYNC 1.1 with SDL Core 2.1.0
```

**Comment by joeljfischer** [comment]
Hello @peterkomar, thank you for the report. It would be very helpful if you are able to turn on `debug` or `verbose` logging with your app, then connect to the head unit and provide us with the relevant logs.

**Comment by peterkomar** [comment]
Hi @joeljfischer,  I will update the issue with logs later today

**Comment by peterkomar** [comment]
I was checked the logs and found what was the reason. It was problem in my code. Sorry for disturbing.
