### ISSUE TITLE
Is there a way know I'm runing sync3 or sync4?

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#2088]
### Description
Because sync3 and sync4 have different behavior, so I need to do different thing.
I'm trying to use SDLMsgVersion to get the sync3 or sync4, but I can only get like this: 4.2.0 ; 5.0.0 from TDK, it seems not match sync3 or sync4. So I want to know is there any API to check this? 
Thanks very much!

**Comment by joeljfischer** [comment]
Look at the `SDLManagerDelegate` callback `- (BOOL)didReceiveSystemInfo:(SDLSystemInfo *)systemInfo`. I'm not sure if Ford will give you that information in those parameters or not. You may be able to infer from both the `make = Ford` and the `SDLMsgVersion`.

**Comment by 84798012** [comment]
Thanks for you feedback!
I make a test, systemInfo also included in following notification, but it can not recognize sync3 or sync4, I will connect with Ford to check this issue.

(void)didReceiveRegisterAppInterfaceResponse:(SDLRPCResponseNotification *)notification
		sdlVersion = a56f1cb2;
		syncMsgVersion = "5.0.0";
		systemSoftwareVersion = "21296_DEVTEST";
		vehicleType = "{\n    make = Ford;\n}";
