### ISSUE TITLE
Connecting the phone to SYNC before launching the app results in the app not attempting to connect

### ISSUE THREAD

**Issue by adein** [smartdevicelink/sdl_ios#211]
It seems that the proxy doesn't check for EA connections when the proxy is instantiated; it only checks when a connection event occurs.  This results in apps not connecting if the app is launched after the device is connected to SYNC.

**Comment by joeljfischer** [comment]
Within `[SDLProxy initWithTransport:protocol:delegate:]` there is:

```objc
[self.transport performSelector:@selector(connect) withObject:nil afterDelay:0];
```

Is this not working for some reason?

**Comment by adein** [comment]
Apparently not.  I'm not sure why.  I've tried it several times, and all I see is the InitWithTransport..., then nothing until I unplug/replug the cable.

**Comment by adein** [comment]
I replaced the code you quoted with this, and it fixed it:

    [self.transport connect];

It seems like it might be an issue with performselector queuing the call in the run loop (not sure which run loop), and then not ever actually running it.  See [this StackOverflow post.](https://stackoverflow.com/questions/7219131/performselector-not-working)

**Comment by joeljfischer** [comment]
I was actually going to question why it was being done after a delay. If it does need to be done after a delay (for instance, to avoid the transport calling back to the proxy before it's finished constructing), I would recommend either:

1. A 'start' method in the proxy that's required to be called after the `init` finishes.
2. Using `dispatch_after` with a delay more like 0.5 seconds.

**Comment by adein** [comment]
I don't think there needs to be a delay at all, everything should be setup before it gets called.  I changed it to a simple method call and it worked (at least the first time I tried it).

**Comment by joeljfischer** [comment]
Yeah, there is an edge-case where the transport, now that it has been commanded to start, could try to callback to a not-yet-constructed proxy that's still waiting to finish it's init method. There's a low chance, but the flow does allow for it.

**Comment by Heath-FoMoCo** [comment]
Couple things on this issue.  It sounds like, @joeljfischer, you have a fix in mind.  Can we get this implemented and available to test?
Second, I believe this should be offered as a hot fix as we are waiting on this go to forward with app development on our current version.

**Comment by joeljfischer** [comment]
@adein I've had some time to consider, and I've come around to think a simple change to call `connect` will be okay and solid. We're calling it after all the ivars & properties have been set up, so it's internal state should be set. I'll submit a PR referencing this issue. It will also cover setting up properties using direct ivar access, as [recommended by Apple](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmPractical.html)

**Comment by adein** [comment]
@joeljfischer Ok, great.  Is it possible to make this a hotfix like Heath asked instead of targeting the 4.0 milestone?

**Comment by joeljfischer** [comment]
@adein Well we're waiting on confirmation on #212 anyway. The additional things I have in this fix also change some public APIs (11th hour I know) for safety reasons, basically just making the proxy listeners array into a set, so that developers can't accidentally add a listener twice and get double callbacks, making it readonly, so they can't accidentally set a new value in there, and making it immutable, so they don't have two options for adding a proxy listener, one good and one 'bad'. It also adds a way for developers to remove a listener they no longer need.

It's pretty minor stuff, really, but it would have to get in before 4.0 or wait for 5.0.
