### ISSUE TITLE
Proxy lifecycle methods sometimes run in the 'wrong order' resulting in the app not being able to reconnect

### ISSUE THREAD

**Issue by adein** [smartdevicelink/sdl_ios#212]
After an app has connected and registered with SYNC, unplugging and reconnecting the phone to SYNC sometimes results in the cleanup methods (dealloc, etc) being executed after the Init method(s).  When this occurs, the proxy will not connect to SYNC when the phone is reconnected.

Sample log output:

05/28/15 14:08:53.042: [1] Accessory Disconnected Event
05/28/15 14:08:53.047: [1] IAP Disconnecting
05/28/15 14:08:53.051: [1] Output Stream Closed
05/28/15 14:08:53.055: [1] Input Stream Closed
05/28/15 14:08:53.060: [1] SDLIAPSession Dealloc
05/28/15 14:08:53.065: [6] onProxyClosed
05/28/15 14:08:53.071: [5] Stop Proxy
05/28/15 14:08:53.072: [7] Start Proxy
05/28/15 14:08:53.076: [7] SDLIAPTransport Listening For Events
05/28/15 14:08:53.077: [7] SDLIAPTransport Init
05/28/15 14:08:53.079: [7] SDLProxy initWithTransport
05/28/15 14:08:53.081: [7] SDLIAPTransport Stopped Listening For Events
05/28/15 14:08:53.082: [7] SDLProtocol Dealloc
05/28/15 14:08:53.083: [7] SDLProxy Dealloc
05/28/15 14:08:53.085: [5] IAP Disconnecting
05/28/15 14:08:53.093: [5] SDLIAPTransport Stopped Listening For Events
05/28/15 14:08:53.100: [5] SDLProtocol Dealloc
05/28/15 14:08:53.112: [5] SDLProxy Dealloc
05/28/15 14:09:00.089: [7] SDLIAPTransport Dealloc
05/28/15 14:09:00.090: [2] SDLIAPTransport Dealloc

**Comment by stefanek22** [comment]
How often are we witnessing this bug?  Or rather, what is the reproducibility rate?  This could explain known connection issues...

**Comment by adein** [comment]
I haven't measured it, but it seems to be quite often.  Maybe 30-50%, at least with the app I've been testing/working on.

**Comment by adein** [comment]
Looking at this class (the 'initWithTransport' and 'destructObjects' methods in particular):
[SDLProxy.m](https://github.com/smartdevicelink/sdl_ios/blob/d8a8310745f471f40d0ff5c1e56e7ec648b9fdf0/sdl_ios/SmartDeviceLink/SDLProxy.m)

Along with the description of [unregisterForLocalNotifications / registerForLocalNotifications](https://developer.apple.com/library/prerelease/ios/documentation/ExternalAccessory/Reference/EAAccessoryManager_class/index.html#//apple_ref/occ/instm/EAAccessoryManager/unregisterForLocalNotifications)

I'm wondering if the problem is related to those method calls occurring the wrong order (since the order of adding/removing the EAAccessoryDidConnectNotification/EAAccessoryDidDisconnectNotification event observers shouldn't really matter)?

Is it possible to use a serial dispatch queue for the calls to 'initWithTransport' and 'destructObjects' to insure they run in the correct order?

**Comment by joeljfischer** [comment]
All of those methods should be running on the main thread, which is a serial queue. Why is the proxy being dealloc'd at all? Should the proxy not still be sticking around and it's transport waiting for a new connection? This seems to be a very strange series of events for an accessory disconnection.

**Comment by adein** [comment]
The current/pre-existing architecture for the proxy is to remove references to the whole thing and create a new one whenever a disconnect occurs.

This was probably because everything was all interlinked, and in the past, was all in one or two classes.  Also, it was probably just more convenient instead of having to reset the state of the proxy.  Now that things are a little more separated this could be changed.  Probably the best time would be when ALM gets added to the iOS proxy.

But for now, this is the normal lifecycle (destroy and re-create the proxy).

**Comment by joeljfischer** [comment]
Is the developer responsible for knowing and implementing that?

**Comment by adein** [comment]
Yes.  The sample code and developer guides tell them to create a new proxy when they receive an onProxyClosed callback.

**Comment by joeljfischer** [comment]
Yeah, sorry, I'm looking at that now. 

Is the old proxy and the new proxy being destroyed / constructed (respectively) on different queues? You can log the current queue using `dispatch_get_current_queue` and then `dispatch_queue_get_label`.

If the numbers in brackets are the thread index, then we have some bad threading going on here.

**Comment by joeljfischer** [comment]
@adein If you want to test what those thread indexes actually support, then create a method:

```objc
- (NSString *)queueLabel {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    dispatch_queue_t currentQueue = dispatch_get_current_queue();
#pragma clang diagnostic pop
    
    return [NSString stringWithCString:dispatch_queue_get_label(currentQueue) encoding:NSUTF8StringEncoding];
}
```

and in `+[SDLDebugTool logInfo:withType:toOutput:toGroup:]` change the first line (on the release/4.0.0 branch) to call that method and log it instead of the thread index. 

Do you have a list of repro steps that you could put into the top comment?

**Comment by adein** [comment]
Looking at my code, it looks like the 'stopProxy' method was being dispatched, resulting in the cleanup code frequently running *after* the initWithTransport method of the new proxy.  I've changed this and will test to see if the issue goes away.

Regardless, this seems like something the proxy should be able to prevent (like you said earlier) if the architecture is changed such that the entire proxy object isn't destroyed and re-created on each disconnect.  This would be a dev facing change, so it would have to be in a future release (if we want to do it).
