### ISSUE TITLE
Refactor and remove [dispose] and [destructObjects] methods

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#216]
Everything should be pretty much possible within dealloc. Many of the actions taking place in these methods are unnecessary / remnants of pre-ARC code. This can also remove `_alreadyDestructed` ivars. This should free up some unnecessary complexity as well.

This may be required for #73 to be done correctly

**Comment by asm09fsu** [comment]
This has been merged into develop
