### ISSUE TITLE
Refactor PutFile streaming to not use associated objects

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#223]
Associated objects should only be used as a last resort, when modifying a system framework with new properties is really the only option. With PutFile streaming I don't believe we're at that point, this code could be refactored to be cleaner and less fragile. I have also seen situations where this code does not seem to work at all, and an alternate method to PutFile had to be used.

**Comment by hugh22** [comment]
I have seen many situations where it works fine every time actually and is not fragile at all. But w/e.

**Comment by joeljfischer** [comment]
I haven't tested extensively, so I would need to verify for myself. I've only heard it from one third-party I worked with. Generally I try to avoid runtime manipulations, but if it works fine then it would be low on the priority list.

**Comment by adein** [comment]
@joeljfischer Do we want to use this issue for the putfile streaming changes that are incoming (alignment with Android methodology), or create a new one?

**Comment by joeljfischer** [comment]
I would just create a new one that's specific to the changes requested, and reference this issue. If the PR fixes both issues then it would just mark that it fixes both.

**Comment by joeljfischer** [comment]
This can be closed once the abstraction layer ships ships
