### ISSUE TITLE
Add PLAY_PAUSE to ButtonName enum

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#246]

**Comment by justinjdickow** [comment]
Need to go back to #146 to check if PLAY_PAUSE is a 4.0.0 RPC change.

**Comment by joeljfischer** [comment]
@justinjdickow do you know what's up with this issue?

**Comment by joeljfischer** [comment]
See:
* https://github.com/smartdevicelink/sdl_android/pull/229
* https://github.com/smartdevicelink/sdl_core/pull/766

**Comment by joeljfischer** [comment]
This needs to wait for a major version change of the RPC spec.

**Comment by kshala-ford** [comment]
@joeljfischer any update to the PLAY_PAUSE feature? Anyhting that need to be done beforehand?

**Comment by joeljfischer** [comment]
@kshala-ford As noted above, this needs to wait for a major version rev of the RPC spec.

**Comment by joeljfischer** [comment]
@kshala-ford I'm looking around for exactly why (it's been a while), and you may have to ask @joeygrover for the exact reason, I don't see it documented. https://github.com/smartdevicelink/sdl_core/pull/766
