### ISSUE TITLE
Implement Generics

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#247]
Covers [Proposal SDL-0007](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0007-ios-objc-generics.md).

See also #73 

Xcode 7 enables the ability to use generics with Objective-C. We should support this feature when possible.

> Objective-C has been updated to enable it and Swift to work together more seamlessly and efficiently. The new Objective-C language features include:
> 
> **Generics** Allow you to specify type information for collection classes like NSArray, NSSet, and NSDictionary. The type information improves Swift access when you bridge from Objective-C and simplifies the code you have to write.
> 
> **Nullability annotation** Lets you indicate in Objective-C source when to expect a value to be nil or non-nil, smoothing the use of Objective-C frameworks and modules from Swift code.
> 
> **Kind-Of** Objects declared as __kindof types express “some kind of X” to the compiler and can be used within generic parameters to constrain types to a particular class or its subclasses. Using __kindof allows constraints to be more flexible than an explicit class, and more explicit than just using id.

**Comment by asm09fsu** [comment]
This is in develop.
