### ISSUE TITLE
Add SDLDeviceInfo to ALM RegisterAppInterface

### ISSUE THREAD

**Issue by kmilitel** [smartdevicelink/sdl_ios#253]
SDLDeviceInfo includes hardware, os, osVersion, carrier, etc... information.

**Comment by Heath-FoMoCo** [comment]
This will have to be completed before https://github.com/smartdevicelink/sdl_ios/pull/169 is approved.

RAI should contain he DeviceInfo Struct.

**Comment by justinjdickow** [comment]
Need to confirm in #146
