### ISSUE TITLE
IAPTransport requests background processing time regardless of connection state

### ISSUE THREAD

**Issue by adein** [smartdevicelink/sdl_ios#292]
In the SDLIAPTransport applicationDidEnterBackground: method, it will ask for extra 'background' processing time to try to extend background execution time.

My concerns are:
1. This is done regardless of whether the app is actually connected to a headunit.
2. Incoming iAP data will wake up an app (temporarily) to process the data.
3. If an app is doing something while backgrounded, it should be the one asking for more background time, not the SDK.

https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS/SmartDeviceLink/SDLIAPTransport.m#L121

I suggest (at a minimum) adding a check for connection state, or removing this altogether.

**Comment by joeljfischer** [comment]
I'm in agreement with this. For whatever reason I figured those notifications would only get posted if there was an active connection, but it doesn't look like that's the case. If the app has integrated SDL proxy with IAP, then this will get called. It should probably be removed. We already get backgrounding as part of the External Accessory background mode.
