### ISSUE TITLE
SDLProtocolHeader throws an NSException instead of NSError

### ISSUE THREAD

**Issue by adein** [smartdevicelink/sdl_ios#294]
According to Apple's guidelines, exceptions should only be thrown due to programmer bugs, not runtime issues.  SDLProtocolHeader will throw an exception when an unknown version is encountered, resulting in an app crash.  Instead, this should return an NSError, which either the proxy handles on it's own (abort or recycle the proxy), or returns to the app.  I think the former makes the most sense.

https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS/SmartDeviceLink/SDLProtocolHeader.m#L55

**Comment by joeljfischer** [comment]
Related to #40

**Comment by joeljfischer** [comment]
Underlying bug causing this issue on TCP connections was fixed.
