### ISSUE TITLE
Use Constants instead of #define

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#3]
The parameter key and value constants defined in SDLNames.h should use extern instead of define for safe compile time type checking and to avoid collisions.

[Apple's Recommendation](https://developer.apple.com/library/mac/documentation/cocoa/conceptual/codingguidelines/Articles/NamingIvarsAndTypes.html#//apple_ref/doc/uid/20001284-1003095) suggests

>Define constants for strings used for such purposes as notification names and dictionary keys. By using string constants, you are ensuring that the compiler verifies the proper value is specified (that is, it performs spell checking).

**Comment by joeljfischer** [comment]
Additionally, these defines cause greater memory use because a new string is instantiated every time the macro is used; with constants only one string would be used.
