### ISSUE TITLE
SDLHexUtility causes crash when streaming audio over TCP/IP.

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#306]
Looks like when we are streaming audio over TCP/IP, we get occasional crashes on the device. After digging into the code, it looks like the culprit is SDLHexUtility and it's performance. The memory allocation on this function is very high, sometimes upwards of 300+MB, which is causing the crash.

**Comment by joeljfischer** [comment]
We probably need an `@autoreleasepool` here: https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS/SmartDeviceLink/SDLTCPTransport.m#L65

I'm guessing that would fix it since it would force the autorelease of the previous iteration's temp variables.

**Comment by asm09fsu** [comment]
@joeljfischer yes, this fixes the memory allocation issue. I would highly recommend changing this to a C based function. The execution time is 97% (on average) faster on just the parsing alone.

I went ahead and added this as a PR, located here: https://github.com/smartdevicelink/sdl_ios/pull/307

**Comment by joeljfischer** [comment]
Fixed in #307
