### ISSUE TITLE
Policy Updates Fail With 4.0.0-RC.1 and MobileWeather

### ISSUE THREAD

**Issue by adein** [smartdevicelink/sdl_ios#310]
Using the MobileWeather app with the 4.0.0 RC.1 release results in policy updates failing.  Each request results in SYNC waiting a long time until the failure message is displayed, most likely due to a timeout.

Using the same phone, same TDK, but with a production app (with the 2.3.2 release of the AppLink SDK) resulted in the policy update working just fine.  This was tested several times with the same result.

Used the MobileWeather (tutorial branch):
https://github.com/smartdevicelink/sdl_mobileweather_tutorial_ios/tree/tutorial

Used the 4.0.0-RC.1 (via Cocoapods):
https://github.com/smartdevicelink/sdl_ios/tree/4.0.0-RC.1

**Comment by joeljfischer** [comment]
Issue is related to [ATS](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/) in iOS 9. See PR #311 for an example fix for now. Future fix will involve server implementing HTTPS.
