### ISSUE TITLE
Lock screen icon fetching should cache images

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#313]
If the URL is the same as a cached image, it should only redownload after a period of time.

**Comment by NicoleYarroch** [comment]
@joeljfischer Was this fixed in PR 1033: [Implement SDL-0041 - App Icon Resumption](https://github.com/smartdevicelink/sdl_ios/pull/1033)

**Comment by joeljfischer** [comment]
Nope, this is a separate issue
