### ISSUE TITLE
SystemRequest RPCs on SDL iOS SDK missing

### ISSUE THREAD

**Issue by fkattner** [smartdevicelink/sdl_ios#323]
We had a workshop over here to work with online traffic and we saw some issues on the iOS SDK for SDL (4.0.1).
 
The file SmartDeviceLink.h is missing some imports. It should contain:
#import “SDLSystemRequest.h”
#import “SDLSystemRequestResponse.h”
 
If an iOS app wants to send SystemRequest it would need to import them by themselves.
 
The file SDLProxyListener.h should contain:
- (void)onSystemRequestResponse:(SDLSystemRequestResponse *)response;
 
If an iOS app sends a SystemRequest is cannot receive its response.

**Comment by joeljfischer** [comment]
Note that an iOS app actually cannot import it themselves, since the file is currently set to project, not public. This appears to be an oversight.

**Comment by justinjdickow** [comment]
@fkattner What is the use case for the mobile app sending a SystemRequest? Joel has a pull request that adds the functionality, but the developer would also get an onSystemRequestResponse for any system requests that happen internally as well. We're trying to figure out the best thing to do here.

**Comment by fkattner** [comment]
**@justinjdickow **The mobile app sends the SystemRequest to Sync after providing TrafficData (TMC) via PutFile. The previously mentioned problem wit always retirieving the response GENERIC_ERROR does not occur anymore., This was caused by a error in the app's implementation.

**Comment by joeljfischer** [comment]
@fkattner so is this resolved, or is a different issue resolved and this one is still open? What do you need to know from the SystemRequestResponse that isn't available now?
