### ISSUE TITLE
Heartbeat timer still running after app disconnect.

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#341]
Currently, when connecting an app, the heartbeat timer functions and fires as intended. However, when the application is disconnected and the proxy is closed, the heartbeat timer still fires. It seems that although within `SDLTimer`, in the dealloc method, that `- (void)cancel` is in fact called, however it does not fire.  

Solution:

Change `SDLProtocol.m`:
```
- (void)destructObjects {
    if (!_alreadyDestructed) {
        _alreadyDestructed = YES;
        self.messageRouter.delegate = nil;
        self.messageRouter = nil;
        self.transport = nil;
        self.protocolDelegateTable = nil;
        self.heartbeatTimer = nil;
    }
}
```

to 
```
- (void)destructObjects {
    if (!_alreadyDestructed) {
        _alreadyDestructed = YES;
        self.messageRouter.delegate = nil;
        self.messageRouter = nil;
        self.transport = nil;
        self.protocolDelegateTable = nil;
        [self.heartbeatTimer cancel];
        self.heartbeatTimer = nil;
    }
}
```

**Comment by joeljfischer** [comment]
That solution seems to mask the problem rather than fixing it. Can we develop a unit test that shows the failing functionality so we can determine something that will fix it? Also, don't forget that there's GCD based timer code on one of the branches. Even if it doesn't solve that problem, it may solve this one?

**Comment by asm09fsu** [comment]
I agree about masking the issue, I didn't have enough time to really look yesterday, but wanted to get this here before I forgot. I do know that we have a GCD Timer branch, just want to make sure we had this on record so we can validate if it's still occurring when that branch gets merged.

**Comment by asm09fsu** [comment]
Figured out a part of the issue. Seems that NSTimer is keeping a retain cycle with SDLTimer, so dealloc is never called. Simply passing in SDLTimer as a weak reference when declaring the NSTimer object fixes this issue and allows us to properly call dealloc on SDLTimer.

```
__weak typeof(self) weakSelf = self;
self.timer = [NSTimer timerWithTimeInterval:self.duration target:weakSelf selector:@selector(timerElapsed) userInfo:nil repeats:self.repeat];
```

However, it seems the `elapsedBlock()` is still firing after the dealloc method had been called, which is still our issue.

I looked over the dispatch_timer's code, and it seems as though there *will be* the same issue with the `elapsedBlock()` still firing, although the retain cycle seems to have been fixed.

**Comment by joeljfischer** [comment]
So it seems that the basic requirement here is that we cannot `nil` the timer before we invalidate / cancel it. Cancelling in `dealloc` simply will not work.

**Comment by kshala-ford** [comment]
If it wasn't discussed yet: See http://stackoverflow.com/a/16477837 it mentions that you need to call NSTimer.invalidate in the same thread you create and schedule the timer. This is probably because the invalidate method of the timer looks out for the currentRunLoop instead of mainRunLoop. Those runloops are different for each thread.

**Comment by joeljfischer** [comment]
I'm pretty sure we're calling `invalidate` on the same thread.

**Comment by kshala-ford** [comment]
Copy pasted from some logs (not fully related to timer etc. but you can see the thread name):
Thread 5, name = (null) | [2016/03/03 11:39:30:480] -[SDLProtocol startHeartbeatTimerWithDuration:]
Thread 6, name = (null) | [2016/03/03 11:39:31:063] -[SDLTimer stopAndDestroyTimer]
Main thread | [2016/03/03 11:40:00:522] -[SDLTimer stopAndDestroyTimer]

**Comment by joeljfischer** [comment]
Closed for #368

**Comment by asm09fsu** [comment]
This is a more general issue, as it impacts any class that utilizes SDLTimer

**Comment by asm09fsu** [comment]
Closing in favor of the more generic issue: #382
