### ISSUE TITLE
Update MTU size for v3 protocol

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_ios#342]
For the v3 protocol we need to update the mtu with the details below:
Payload of a message will be 131072
Complete message will be 131072+12 byte header

**Comment by Heath-FoMoCo** [comment]
@joeljfischer Want to make sure this makes it into 4.0.2.  Are you going to make the change?  Or should someone on our end?

**Comment by joeljfischer** [comment]
If you guys want to submit a PR with the change, go ahead, otherwise I'll probably get to it sometime tomorrow.
