### ISSUE TITLE
image and text streaming in iOS issue

### ISSUE THREAD

**Issue by divinebaibhav** [smartdevicelink/sdl_ios#343]
How we can do image and text file streaming  like this method 

- (BOOL)sendVideoData:(CVImageBufferRef)imageBuffer;

**Comment by justinjdickow** [comment]
You should use PutFile to send images which will be reference in a Show RPC (to show an image on screen in vehicle). What is the use case for sending text files?

**Comment by divinebaibhav** [comment]
can I get a demo code?

**Comment by asm09fsu** [comment]
@divinebaibhav please answer Justin's question in order for us to best help. If you are inquiring about how to show images and text on the screen in the form of a show, check out our [hello_sdl_ios example](https://github.com/smartdevicelink/hello_sdl_ios/), more specifically [here](https://github.com/smartdevicelink/hello_sdl_ios/blob/master/HelloSDL/HelloSDL/HSDLProxyManager.m#L214) or our [sdl_mobileweather_tutorial_ios](https://github.com/smartdevicelink/sdl_mobileweather_tutorial_ios/tree/tutorial), more specifically [here](https://github.com/smartdevicelink/sdl_mobileweather_tutorial_ios/blob/tutorial/MobileWeather/SmartDeviceLinkService.m#L510).

**Comment by divinebaibhav** [comment]
thanks..
