### ISSUE TITLE
On Session Ended, hashID should be sent for RPC Service.

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#345]
When ending the RPC service, the SDK needs to include the hashId received from the start service ack for service type 7.  We need to store the hash id used for each session that is established via start session ack and send in the end service request for service type 7.  This is only required to end an RPC session, other services established do not require the hash id to be ended.

**Comment by joeljfischer** [comment]
Fixed in 4.2.0
