### ISSUE TITLE
Session IDs don't get cleared when a service ends

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#349]
Correct me if I'm wrong, but it looks like we're just storing them and not clearing them. 

https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink-iOS/SmartDeviceLink/SDLProtocol.m#L327

**Comment by asm09fsu** [comment]
Seems like that is the case, yes. Something like this should be done similar to #346 Pull Request.
