### ISSUE TITLE
How can I get  vehicle Data like speed,fuel,gps,others? 

### ISSUE THREAD

**Issue by divinebaibhav** [smartdevicelink/sdl_ios#351]
Hi,
Im using TDK 

I m not getting call in this method below method

- (void)onOnVehicleData:(SDLOnVehicleData *)notification

**Comment by joeljfischer** [comment]
Make sure you are subscribing to vehicle data first with `SubscribeVehicleData`, also make sure vehicle data is working with `GetVehicleData`. You can use Get to get the initial values, and also subscribe to get future changes.

**Comment by divinebaibhav** [comment]
I have done     _vehicleDataSubscribed = YES;

not getting in call in  any
- (void)onOnVehicleData:(SDLOnVehicleData *)notification ;
- (void)onSubscribeVehicleDataResponse:(SDLSubscribeVehicleDataResponse *)response ;

**Comment by divinebaibhav** [comment]
I m getting this:
-(void) onSubscribeVehicleDataResponse:(SDLSubscribeVehicleDataResponse*) response  as Response:

SubscribeVehicleData (response)
{
    bodyInformation =     {
        dataType = "VEHICLEDATA_BODYINFO";
        resultCode = SUCCESS;
    };
    eCallInfo =     {
        dataType = "VEHICLEDATA_ECALLINFO";
        resultCode = SUCCESS;
    };
    engineTorque =     {
        dataType = "VEHICLEDATA_ENGINETORQUE";
        resultCode = SUCCESS;
    };
    externalTemperature =     {
        dataType = "VEHICLEDATA_EXTERNTEMP";
        resultCode = SUCCESS;
    };
    fuelLevel =     {
        dataType = "VEHICLEDATA_FUELLEVEL";
        resultCode = SUCCESS;
    };
    "fuelLevel_State" =     {
        dataType = "VEHICLEDATA_FUELLEVEL_STATE";
        resultCode = SUCCESS;
    };
    gps =     {
        dataType = "VEHICLEDATA_GPS";
        resultCode = SUCCESS;
    };
    info = "Subscribed on provided VehicleData";
    resultCode = SUCCESS;
    speed =     {
        dataType = "VEHICLEDATA_SPEED";
        resultCode = SUCCESS;
    };
    success = 1;
}
