### ISSUE TITLE
policy Disallowed in SubscribedvechileData response? 

### ISSUE THREAD

**Issue by divinebaibhav** [smartdevicelink/sdl_ios#352]
getting SubscribedvechileData response 
info = "Ploicy disallowed"
"result code"= DISALLOWED

In TDK

**Comment by joeljfischer** [comment]
[We need alot more information than that](http://yourbugreportneedsmore.info).

Specifically, code examples, a small test app would be ideal, or failing test cases. We also need to know TDK version, iOS version, SDL version, etc.

**Comment by divinebaibhav** [comment]
I m attaching two files SDLManager to connect .
[SDLManager Query Files.zip](https://github.com/smartdevicelink/sdl_ios/files/133723/SDLManager.Query.Files.zip)



I getting different issue in TDK , ALE, real Vehicle

SYNC TDK X1
IOS 9
pod 'SmartDeviceLink-iOS', '4.0.1'


And used this code in appdelegate to start:
{
   
 let sharedObject = SDLManager.sharedManager()
        sharedObject .startProxy()
        sharedObject.delegate = self
}

//MARK:-- Here we get vechile Data on ALE 
/**
 OnVehicleData (notification)
 {
 bodyInformation =     {
 ignitionStableStatus = "MISSING_FROM_TRANSMITTER";
...
 };
 "fuelLevel_State" = LOW;
 gps =     {
 actual = 0;
....
 heading = 173;
 latitudeDegrees = "30.5071124747";
 longitudeDegrees = "114.3966938034";
...
 speed = 140;

 };
 prndl = SPORT;
 speed = 140;
 }

 **/


But on TDK we we get permission disallowed but it get connected.

But in ford real vehicle can't connect  even


thanks
:)

**Comment by asm09fsu** [comment]
@divinebaibhav please use code tags in the future. 

Note that applications have permissions that are maintained by their OEM, and vehicle data is one of those permissions. You must contact Ford directly to be able to use that application on a TDK and Ford Vehicle. 

Please refer to our documentation on developer.ford.com (or more specifically [here](https://developer.ford.com/pages/register-your-application-ios#toc0)) on how to continue. 

Closing.

**Comment by divinebaibhav** [comment]
i have registered appid.
1)  getting odometer nil on TDK 2.2
2) On TDK X1 getting permisssion disallowed issue
..

thanks for help

**Comment by joeljfischer** [comment]
@divinebaibhav please move discussion about OEM specific issues to that OEM's developer forums as @asm09fsu noted.
