### ISSUE TITLE
No retry for iAP connection 

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_ios#353]
in iOS SDL proxy, there is no retry iAP connection and i see comments “Current strategy disallows automatic retries.“ https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink-iOS/SmartDeviceLink/SDLIAPTransport.m#L236

**Comment by joeljfischer** [comment]
Currently unnecessary as we have not seen any issues.

**Comment by madhuy** [comment]
@joeljfischer 
Here is failure use case I observed in TDK
1. Launch app in Mobile first
2. POWER on the TDK ( it will start SDL core)
3. No app is showing on app screen
4. Kill the app and start in mobile, app is visible.

These use case can be fixed by using retry logic in proxy.

**Comment by joeljfischer** [comment]
@madhuy That's not the same type of issue as a retry issue. This would be an issue of the iAP session not starting at all in that specific case. Please open a separate issue all necessary information.
