### ISSUE TITLE
`OnProxyOpened` is mistakenly called for all service types

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#358]
### Bug Report
Currently, it appears that we are calling `onProxyOpened` from [SDLProxy L#183](https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m#L183) for every service type. I am unsure if the `||` should be `&&` or if there's a reason the line is as it is.

##### Reproduction Steps
1. Connect to Core using RPC service
1. Enable another service, such as the video service

##### Expected Behavior
`SDLProxy` does not call `onProxyOpened` on its delegate.

##### Observed Behavior
`SDLProxy` calls `onProxyOpened` on its delegate.

##### OS & Version Information
* iOS Version: 9.2.1
* SDL iOS Version: 4.0.1
* Testing Against: SDL Core 4.0.4

**Comment by joeljfischer** [comment]
@asm09fsu @Heath-FoMoCo @justinjdickow  Do you know why we have a version check in the line linked above? Do you know if there's bad ramifications for removing `|| [SDLGlobals globals].protocolVersion >= 2`?

**Comment by Heath-FoMoCo** [comment]
@khburdette might have to help.  He might be the most familiar with how the different sessions are notified of connection .  @mrapitis can you comment based on android?

**Comment by mrapitis** [comment]
On android we only call onProxyOpened when a new (unencrypted) RPC session is established.  I'm not sure why a protocol version check is occurring on iOS.

**Comment by joeljfischer** [comment]
Okay, I'm going to remove it in the security branch since it's causing some oddities for video / audio. If we discover something in testing, we can deal with it then.

**Comment by Heath-FoMoCo** [comment]
@joeljfischer :+1:

**Comment by joeljfischer** [comment]
Fixed in a4f1eac95ceeb90270cd054a66045b29b3992fd8
