### ISSUE TITLE
Support for the HTTP requestType is missing

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#364]
### Bug Report
HTTP RequestType support is missing - this is required for unencrypted policy table updates to work in SDL Core.

##### Reproduction Steps
https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m#L314-L326

##### Expected Behavior
Working on it.... I don't know yet

##### Observed Behavior
Requests are just dropped

**Comment by madhuy** [comment]
FYI - SDL core develop branch send request type as PROPRIETARY  for policy update https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/application_manager/src/message_helper/message_helper.cc#L2099

that means this fix may not work for develop branch SDL core.

**Comment by justinjdickow** [comment]
@madhuy Currently making it work against the release branch according to spec, then will discuss what's in develop and how it's supposed to work in 4.1 of SDL Core

**Comment by justinjdickow** [comment]
Just realized we aren't actually sending data to the sdl server using the method provided...
