### ISSUE TITLE
Timers are not appropriately stopped when deallocated.

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#382]
This is a more generic issue stemming from #341 
### Bug Report

Our custom timer class, `SDLTimer`, is currently not handling itself correctly when set to nil, without being cancelled beforehand. i.e. the `elapsedBlock` will continue to fire.
##### Reproduction Steps
1. Use a version of SDL that supports sending heartbeats (v4.0.2).
2. Connect application to Core
3. Disconnect app.
4. Look at logs. Will see printout for inability to send heartbeat.
##### Expected Behavior

Timers are correctly stopped.
##### Observed Behavior

Timers still fire.
##### OS & Version Information
- iOS Version: 9.1.2
- SDL iOS Version: v4.0.2
- Testing Against: iOS Simulator connected to Core via Relay.

**Comment by joeljfischer** [comment]
I believe this is an NSTimer limitation. Do we know if we're planning on doing anything about this?

**Comment by joeljfischer** [comment]
@asm09fsu Has this been fixed?

**Comment by asm09fsu** [comment]
@joeljfischer no. This is still an issue an easily reproducible.
Steps:
1. Comment out [this line](https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLProxy.m#L262) in `SDLProxy.m`.
2. Connect the Example app to a testing device over iAP. 
3. Leaving the app on the device in the foreground, you'll notice that the app will disconnect and reconnect every 10 seconds (due to the timer firing).
4. Backgrounding the app on the device, you'll see that the app never disconnects and reconnects until the app is brought back in to the foreground.

I'm not sure if we can resolve this at this time, as it seems to be a limitation of the `NSTimer`. Do we have the same drawbacks using GCD? What if we monitor when the app is going to the background, notice what timers are active, and potential request more time from the OS?

**Comment by joeljfischer** [comment]
I believe timers _should_ be working in the background when the `mainRunLoop` is active. I'm not sure why it does not in this case. Perhaps we should create a minimal project to repro the issue and request assistance from Apple? I don't know why there'd be a difference between running on an External Accessory background process and requesting additional time.
