### ISSUE TITLE
Streaming sessions are not closed on proxy disconnect

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#386]
### Bug Report

Currently, if a video or audio streaming session in `SDLStreamingMediaManager` is connected and streaming, and the proxy gets disconnected, the streams are in a non-ideal state as they are not closed.
##### Reproduction Steps
1. Connect Proxy to Core.
2. Begin video/audio streaming.
3. Disconnect Proxy from Core. 
##### Expected Behavior

Video/audio streaming should be stopped.
##### Observed Behavior

Video/audio streaming is not stopped.
##### OS & Version Information
- iOS Version: iOS 9.3
- SDL iOS Version: 4.1.0
- Testing Against: Core 4.0

**Comment by joeljfischer** [comment]
How do you mean disconnect? If only the ROC service disconnects that does not affect the video or audio services.

**Comment by asm09fsu** [comment]
Shouldn't we be checking the connection state of the proxy before sending data of any kind? This may actually be even further out of scope and be a question for the entirety of the proxy.

If we start a video session, and core is shut down, what happens to this session? Is the `videoSessionConnected` updated? It doesn't seem so.

**Comment by joeljfischer** [comment]
When a transport is disconnected, it ought to notify the proxy, which ought to notify its protocol that all sessions have been terminated, which should then roll back up the chain to the streaming manager. That's how I think it should work, but I doubt it does work that way.

**Comment by joeljfischer** [comment]
@asm09fsu Has this been fixed?

**Comment by asm09fsu** [comment]
@joeljfischer This has not been resolved, however with the improvements in [this proposal](https://github.com/smartdevicelink/sdl_evolution/pull/56) it would be resolved. We could add a hot fix in now that would notify SMM of these changes.

**Comment by joeljfischer** [comment]
@asm09fsu That would be better. We don't want to wait 'till 5.0 for bug fix changes if possible.
