### ISSUE TITLE
Failed to SDLSetDisplayLayout "NON_MEDIA" for a non_media app. 

### ISSUE THREAD

**Issue by Mage25** [smartdevicelink/sdl_ios#392]
### Bug Report
Failed to SetDisplayLayout to "NON_MEDIA" for a non_media app demo(proxy SmartDeviceLink 4.1.0)

##### Reproduction Steps
I coded a demo, in which need to reset layout to be "NON_MEDIA" in below two situations:
<1>. 
change layout from "TILES_ONLY" to "NON_MEDIA" when press softButton "Near" in base interface
 Result:  the layout is still "TILES_ONLY"
 Response: resultCode = "INVALID_DATA"
![titleonlytononmedia](https://cloud.githubusercontent.com/assets/14119225/15065304/ee300d34-1390-11e6-9654-7e65ae178458.png)

<2>.
change layout from "GRAPHIC_WITH_TEXTBUTTONS" to "NON_MEDIA" when press softButton "Look detail"(you can find the button when you press softButton "Road" in base interface)
 Result: the layout is still "GRAPHIC_WITH_TEXTBUTTONS"
Response: resultCode = "INVALID_DATA"
![non_media](https://cloud.githubusercontent.com/assets/14119225/15065322/2042fa48-1391-11e6-8b3c-e86ebcede9b7.png)

##### Expected Behavior
SetLayout "NON_MEDIA" successfully for non_media app.

##### Observed Behavior
Get response - "INVALID_DATA" when set layout to "NON_MEDIA", and the layout unchanged.
[Note]I reached the effect via setting layout to "DEFAULT". 
ResultCode
![img_0028](https://cloud.githubusercontent.com/assets/14119225/15065776/8281d220-1395-11e6-8805-721c6c375421.PNG)

Response:
![img_0027](https://cloud.githubusercontent.com/assets/14119225/15065772/7b57ad1c-1395-11e6-88da-786f097b8413.PNG)

##### OS & Version Information
* iOS Version: iPhone5s_iOS9.2.1
* SDL iOS Version:SmartDeviceLink4.1.0
* Testing Against: Free test

##### Test Case, Sample Code, and / or Example App
Please refer to the two methods in HSDLProxyManager.m:
hsdl_showNearDetailPage
hsdl_showRoadDetailPage
[Demo.zip](https://github.com/smartdevicelink/sdl_ios/files/251606/Demo.zip)

**Comment by justinjdickow** [comment]
Can you try using `@"NON-MEDIA` instead of `@"NON_MEDIA"`

**Comment by Mage25** [comment]
"NON-MEDIA" works. Thanks a lot. I'm careless.
BTW, "NON-MEDIA" is not displayed in response above. Is it as expected?
