### ISSUE TITLE
Don't use Exceptions as flow control

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#40]
From [Apple](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html)

> Although Objective-C includes syntax for exception handling, Cocoa and Cocoa Touch use exceptions only for programming errors (such as out of bounds array access), which should be fixed before an app is shipped.
> All other errors—including runtime problems such as running out of disk space or not being able to access a web service—are represented by instances of the NSError class. Your app should plan for errors and decide how best to handle them in order to present the best possible user experience when something goes wrong.

I've noticed a few places in the proxy where exceptions are used as flow control, those should be refactored.

**Comment by joeljfischer** [comment]
Some of the code wrapped in try-catch statements literally can't even throw exceptions.

**Comment by justinjdickow** [comment]
![litorfig](https://cloud.githubusercontent.com/assets/3627664/5862125/251b7444-a23d-11e4-94f3-ad532f167401.jpg)

**Comment by joeljfischer** [comment]
![](https://s-media-cache-ak0.pinimg.com/736x/77/09/9e/77099e99060209eda33a58858fd7b962.jpg)

**Comment by joeljfischer** [comment]
Example: https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS/SmartDeviceLink/SDLPolicyDataParser.m#L13

**Comment by asm09fsu** [comment]
@joeljfischer are we still doing this for 5.0?

**Comment by joeljfischer** [comment]
I'd like to check it. It shouldn't be hard.
