### ISSUE TITLE
Add Touch Manager for improved onTouchEvent Handling

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#402]
### Bug Report
After dealing with using the onTouchEvent callback, I propose we design an architecture for having a touch manager to give callbacks that allow developers to know if certain touch events are happening. Currently the following are thought of as important:
- Taps
  - Single Tap
  - Double Tap
- Pinch
  - Pinch Did Start
  - Pinch Moved
  - Pinch Did End
- Pan
  - Pan Did Start
  - Pan Moved
  - Pan Did End

The point of this manager is to allow developers to use their time dealing with these touch events, instead of building logic to figure out when these touch events occur.

**Comment by joeljfischer** [comment]
Would it make sense to mirror iOS' own gesture and uiresponder architecture
for familiarity?

**Comment by asm09fsu** [comment]
I considered that, however if we do something similar to how the gesture recognizer's work is there is still a catch all function for the respective gesture (tap, pinch, pan). I tried to think of it by completely extracting out the logic needed to determine what state you are currently in, and make it a bit more clean.

**Comment by joeljfischer** [comment]
Fixed in #423
