### ISSUE TITLE
Drop iOS 6 support

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#419]
Covers [Proposal SDL-0008](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0008-ios-7-0-minimum.md).
### Feature Request

We should seek to drop iOS 6 support. Virtually no one uses it and it would allow us to drop the NSURLConnection support and simplify a lot of code with NSURLSession instead.

**Comment by joeljfischer** [comment]
It would be awesome if we could also drop iOS 7 support and just support iOS 8+ and Swift.

**Comment by tpulatha** [comment]
There are quite some Apps on iOS that still support iOS7. So we will have to wait with that.

**Comment by joeljfischer** [comment]
I know 😭
