### ISSUE TITLE
Corrupted framework archive for version 4.1.3

### ISSUE THREAD

**Issue by mokagio** [smartdevicelink/sdl_ios#422]
### Bug Report

The framework archive for [version 4.1.3](https://github.com/smartdevicelink/sdl_ios/releases/tag/4.1.3) , [SmartDeviceLink.framework.zip](https://github.com/smartdevicelink/sdl_ios/archive/4.1.3.zip), contains an `#import` statement for an header that doesn't exist. The same file in the source does not contain that statement.

This results in project fetching the library using `carthage bootstrap` or `update`, which by default download the archive for a GitHub release to fail building.

##### Reproduction Steps
1. Download the archive for version 4.1.3. [Link](https://github.com/smartdevicelink/sdl_ios/archive/4.1.3.zip)
1. Extract the zip
1. Open `Carthage > Build > iOS > SmartDeviceLink.framework > Headers > SDLRPCRequestFactory.h`
1. Notice the `#import "SDLNotificationConstants.h"` statement.
1. Compare with the [`SDLRPCRequestFactory.h` source at 4.1.3 (6c331d5)](https://github.com/smartdevicelink/sdl_ios/blob/6c331d5eecc7c5993ce724b98eda92a2e8560173/SmartDeviceLink/SDLRPCRequestFactory.h)
1. Notice how the import statement is not present, also notice how `SDLNotificationConstants.h` is not present anywhere in the project.

##### Expected Behavior

The archive and source code should match.

##### Suggested Solution

Add an automated step to the release pipeline with that verifies the Carthage integration.

---

Thanks team 👍 ❤️

**Comment by joeljfischer** [comment]
I just re-did the archive, see if that fixes it. I manually did it last time as well, not sure if my directory was corrupted somehow perhaps?
