### ISSUE TITLE
iOS Library does not terminate properly if app is force-closed

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#437]
### Bug Report
See this issue for more detail: https://github.com/smartdevicelink/sdl_core/issues/682

If an app containing the iOS library is force closed, the connection is not terminated properly. Therefore, if the app attempts to reconnect, it will receive a `DISALLOWED` as a result of that app still being registered with the head unit.

##### Reproduction Steps
1. Connect an app to Core on iOS
1. Bring up the app switcher and swipe the app away to force-close it
1. Re-connect the app to Core

##### Expected Behavior
The app successfully connects

##### Observed Behavior
The app fails to connect with a DISALLOWED message

##### OS & Version Information
* iOS Version: 9.3.4
* SDL iOS Version: 4.2.1
* Testing Against: Sync TDK v3

**Comment by asm09fsu** [comment]
@joeljfischer I'm not seeing this

**Comment by joeljfischer** [comment]
This bug is currently unfixable from the iOS end. There are a few ways to fix this. On IAP, there should be a callback (or something similar) saying that the connection is closed. On Wifi, the remote system should be using heartbeats, which the iOS app will respond to as long as it is available to do so.
