### ISSUE TITLE
SDL iOS 4.3 should deprecate `SDLRPCRequestFactory` and add `init` methods for RPCs to replace them

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#458]
Because SDL 5.0 is intending to remove `SDLRPCRequestFactory`, SDL 4.3 should add `init` methods and builders to point people to.

Related: [SDL-0020](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0020-ios-remove-rpcrequestfactory.md)

**Comment by asm09fsu** [comment]
Committed in ee5bf8c
