### ISSUE TITLE
SDL proxy is not establishing Data session when app is in Back ground

### ISSUE THREAD

**Issue by madhuy** [smartdevicelink/sdl_ios#483]
### Bug Report
SDL proxy is not establishing Data session when app is in Back ground.

##### Reproduction Steps
1. Connect Phone to HU
2. start Application HS and make sure it is running on HU
3.IGN OFF
4. Press Home screen on Mobile to enter app in background
5. IGN ON 

##### Expected Behavior
App should connect to HU and work properly

##### Observed Behavior
App is not connected.

##### OS & Version Information
* iOS Version: 9.3.5
* SDL iOS Version: 4.2
* Testing Against: internal HU

Analysis,
Data session is created in main queue , that might cause not establish data session when app is in background
https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLIAPTransport.m#L336
Suggestion:
1.  create background thread having runloop, which deals EASession I/O stream.
2. create data session in background thread instead in main_queue. 

I modified quickly , it seems creating Data session now. but the problem is ,
It is recives version:1 message instead of ACK , Not sure reason
`forProtocol:com.smartdevicelink.prot2
2016-12-15 12:00:15.151 CTSMediaApp1[342:54231] [29] Opening EASession withAccessory:LEXUS forProtocol:com.smartdevicelink.prot2
2016-12-15 12:00:15.160 CTSMediaApp1[342:54231] [29] Created Session Object
2016-12-15 12:00:15.167 CTSMediaApp1[342:54236] starting the event loop for accessory
2016-12-15 12:00:15.167 CTSMediaApp1[342:54236] [30] Output Stream Opened
2016-12-15 12:00:15.168 CTSMediaApp1[342:54236] [30] Input Stream Opened
2016-12-15 12:00:15.168 CTSMediaApp1[342:54236] [30] Data Session Established
2016-12-15 12:00:15.168 CTSMediaApp1[342:54236] [30] StartSession (request)
2016-12-15 12:00:15.890 CTSMediaApp1[342:54235] [31] message complete. Version:1, compressed:0, frameType:0, serviceType:7, frameData:3, sessionID:1, dataSize:0 Payload: 0 bytes.
`

**Comment by asm09fsu** [comment]
@madhuy can you please pull master and try again to make sure? We are currently on version 4.4.1

**Comment by asm09fsu** [comment]
@madhuy iOS 10 also added in the ability for applications to be launched in the background. Is this issue still reproducible on iOS 10.2?

**Comment by madhuy** [comment]
@asm09fsu even in iOS10 also we have to bring apps to bring foreground manually.
Did you fi any iAP transport bugs in 4.4.1 ?

**Comment by asm09fsu** [comment]
There is some more advanced lifecycle management introduced in 4.3.

**Comment by asm09fsu** [comment]
@madhuy The logs here look okay. The mobile side always sends version 1 with the Start Session for RPC because it is the first call we make. Core then responds back with the correct protocol version we should be using in the ACK. This is why Start RPC Session is required to be the first call made.

**Comment by madhuy** [comment]
@alex I see below message after data session established
`message complete. Version:1, compressed:0, frameType:0, serviceType:7, frameData:3, sessionID:1, dataSize:0 Payload: 0 bytes.`
But, SDL proxy expects Version:2 and frameData:3 to send **onProxyOpened** to the Application.

And also I tried with TDK and Spotify, some times it works some times not.
It does NOT work , if we IGN ON after 10 minutes of IGN OFF.  If we bring Spotify App, it works.

**Comment by asm09fsu** [comment]
"message complete…" is coming from iOS: https://github.com/smartdevicelink/sdl_ios/blob/e7845f4bf9ddeb0fe8a4a2b42d25a88d6ae7429a/SmartDeviceLink/SDLProtocol.m#L384

not core.

**Comment by madhuy** [comment]
I guess SDL core sends to SDL proxy and SDL proxy prints it.

**Comment by asm09fsu** [comment]
@madhuy I have tried using an app on 10.2, with SDK version 4.4.1. Can you try with this combination?

**Comment by madhuy** [comment]
@asm09fsu  I am using iOS 9.3.x and iphone 5

**Comment by asm09fsu** [comment]
@madhuy after testing with Spotify on iOS 10.2, SDL version 4.4.1, I would say that the cause is due to their implementation of the SDL lifecycle is not correct, and there is a bug. Applications that utilize 4.3+ shouldn't have that issue, I think.
