### ISSUE TITLE
Remove SDLOnWaypointChange

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#489]
### Bug Report
We deprecated `SDLOnWaypointChange` due to it being a misspelled mirror of `SDLOnWayPointChange`, we may remove it in v5.0.

**Comment by asm09fsu** [comment]
Should this include `SDLSubscribeWaypoints`, `SDLSubscribeWaypointsResponse`, `SDLUnsubscribeWaypoints`, `SDLUnsubscribeWaypointsResponse`, `SDLGetWaypoints`, `SDLGetWaypointsResponse` as well?

**Comment by joeljfischer** [comment]
![](https://media.giphy.com/media/l1IYfzdrfjsCHSss8/giphy.gif)
