### ISSUE TITLE
Refactor all setters/getters for RPCs internal storage.

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#493]
### Bug Report
Currently, we have all of our RPC's properties using custom setters and getters that read/write from the internal storage. Most of this code is the same, yet there are no general categories established to make sure we are in fact doing the same thing for every property.

##### OS & Version Information
* SDL iOS Version: 4.5.0

**Comment by joeljfischer** [comment]
This is more of a feature request than a bug report...
