### ISSUE TITLE
SDLOnLockScreenStatus doesn't use constants for property keys.

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#497]
### Bug Report
Currently, `SDLOnLockScreenStatus` does not use constants (or macros in pre-5.0) for their properties, which is standard for RPCs and notifications. 

##### OS & Version Information
* SDL iOS Version: 4.5

**Comment by joeljfischer** [comment]
I think this is because it's not actually in the SDL Core RPC spec?

I don't see it anywhere in here:

https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml
