### ISSUE TITLE
IAPTransport Writes Output Stream from Different Thread than Scheduled Run Loop

### ISSUE THREAD

**Issue by davidswi** [smartdevicelink/sdl_ios#522]
The input and output streams for the EASessions used by the SDL mobile proxy are scheduled and opened on the main thread in SDLIAPSession's startStream method. However, the output stream is written to from the dispatch queue com.sdl.transport.iap.transmit in SDLIAPTransport's sendData method. This cross-thread usage of the output stream appears to violate the Apple usage guidelines for NSOutputStream, as stated in https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Streams/Articles/WritingOutputStreams.html. I have bold formatted the specific guideline from the relevant paragraph.

Before you open the stream to begin the streaming of data, send a scheduleInRunLoop:forMode: message to the stream object to schedule it to receive stream events on a run loop. By doing this, you are helping the delegate to avoid blocking when the stream is unable to accept more bytes. If streaming is taking place on another thread, be sure to schedule the stream object on that thread’s run loop. **You should never attempt to access a scheduled stream from a thread different than the one owning the stream’s run loop**. Finally, send the NSOutputStream instance an open message to start the streaming of data to the output container.

The IAPSession startStream method should be extended to include a dispatch_queue argument that should be set to nil if the main run loop is to be used and to the custom dispatch queue to be used otherwise. Then as discussed in this StackOverflow article, the run loop for the thread backing the dispatch queue should be used and the run loop's run method must be called:

http://stackoverflow.com/questions/14022044/how-to-schedule-event-in-runloop-in-gcd

Alternatively, an NSThread can be detached to process the output stream.

**Comment by madhuy** [comment]
This issue is related https://github.com/smartdevicelink/sdl_ios/issues/483.

**Comment by davidswi** [comment]
I also want to draw attention to the polling write loop in SDLIAPTransport.m sendData. There is a flaw that allows the poling write loop to hang forever. The while loop only breaks if the remainder NSMutableData copy has length of zero or the stream write fails:

 while (remainder.length != 0) {
            if (ostream.streamStatus == NSStreamStatusOpen && ostream.hasSpaceAvailable) 

However, because the stream can close on the main thread while the polling write loop is enqueued to its dispatch queue or executing, the stream status test will begin failing and the remainder will never reach zero length. This is why SDL apps appear to crash after a number of connect/disconnect cycles. iOS is terminating them because they are using far too much CPU in the tight while loop.

The tests in the if condition should be moved into the while test, or the loop should break if the stream status is not open.

**Comment by davidswi** [comment]
I think it's also reasonable to ask why writing is done in a polling loop at all, synchronously, rather than scheduled in the run loop. There are a number of examples of using NSOperationQueue to manage scheduled writes while preserving the order of the higher level messages over the transport. The IAP dispatch queue could be repurposed as the queue used by the NSOperationQueue and operations could be enqueued from the stream thread. It would only be necessary to perform the write stream operation on the stream thread from the NSOperation block.

**Comment by davidswi** [comment]
I have an experimental branch of the IAPTransport that addresses the issues with the polling loop and cross-thread access to the stream. I believe the order in which upstream changes should be made is as follows:

1. Fix the hang in the polling loop
2. Move the stream writes to the same thread that has the stream run loop. This can be done from the current dispatch block logic by performing the write operations synchronously on the main thread.
3. Move the read and write stream run loops to a dedicated NSThread
4. Make writes scheduled by using the NSOperationQueue pattern.

**Comment by davidswi** [comment]
I can submit PRs for each of these changes individually.

**Comment by tpulatha** [comment]
That would be great thank you. We will have an iOS expert looking into this shortly!

**Comment by asm09fsu** [comment]
Hey @davidswi,

I've been investigating this since you posted the issue 19 days ago (apologies for the lack of communication). I'd love it if you could add PRs for your solutions relating to the issues here, and @joeljfischer and myself will review them. 

Before we would be able to accept your code, however, we would need you to sign the [CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform).

**Comment by davidswi** [comment]
Hi I've signed the CLA.
