### ISSUE TITLE
[SDL 0014] Adding Audio File Playback to TTSChunk

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#524]
Proposal: [Adding Audio File Playback to TTSChunk](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0014-adding-audio-file-playback-to-ttschunk.md)

> More and more applications use sounds as a means to make a user feel more at home within their application, and allow the developer to have more customization of their User Experience. This proposal will allow developers to provide audio files uploaded to be played in conjunction with, or without, Text-to-Speech text, so that they may provide a more customized experience.

Review: smartdevicelink/sdl_evolution#42

Steering Committee Decision:

> This proposal was accepted. The committee feels it is a good feature to add to give apps some personality and to enable new features, and while the naming isn't ideal, it gives us the maximum amount of flexibility with the minimum extra development cost.  The implementation will have to be fleshed out on core to ensure backward compatibility.

**Comment by theresalech** [comment]
This also impacts [Android](https://github.com/smartdevicelink/sdl_android/issues/419) and [Core](https://github.com/smartdevicelink/sdl_core/issues/1277)

**Comment by joeljfischer** [comment]
The implementation of this issue depends on it being implemented in Core, so that they may both be tested.

**Comment by theresalech** [comment]
Closed via #1018
