### ISSUE TITLE
[SDL 0017] iOS Library Protocol Layer Should Not Be Public

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#525]
Proposal: [iOS Library Protocol Layer Should Not Be Public](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0017-ios-protocol-layer-nonpublic.md)

> This proposal is to make breaking changes by shifting all code on the protocol layer to be non-public. No class on the protocol layer should have a public API.

Review: smartdevicelink/sdl_evolution#45

Steering Committee Decision:

> This proposal is accepted. The committee feels this is an important cleanup for the next major version to tackle.

**Comment by joeljfischer** [comment]
Due to the deferral of [sdl_evolution/sdl 0019](https://github.com/smartdevicelink/sdl_evolution/issues/48), we will probably have to wait until a 6.0 release that includes privatizing the proxy to implement this change.
