### ISSUE TITLE
crash occurs in SDLStreamingMediaManager when disconnect USB during video streaming

### ISSUE THREAD

**Issue by clu42** [smartdevicelink/sdl_ios#529]
##### Reproduction Steps
1. Connect iPhone via USB
2. Start video streaming
3. Remove USB

##### Expected Behavior
No crash in app side

##### Observed Behavior
crash occurs, app exits automatically on phone side

##### OS & Version Information
* iOS Version: 4.5.3
* SDL iOS Version: 10.2

[SogouNavi  09-02-2017, 1-01 PM.zip](https://github.com/smartdevicelink/sdl_ios/files/769993/SogouNavi.09-02-2017.1-01.PM.zip)

**Comment by asm09fsu** [comment]
@clu42 I am unfortunately unable to reproduce this issue.

**Comment by joeljfischer** [comment]
@clu42 Can you provide more information? For example, a stack trace or an example app that reproduces the issue?

**Comment by henry-fan** [comment]
@asm09fsu Does the dump file help?

**Comment by clu42** [comment]
link to [Pull Request #530](https://github.com/smartdevicelink/sdl_ios/pull/530)
