### ISSUE TITLE
Lock screen doesn't appear when app entered via Widget or Force-touch menu items.

### ISSUE THREAD

**Issue by JamaicanRumCream** [smartdevicelink/sdl_ios#538]
### Bug Report
Lock screen doesn't appear when app entered via Widget or Force-touch menu items.

##### Reproduction Steps
1. have all phone apps backgrounded, ie view home screen with all apps
2. Plug phone into car/unit
3. start app on car
4. notice phone screen should continue to show apps/home screen
4a. press some buttons or function of the app on the car/unit
5. Force Press app on phone (in iOS 10) to display widget and/or quick action menu
6. tap on widget, assuming widget will open to the main app
6a. tap on a quick action that will take you to main app

##### Expected Behavior
Lock screen should appear right away

##### Observed Behavior
Lock screen doesn't appear. Using the app on phone will not make it appear. Using the app on the car/unit may make the lock screen appear on phone.

##### OS & Version Information
* iOS Version: 10.2.1
* SDL iOS Version: 4.5.2
* Testing Against: Accuweather app; on Sync gen3 TDK I think (8 inch touch screen)

**Comment by joeljfischer** [comment]
Hi @JamaicanRumCream, could you try the change in [this branch](https://github.com/smartdevicelink/sdl_ios/tree/hotfix/issue_538), which is [this commit](https://github.com/smartdevicelink/sdl_ios/commit/61e6f87b536bc33b944f42be7bad6786c0bab4d1) and let me know if that fixes the issue for you? I don't have an app with 3D touch to test with, but I did test with backgrounding.

**Comment by JamaicanRumCream** [comment]
Looks like it's good now. Thanks.
