### ISSUE TITLE
SDLManager's `startWithReadyHandler` should return back after onHMIStatus has been received

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_ios#540]
### Bug Report
Currently, `SDLLifecycleManager` returns back from the `startWithReadyHandler` once we receive a register app interface response, all the managers are set up, and the app icon is set. We then fire a delegate callback for `hmiLevel:didChangeToLevel:`. With this delegate callback, we are _assuming_ that we will have an HMI State by this point. We should instead return back from the `startWithReadyHandler` only after the register app interface response in received, all the managers are set up, the app icon is set *and* the `OnHMIStatus` is received.

##### OS & Version Information
* SDL iOS Version: 4.3+

**Comment by joeljfischer** [comment]
Note that this is a bug and not an enhancement, the developer expects that the `onHMIStatus` is guaranteed to have been received by that point, and in the large majority of cases it will be, but we are not guaranteeing that it will be. We should guarantee it.
