### ISSUE TITLE
Video streaming sample with iOS

### ISSUE THREAD

**Issue by rememberkarl** [smartdevicelink/sdl_ios#547]
Hi all,

First, it is not a bug thing...
I'm sorry but I just want to give you some questions for making a sample of video streaming on iOS.
I'm trying to make it done with iOS simulator and ubuntu machine which is located in another computer.
I just referred to [this article](https://www.smartdevicelink.com/en/guides/iOS/mobile-navigation/introduction/) but it didn't work.
As you see the link, my goal that I want to achieve is kind of navigation app by displaying smartphone's screen on dashboard.
So I'm looking over all the source codes of SDL iOS library, but I've not found any of clues...
Dose anyone make it done by the same way like I've done?

Thanks.

Karl

**Comment by asm09fsu** [comment]
@rememberkarl [RPC Builder](https://github.com/smartdevicelink/rpc_builder_app_ios) does very basic video streaming without encryption. Video streaming for a production environment (connecting to a vehicle) requires security libraries from the respective OEMs. 

I would suggest using RPC Builder first to make sure your setup on the ubuntu machine is set up correctly.

If using SDL Core, please use [this guide](https://github.com/smartdevicelink/sdl_core/wiki/Video-Streaming-Setup) to set up video streaming.

If using the [Ford AppLink emulator](https://developer.ford.com/pages/ale) be aware that this does not currently support mobile navigation. 

Once this has been setup correctly, you can use the guide provided [here](https://www.smartdevicelink.com/en/guides/iOS/mobile-navigation/introduction/) to setup mobile navigation (which is the link you shared).

**Comment by rememberkarl** [comment]
@asm09fsu I'm using SDL Core and SDL HMI simulator on chromium browser in same place with SDL Core, and those SDL Core and SDL iOS are connected by TCP in same Wifi network. 
I already did them all but I didn't follow a few instructions below:
 
![2017-02-23 19 15 34](https://cloud.githubusercontent.com/assets/1032805/23254807/aa11510a-f9fc-11e6-85b0-814388501120.png)

I couldn't find out where are those four instructions and what should I do for the next.

In debug logs, I gotta find out that one of the reasons why this streaming couldn't start is caused by 'no setting videoSessionConnected as true' issue. 
And a state of this variable is changed by calling 'handleProtocolStartSessionACK' method, I guess it's called by message from SDL Core through TCP communication.
There are number of classes having 'handleProtocolStartSessionACK' method, and those classes are piled in 'protocolDelegateTable' objects, but 'handleProtocolStartSessionACK' method of 'SDLStreamingMediaManager' is not called even it's added into 'protocolDelegateTable'.

Is it correct? I'm trying to figure out the way to do it but it's so complicated.

**Comment by asm09fsu** [comment]
@rememberkarl have you tried to use RPC Builder to start the video stream? Once this works we can confirm your setup is correct. Those settings are not relevant on the mobile side, so disregard those.

You should have no need to understand things such as start session acks or anything of that nature.

**Comment by rememberkarl** [comment]
@asm09fsu okay. I'll try to use RPC Builder to start for my test. Thanks.

**Comment by rememberkarl** [comment]
@asm09fsu I tried to stream camera data by RPC Builder app on iPhone6s device, but it didn't work.  There were no error messages in iPhone's logs, but some error messages were popped up in SDL HMI side. Error messages shown in SDL HMI logs are below:

'MediaEvent: PIPELINE_ERROR demuxer: could not open'
'MediaEvent: PIPELINE_ERROR pipeline: read error'

and in Developer Tools of Chromium

'GET http://127.0.0.1:5050/ net::ERR_CONNECTION_REFUSED'
'Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()'

Did I set up the SDL environment incorrectly?

**Comment by asm09fsu** [comment]
Judging from the fact that you are seeing errors, I would say your problem is stemming from that. I will be closing this issue/question as the reason nothing is working for you is due to core not being set up correctly. Please join us in [slack](https://slack.smartdevicelink.com) more specifically the *sdl_core* channel and ask for assistance, or open an issue on their [repository](https://github.com/smartdevicelink/sdl_core/).

Slack will provide the fastest response.
