### ISSUE TITLE
Driver Distraction Notification not being sent at startup or first SDLHMILevel.full() 

### ISSUE THREAD

**Issue by chuckbrandt-vml** [smartdevicelink/sdl_ios#581]
### Bug Report
Confirmed using the Relay app and version 4.5.5.   No Driver Distraction notification is being sent at app start up.  

##### Reproduction Steps
1. Start the sdlManager in this manner: 
```swift
let configuration = SDLConfiguration(lifecycle: lifecycleConfiguration, lockScreen: .disabled())
super.init()
self.addRPCObservers()
sdlManager = SDLManager(configuration: configuration, delegate: self)
```
2. Run the app in debugger
3. a breakpoint set in the driver distraction notification handler is not hit until the vehicle changes state - i.e. you don't know the initial state when the app is being run.  

##### Expected Behavior
The notification is sent once after sdlmanager start or SDLHMILevel.full() for the first time. 

##### Observed Behavior
The notification is not sent until the state changes 

##### OS & Version Information
* iOS Version: 10.2.1
* SDL iOS Version: 4.5.5
* Testing Against: 2016 Ford Escape running Sync 3 version 1.1 build 15349

**Comment by joeljfischer** [comment]
@chuckbrandt-vml What is `self.addRPCObservers()`? Can you perhaps add a small example project or some code that we can use to repro the issue?

**Comment by asm09fsu** [comment]
@joeljfischer this is from [hello_sdl](https://github.com/smartdevicelink/hello_sdl_ios/blob/feature/swift-3.0/HelloSDL/HelloSDL/HSDLProxyManager.swift#L143)

**Comment by joeljfischer** [comment]
@asm09fsu Gotcha

**Comment by joeljfischer** [comment]
This wouldn't really be an iOS issue then, I don't think, it's just passing along whatever arrives from the head unit, right?

**Comment by asm09fsu** [comment]
This is correct

**Comment by asm09fsu** [comment]
@joeljfischer @chuckbrandt-vml After confirming with Android, it seems that this is just how Driver Distraction works (although I thought it was this way). Because of this, I will be closing this issue as this would need to be something opened up again Core, not iOS, as this is not an iOS issue.
