### ISSUE TITLE
[SDL 0054] ChangeRegistration-Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#617]
Proposal: [ChangeRegistration-Manager](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0054-change-registration-manager.md)

> ChangeRegistration RPC allows an app to manipulate parameters that were sent during app registration including app name, TTS name and voice synonyms of the app. This proposal aims to make it more convenient for the app developer to change the apps registration and to provide an API which fits to the design of the application lifecycle manager.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/164

**Comment by kshala-ford** [comment]
@joeljfischer I just have started to work on implementing this proposal (will do my best but there are other things of higher priority going on). Any due date you would want a PR ready to be merged?

**Comment by joeljfischer** [comment]
The submission has to be in by Sept. 15, the review and merge would happen over the next two weeks.

**Comment by kshala-ford** [comment]
I'm going to start on Monday/Tuesday. Should be ready by Sept 15.
