### ISSUE TITLE
[SDLRPCMessage initWithDictionary] does not check whether the passed in dictionary is formatted correctly

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_ios#62]
The `initWithDictionary` function in the `SDLRPCMessage` class assumes that whatever dictionary is passed in is in a specific format. 

As a result, if a dictionary that doesn't follow this format is passed in, then the function will raise an exception which means nothing to the user.

For Example, this exception is thrown when a dictionary containing a single key:value pair is given to the function:

> "failed: caught "NSInvalidArgumentException", "-[SDLAppInterfaceUnregisteredReason objectForKey:]: unrecognized selector sent to instance 0x7f9dc349e9e0"" 

The function should check whether the dictionary follows the correct format, and return nil or throw an exception describing the problem if it does not.

**Comment by justinjdickow** [comment]
@jacobkeeler Can you link to a unit test that forces the initWithDictionary to fail?

**Comment by jacobkeeler** [comment]
At the moment, there are no tests that fail because of this issue, I just found the issue while I was writing the unit tests for SDLRPCMessage. 

After looking more into what causes the error, it appears that the cases where it happens are fairly specific. From what I can tell, it fails whenever there is an entry in the dictionary that does not have a NSDictionary value before the main entry ("notification", "request", or "response"). I am not entirely certain why this is case as of yet.

Examples:
```objc
Does Not Crash:    @{NAMES_notification:
                       @{NAMES_parameters:@{@"param":@"val"},
                         NAMES_operation_name:@"name"}}

CRASHES:           @{"key":"value", NAMES_request:
                       @{NAMES_parameters:@{@"param":@"val"},
                         NAMES_operation_name:@"name"}} 

Does Not Crash:    @{"dict":@{"key":"value"}, NAMES_notification:
                       @{NAMES_parameters:@{@"param":@"val"},
                         NAMES_operation_name:@"name"}}

CRASHES:           @{"dict":@{"key":"value"}, "key":"value", NAMES_response:
                       @{NAMES_parameters:@{@"param":@"val"},
                         NAMES_operation_name:@"name"}}

Does Not Crash:    @{NAMES_request:
                       @{NAMES_parameters:@{@"param":@"val"},
                         NAMES_operation_name:@"name"}
                     "key":"value"}
```
