### ISSUE TITLE
How to use free account for Ford car IOS app by SDL.

### ISSUE THREAD

**Issue by humray** [smartdevicelink/sdl_ios#635]
I am an IOS Developer. I only have a free apple deleveloper account.(I don't pay money for the account)
   I developed the IOS program will only for my own iPhone or iPad, will not be published to APP Store.
   My question is:
      how can I use the AppLink in My own IOS program. I needs shows my ford motor's information through the API on my iPhone.

   **The main purpose of the program is to obtain the motion of the vehicle information, such as the instantaneous fuel consumption, such as speed, recorded in my iPhone.**

**Comment by joeljfischer** [comment]
These types of uses require special permission by the OEM (such as Ford), so what you are asking for is not possible. If you have any further questions, you may address them to our slack channel. [You can sign up here](http://slack.smartdevicelink.com).
