### ISSUE TITLE
If an SDLRPCMessage object is initialized using initWithName, the messageType is always set to "request"

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_ios#64]
Regardless of the type of message, if an `SDLRPCMessage` object is initialize using `initWithName`, then the `messageType` is automatically set to "request".
```
messageType = NAMES_request;
```
This should instead set the `messageType` to whatever is appropriate based on the message.

A simple way of doing this would to override the `initWithName` function in `SDLRPCRequest`, `SDLRPCNotification`, and `SDKRPCResponse`, and set the `messageType` in that override instead.

For example, the override in `RPCNotification` might look like:
```
-(id) initWithName:(NSString*) name {
	if (self = [super initWithName:name]) {
		messageType = NAMES_notification;
		[store setObject:function forKey:messageType];
	}
	return self;
}
```

**Comment by joeljfischer** [comment]
This should be checked to see if it affects #45
