### ISSUE TITLE
Graphics with long name doesn't work

### ISSUE THREAD

**Issue by poborin** [smartdevicelink/sdl_ios#640]
### Bug Report
SDLShow does not display images with long image names. E.g. `rso_start_screen_static_map_image_name.png`

##### Reproduction Steps
1. Create and upload SDLArtfork with `rso_start_screen_static_map_image_name.png` name
2. Create an SDLShow with image that uses that name
3. Send an RPC

##### Expected Behavior
Image displayed on a headunit

##### Observed Behavior
Image not displayed on a headunit

##### OS & Version Information
* iOS Version: 10.3.2
* SDL iOS Version: 4.5.5
* Testing Against: TDK-X2 U2-221
* Firmware: 16074

##### Test Case, Sample Code, and / or Example App
```Swift
let imageName = "rso_start_screen_static_map_image_name.png"
let image = UIImage(contentsOfFile: imageName)
let artwork = SDLArtwork(image: image, name: imageName, as: .PNG)
sdlManager.fileManager.uploadFile(artwork) { _, _, _ in
    let show = SDLShow(withTitle: "line1", message1: "line2", message2: "line3", alignment: .left_ALIGNED())
    show.graphic = SDLImage(name: imageName, of: .dynamic())
    self.sdlManager.send(show)
}
```

**Comment by joeljfischer** [comment]
Hi @poborin, thanks for making this issue. Has this worked before and a recent update is causing it to not work? Is the file manager completion handler coming back with any sort of an error? Is the Show?

**Comment by poborin** [comment]
Hi Joel,

I'm not sure if it was working in previous SDL versions. The file manager does not return any error neither Show rpc response.

**Comment by joeljfischer** [comment]
We've done testing and the issue appears to be limited to the Ford ecosystem and is not an SDL issue, we've reported the issue to the Ford team and will close this issue. You can see this by testing against [Manticore](https://smartdevicelink.com/resources/manticore/). We'd recommend shortening the name of the file for now.

**Comment by poborin** [comment]
Hi Joel,

I think this is wrong. SDL SDK should prompt an error at least. There is no visibility whenever Ford supports it or not. 

On the top of my head I do not remember anything in the doc that saying "the image name should not be longer then x characters". And even if it does then I definitely expect an error form the SDK.

**Comment by brettywhite** [comment]
Hi @poborin,

We had a discussion about this today while discussing this issue. SDL itself acts as a proxy between the mobile application and the head unit. The limitation here in particular isn't a limitation of SDL but a limitation of the QNX filesystem that Sync is built on. We are going to add comments on the affected classes such as `SDLFile` and `SDLArtwork` that if building for that system that you will be expected to adhere to its limitations. It would not be suitable for the library to make this warning for a developer if the system the are connecting to *does* allow longer file names. It is up to the implementor of core / hmi to return clear warnings for their implementation of the system. 

I hope this helps bring some clarity.

**Comment by poborin** [comment]
Hi Brett,

Thanks for the comment. It sounds much more clear now.
