### ISSUE TITLE
Proxy Crash on Accessory Disconnect

### ISSUE THREAD

**Issue by davidswi** [smartdevicelink/sdl_ios#642]
### Bug Report
If an EAAccessoryDidDisconnect notification occurs while there is an active control session, the following code path is taken:
1. The SDLIAPTransport:sdl_accessoryDisconnected: method is called by the OS
2. The sdl_accessoryDisconnected method calls [self disconnect]
3. The disconnect method  only checks for and closes an open data session, leaving the control session and its streams open
4. The sdl_accessoryDisconnected: method calls the SDLTransportDelegate:onTransportDisconnected method, which recycles the proxy
5. Any incoming stream event on the control session will now reference deallocated objects, causing a crash

##### Reproduction Steps
1. Connect iOS device to SDL compatible headunit. Best is iOS10.x device which will automatically launch compatible SDL apps and cause multiple SDL connections.
2. When the control session is opened, disconnect the iOS handset. Our head units do this programmatically under certain circumstances to switch from USB host to device mode.
3. Check the iOS device crash log

##### Expected Behavior
No crashes

##### Observed Behavior
SDL apps will crash under the conditions described above

##### OS & Version Information
* iOS Version: 9.x and 10.x
* SDL iOS Version: master 4.6RC2
* Testing Against: Internal head unit samples

**Comment by brettywhite** [comment]
Hi @davidswi 

Is there a particular step you are taking to know when the control session is opened? I am having a difficult time thinking of a good way that doesn't use the iOS 11 Beta with the TCP Debugging.

**Comment by davidswi** [comment]
Yes, I am using NSLogger.

**Comment by joeljfischer** [comment]
Hi @davidswi Can you confirm this on the current `develop`. When tracing the code, I'm seeing `SDLIAPTransport disconnect` with the following code:

```objc
[SDLDebugTool logInfo:@"IAP Disconnecting" withType:SDLDebugType_Transport_iAP toOutput:SDLDebugOutput_All toGroup:self.debugConsoleGroupName];
    // Stop event listening here so that even if the transport is disconnected by the proxy
    // we unregister for accessory local notifications
    [self sdl_stopEventListening];
    if (self.controlSession != nil) {
        [self.controlSession stop];
        self.controlSession.streamDelegate = nil;
        self.controlSession = nil;
    } else if (self.session != nil) {
        [self.session stop];
        self.session.streamDelegate = nil;
        self.session = nil;
    }
```

it appears these were merged after this bug report was submitted.

**Comment by joeljfischer** [comment]
Due to comments made here and lack of activity, I'm closing this issue. If this is not resolved, please reopen and provide additional information.
