### ISSUE TITLE
SDL iOS Proxy deadlocks when attempting to stop off the main thread

### ISSUE THREAD

**Issue by davidswi** [smartdevicelink/sdl_ios#643]
### Bug Report
When the IO stream thread was added to handle reads and writes outside the main run loop without the iAP transmit dispatch queue workaround, the `SDLIAPSession:stop:` method was modified to check for the data session, cancel the stream thread and wait on a `dispatch_semaphore`. This code assumed stop would *always* be called from the main thread. However, when there is a `NSStreamEventEnd` or `NSStreamEventError` event sent to the `SDLStreamDelegate:stream:handleEvent` method, the `stop` method is called before the `SDLIAPTransport:retry_establishSession:` is called, and the events are signaled on the stream thread, causing the stream thread to be canceled and the `dispatch_semaphore_wait()` call being made on the stream thread. The wait call fails because it is on the same thread as the signal call. This will deadlock for 1s causing the stream thread cancel to fail. 

The OS will also post the `EAAccessoryDidDisconnect` notification on the main thread. This will always happen, but it is not deterministic as to whether the notification will occur before or after the stream end event is triggered. The data session should only be cleaned up once and the safest way to do that is from the `EAAccessoryDidDisconnect` notification handler. 

We could dispatch the session stop call to the main thread from the `SDLStreamDelegate` handler, but this does not address the design principle of only one data session cleanup. I believe it is safe to assume the stream will only end on an accessory disconnect. From the Apple stream documentation at https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/NetworkingTopics/Articles/UsingSocketsandSocketStreams.html

If the other end of the connection closes the connection:

Your connection `delegate`’s `stream:handleEvent:` method is called with `streamEvent` set to `NSStreamEventHasBytesAvailable`. When you read from that stream, you get a length of zero (0).
Your connection delegate’s stream:handleEvent: method is called with `streamEvent` set to `NSStreamEventEndEncountered`.
When either of these two events occurs, the delegate method is responsible for detecting the end-of-file condition and cleaning up.

For the stream error handler, we do need to stop the session. I believe the correct approach here is to check in the `SDLIAPSession:stop:` method whether we are being called on the stream thread and if so, we can directly close the streams and end our thread.

##### Reproduction Steps
1. Launch SDL app and connect to SDL compatible accessory
2. Disconnect during SDL communication. Reconnect within a few seconds.
3. Repeat 2 until communication fails.

##### Expected Behavior
Communication should not fail.

##### Observed Behavior
The iOS console log shows Error: failed to cancel stream thread, followed by a crash due to the stream delegate calling a dealloc'ed object or a crash in the iap2d process.

##### OS & Version Information
* iOS Version: Reproduces on 8.x, 9.x and 10.x. Most easily reproduced on 10.x due to automatic app connection to compatible accessories.
* SDL iOS Version: Master, 4.6RC2
* Testing Against: Internal head unit engineering samples.

**Comment by brettywhite** [comment]
I wonder if [this](https://github.com/smartdevicelink/sdl_ios/issues/637) bug is associated with this

**Comment by joeljfischer** [comment]
@davidswi Any ideas if #637 is related?
