### ISSUE TITLE
[SDL 0075] OEM specific Human Interface Device support as Plug-in architecture in SDL proxy

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#664]
Proposal: [OEM specific Human Interface Device support as Plug-in architecture in SDL proxy](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0075-HID-Support-Plug-in.md)

> Many OEM head units (ex. Lexus Remote Touch, Mazda Commander Control, BMW Gesture Control, Audi MMI) do not support direct touch interaction, but rather support a focus and select model driven by physical controls. This proposal describes a proxy plug-in interface that models the physical controls as HID devices with OEM-specific plug-in implementations. Note: From conclusion in Steering Committee, this proposal was changed to alt#1 (specify proper RPC, not plug-in architecture).

Review: https://github.com/smartdevicelink/sdl_evolution/issues/219

Steering Committee Decision:

> The Steering Committee has agreed to move forward with a revised version of Alternative 1 for this proposal, and focus on RPC changes only.  While this would typically warrant "returning for revisions," the Steering Committee has decided to make an exception and "accept with revisions" so that the feature can meet the deadline to be contained within the Core 4.4 Release.

This proposal has been accepted with the following revisions, to be made by the Xevo team:

- Alternative 1 will be the planned approach, with focus only on RPC changes - a separate proposal describing a fuller structure around proxy implementation should be entered at a later date
- Add ID to `SpatialStruct`
- Change `HapticSpatialData` array from mandatory to optional
- Increase the maximum size of the `HapticSpatialData` array (to at least 100, possibly 999)
- Add the following to the description of `SendHapticData` RPC: when a request is sent, if successful, it will replace all spatial data previously sent through RPC

These changes have now been reflected in .md file.

**Comment by joeygrover** [comment]
Updated with [evolution pull request.](https://github.com/smartdevicelink/sdl_evolution/pull/234).
Add a single param to the `VideoStreamingCapability` struct:

```xml
    <struct name="VideoStreamingCapability">
        <description>Contains information about this system's video streaming capabilities.</description>
        ....
        <param name="hapticSpatialDataSupported" type="Boolean" mandatory="false">
            <description>True if the system can utilize the haptic spatial data from the source being streamed. </description>
        </param>
    
    </struct>

```
