### ISSUE TITLE
Crashes in SDLURLRequestTask.m Due to Self Retain Cycles in Blocks

### ISSUE THREAD

**Issue by davidswi** [smartdevicelink/sdl_ios#665]
### Bug Report
If the SDL app uses SDLURLRequestTask to download lock screen icon, etc. it can crash during cycling the connection to the head unit.

##### Reproduction Steps
1. Pair iOS device to SDL head unit over Bluetooth
2. Launch SDL media app and wait for HU UI to become active and music to play
3. Connect to HU over USB and wait for HU UI and audio to resume
4. Disconnect USB and wait for HU to reconnect over BT

##### Expected Behavior
The SDL app resumes through an arbitrary number of connection cycles.

##### Observed Behavior
The SDL app will crash. See attached crash log.

##### OS & Version Information
* iOS Version: iOS10.3.2
* SDL iOS Version: 4.6RC2
* Testing Against: Engineering sample head unit

The SDL example app should also exhibit the crash.
[CTSMediaApp1  7-26-17, 4-59 PM.crash.zip](https://github.com/smartdevicelink/sdl_ios/files/1178594/CTSMediaApp1.7-26-17.4-59.PM.crash.zip)

**Comment by brettywhite** [comment]
fixed in #678
