### ISSUE TITLE
Crash in iOS Proxy Due to NSException on Corrupted Protocol Header

### ISSUE THREAD

**Issue by davidswi** [smartdevicelink/sdl_ios#671]
### Bug Report
During automated USB/BT connection switching with an engineering sample head unit, the following NSException in SDLProtocolHeader.m was triggered:
       NSString *reason = [NSString stringWithFormat:@"The version of header that is being created is unknown: %@", @(version)];
            @throw [NSException exceptionWithName:NSInvalidArgumentException reason:reason userInfo:@{ @"requestedVersion": @(version) }];

##### Reproduction Steps
1. Set connect/disconnect duty cycle to 30s on programmable USB hub
2. Pair and connect over BT an iOS device with one or more SDL apps installed
3. Launch an SDL media app and an SDL non-media app from the HU
4. Start connect/disconnect testing

##### Expected Behavior
The apps don't crash even when a disconnection occurs in the middle of SDL communication.

##### Observed Behavior
The above exception is thrown within an hour of automated tests starting.

##### OS & Version Information
* iOS Version: 8.4.1
* SDL iOS Version: 4.6RC2
* Testing Against: Pre-production head unit

##### Test Case, Sample Code, and / or Example App
This should be reproducible with the SDL example app by the above methodology.

[CTSScreensApp  7-30-17, 12-56 PM.crash.zip](https://github.com/smartdevicelink/sdl_ios/files/1185969/CTSScreensApp.7-30-17.12-56.PM.crash.zip)

**Comment by joeljfischer** [comment]
This should be fixed in v4.7.0
