### ISSUE TITLE
Control Session Contention following Accessory Connect Event

### ISSUE THREAD

**Issue by davidswi** [smartdevicelink/sdl_ios#684]
### Bug Report
The SDL iOS proxy attempts to avoid control session collisions by computing an app name hash-based delay. However, when there are several SDL apps installed on the iOS device, there is a likelihood they will have delays that are spaced by less than a second, and quite often, the control session is in use for at least a second. When this occurs, one app will be lucky and several will hit the "control session failed" code path that leaves the proxy inert because the retry count has reached the limit of 1. This scenario is reproducible on iOS8.x and 9.x, but is most easily demonstrated on iOS10 and above because of the automatic app launch feature added in iOS10. This feature causes all of the SDL compatible apps to launch at the same time on the accessory connect event and run through their delayed connect code.

##### Reproduction Steps
1. Install multiple SDL apps on an iOS device
2. For iOS < 10.x, launch the apps and background them before connecting to the head unit
3. Connect to the head unit

##### Expected Behavior
All apps should connect and launch successfully

##### Observed Behavior
Apps with connection delays less than a second apart will collide trying to open the control session and fail to launch. Here's an example with two internal apps:
Aug 2 13:01:22 iPhone7S-1032-0002 CTSScreensApp(SmartDeviceLink)[435] <Notice>: [1] Accessory Connected, Opening in 8.067s
Aug 2 13:01:22 iPhone7S-1032-0002 CTSMediaApp1(SmartDeviceLink)[436] <Notice>: [1] Accessory Connected, Opening in 8.750s
Aug 2 13:01:30 iPhone7S-1032-0002 CTSScreensApp(SmartDeviceLink)[435] <Notice>: [1] Control Session Failed
Aug 2 13:01:31 iPhone7S-1032-0002 CTSMediaApp1(SmartDeviceLink)[436] <Notice>: [1] Control Session Failed

##### OS & Version Information
* iOS Version: 8.x, 9.x, 10.x
* SDL iOS Version: 4.6RC2
* Testing Against: Engineering sample head units

##### Test Case, Sample Code, and / or Example App
The SDL Example App will demonstrate this behavior if on a phone with apps having very closely spaced connection delays.

**Comment by joeljfischer** [comment]
Unfortunately, this can't be fixed in the current implementation, as other implementations rely on it. It has, however, been fixed if the app and head unit support MultiSession IAP connections. https://github.com/smartdevicelink/sdl_ios/pull/667
