### ISSUE TITLE
iOS Proxy Library Crash when attempting to connect with SDL core on develop branch

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_ios#696]
### Bug Report
The current iOS library is crashing when attempting to connect to SDL Core on the develop branch.  The crash appears to be related to the existing core implementation of the v5 protocol version negotiation.  
**Side Note:**
Please keep in mind that the version negotiation implementation for protocol v5 from a SDL core standpoint needs to be backwards compatible with existing iOS proxy libraries that already exist in the field.

##### Reproduction Steps
Build and run the current develop branch of sdl core
Try to connect an iOS SDL enabled application using the TCP transport
Take note that the iOS app crashes, take note of the following entry in the crash logs:
``Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The version of header that is being created is unknown: 5'
``
Next build the master branch of SDL core and connect the same iOS SDL enabled app
Take note that the app connects successfully with no issue.

##### Expected Behavior
The SDL enabled app connects successfully with the develop branch of SDL core with no issues.

##### Observed Behavior
Crash upon connection with the current develop branch of sdl core. Likely due to the following entry in the iOS Library:
https://github.com/smartdevicelink/sdl_ios/blob/cf2b4a7fc59e8a87f92c7a602b1e7f13af9714c1/SmartDeviceLink/SDLProtocolHeader.m#L62

##### OS & Version Information
* iOS Version: 10.3.3
* SDL iOS Version: 4.6.1
* Testing Against: SDL Core Develop branch, Sample iOS app.

**Comment by joeljfischer** [comment]
This is already fixed on v4.7.0, but it shouldn't be appearing on previous versions either. Core v4.4 should have an updated version negotiation that mitigates this. @joeygrover @jacobkeeler @JackLivio we need to investigate why the updated version negotiation isn't working before 4.4 ships. This is actually a Core issue.

**Comment by joeygrover** [comment]
It is both an iOS and Core issue. iOS should be able to handle getting a newer version that it supports during that negotiation.

**Comment by joeljfischer** [comment]
The iOS issue has been resolved for future versions as of v4.7, but Core v4.4's new version negotiation is designed to mitigate this exact issue. If it isn't currently doing so, it's a core issue.

**Comment by joeygrover** [comment]
It is not in place to mitigate this issue. It is a new version negotiation scheme, but the library should have been able to handle it.

**Comment by joeljfischer** [comment]
In either case, Core should be returning v4 in this case because the iOS proxy won't be sending any constructed payloads.

**Comment by joeygrover** [comment]
Correct, hence why it was an issue for both which has been brought with the Core team.

**Comment by mrapitis** [comment]
I will write up a core issue to complement this issue.

**Comment by joeljfischer** [comment]
Fixed on Core
