### ISSUE TITLE
[Proposal] Change to Major Version Zero

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#71]
The library is in a state at this point that it is inevitable that we will be changing public apis, as nearly every API is public. This is not ideal for the [semantic versioning](http://semver.org/) structure currently employed by this project.

However, there is a loophole. Point 4 of Semver states:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I realize that version 3.0.0 is where we started the project, but I believe the state of the project is really a version zero state.

So I propose that we change our versioning, existing tags will be shifted to be v0.1.0, v0.1.1, and v0.1.2 respectively. At such a time that the API is stable, we can revisit tagging the project as v1.0.0.

Note: By project, I mean the iOS Proxy, not Core, the Protocol, or any other component of SmartDeviceLink.

**Comment by devcurmudgeon** [comment]
If you do this, don't you risk that all your downstream users have their history re-written too? In which case their ability to trace/understand what has actually happened in future will likely be affected. 

Might be safer to park the current repo(s) and start fresh with new versioning? That way new consumers get something that makes sense, and existing ones get to consider whether to migrate or stay with what they have.

**Comment by joeljfischer** [comment]
No git history will be rewritten. Only the tag names. Since the history is not yet used for something like Cocoapods, where the user has to actively write out the version number they want, this is the best and only time we could do this.

**Comment by devcurmudgeon** [comment]
OK fair enough :-)

**Comment by joeljfischer** [comment]
Thanks for the comment and helping me clear up some confusion!
