### ISSUE TITLE
Why does iAP transport implement randomness into the retry strategy?

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#72]
Generally determinism is better. What's up with the randomness (between 0 and 0.5 sec)? Why not just implement a single retry delay?

```objc
//Begin Connection Retry
                float randomNumber = (float)arc4random() / UINT_MAX; // between 0 and 1
                float randomMinMax = 0.0f + (0.5f-0.0f)*randomNumber; // between Min (0.0) and Max (0.5)
```

**Comment by justinjdickow** [comment]
We now know that the randomness is needed to prevent multiple apps from competing for the same external accessory session
