### ISSUE TITLE
Some getters do not return nil when they have not been set

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_ios#75]
For each of the non-enum RPC classes, there will sometimes be one or more properties of a type that is a subclass of `SDLRPCStruct` (e.g. `SDLImage`). If any of the getters for these properties are called when the property has not been set, then, instead of returning `nil`, the getter will return an object of the appropriate type initialized with a dictionary of `nil`.

Example:
```objc
-(SDLImage*) image {
    NSObject* obj = [store objectForKey:NAMES_image];
    if ([obj isKindOfClass:SDLImage.class]) {
        return (SDLImage*)obj;
    } else {
        return [[SDLImage alloc] initWithDictionary:(NSMutableDictionary*)obj];
    }
}
```

If `image` was not previously set, then `obj` will equal `nil`. Because of this, the second return statement will run, and it will return `[[SDLImage alloc] initWithDictionary:nil]`. 

As a result of the `nil` dictionary, if the user tries to edit this object directly from the getter reference in any way, nothing will happen. The user will have no way of knowing this, as they cannot check whether the internal dictionary is `nil`. This would result in some very hard to diagnose errors.

Example:
```objc
SDLChoice* choice = [[SDLChoice alloc] init];
SDLImage* image = choice.image;
if (image != nil) {
    image.imageType = [SDLImageType STATIC];
    NSLog(@"%@", image.imageType); //"nil"
}
```

To fix this, a `obj == nil` check could be added to each of these getters as such:
```objc
-(SDLImage*) image {
    NSObject* obj = [store objectForKey:NAMES_image];
    if (obj == nil || [obj isKindOfClass:SDLImage.class]) {
        return (SDLImage*)obj;
    } else {
        return [[SDLImage alloc] initWithDictionary:(NSMutableDictionary*)obj];
    }
}
```

**Comment by justinjdickow** [comment]
@adein @asm09fsu @joeljfischer 

We would like to review this issue with you guys
