### ISSUE TITLE
[SDL 0099] New remote control modules (LIGHT, AUDIO, HMI_SETTINGS) and parameters (SIS Data)

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#755]
Proposal: [New remote control modules (LIGHT, AUDIO, HMI_SETTINGS) and parameters (SIS Data)](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0099-new-remote-control-modules-and-parameters.md)

> SDL remote control provides the ability for mobile applications to control certain components of the vehicle, such as, tune the radio, set the desired temperature or change the fan speed. However, currently only `CLIMATE` and `RADIO` modules are available for remote-control. Mobile application developers need more than basic climate or radio control. To meet developers' requirements, we propose to add three new modules (`AUDIO`, `LIGHT`, `HMI_SETTINGS`) and some new parameters (heatedXXXEnable and radio sisData) to the existing `CLIMATE` and `RADIO` modules respectively. This proposal only defines new data types and new parameters added to the existing data types. It does not add or change any remote control RPCs.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/296

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions. The author will revise the proposal to fix a few typos, as well as include descriptions for the groups of lights - listing which single light elements they typically include. It was also noted that limiting the scope of proposals, especially those related to Remote Control, in the future will help to make for easier understanding and discussion among SDLC Members.
>Proposal has now been revised to include the descriptions and fix the typos mentioned.

**Comment by theresalech** [comment]
This feature is revised by [SDL 0182](https://github.com/smartdevicelink/sdl_ios/issues/1022)

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [Revise SDL-0099 - New remote control modules](https://github.com/smartdevicelink/sdl_evolution/pull/572).  Implementation will need to be revised to remove the duplicate structs and reuse `GPSData` and `RGBColor`.

@joeljfischer I believe this change is already incorporated in this implementation.  Can you please confirm?

**Comment by jordynmackool** [comment]
Proposal file has been updated per the revisions in  [this accepted PR](https://github.com/smartdevicelink/sdl_evolution/pull/601/files).
