### ISSUE TITLE
Embedded IBDocument Error

### ISSUE THREAD

**Issue by Toyota-BSalahat** [smartdevicelink/sdl_ios#759]
### Bug Report
The proxy framework is causing the following compile error on the latest version of Xcode.
I think the "Builds for" flag on the SDLLockScreen storyboard needs to be set to "iOS 7 and later".

> SDLLockScreen.storyboard: error: Illegal Configuration: Compiling IB documents for earlier than iOS 7 is no longer supported.

##### Reproduction Steps
1. Install iOS proxy via cocoapods
2. Compile project

##### Expected Behavior
No compile errors are thrown from the iOS proxy

##### OS & Version Information
* Xcode Version: Version 9.0 (9A235)
* iOS Version: Deployment target iOS 9
* SDL iOS Version: 4.6.1

**Comment by brettywhite** [comment]
Xcode 9 compatibility was added in [4.7.1](https://github.com/smartdevicelink/sdl_ios/releases/tag/4.7.1) Though there have been a few minor enhancements since then so I suggest you take a look at 4.7.3

**Comment by Toyota-BSalahat** [comment]
@brettywhite are 4.7.1/4.7.3 available via Cocoapods? 4.6.1 is the version I am getting when I pull down the framework with no version specifier.

**Comment by brettywhite** [comment]
Yes sir, https://cocoapods.org/pods/SmartDeviceLink shows 4.7.3 as the latest

```ruby
target 'MyApp' do
  pod 'SmartDeviceLink', '~> 4.7'
end
```
Maybe you need to `pod update` for that repo to refresh?

**Comment by Toyota-BSalahat** [comment]
Got it. Clearing the podfile and doing a full install cleared it up. Thanks!
