### ISSUE TITLE
[SDLRPCStruct initWithDictionary] does not check for a nil dictionary

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_ios#76]
In [SDLRPCStruct initWithDictionary], there is no check whether the passed in dictionary is `nil`.
```objc
-(id) initWithDictionary:(NSMutableDictionary*) dict {
	if (self = [super init]) {
		store = dict;
	}
	return self;
}
```

This means that if any such object is initialized with a `nil` dictionary, then its properties cannot be edited.

There should be a check to see whether the passed in dictionary is `nil`, and if it is, then `store` should just be initialized with an empty dictionary.

```objc
-(id) initWithDictionary:(NSMutableDictionary*) dict {
	if (self = [super init]) {
		if (dict == nil) {
			store = [[NSMutableDictionary alloc] init];
		} else {
			store = dict;
		}
	}
	return self;
}
```

See also: #75

**Comment by joeljfischer** [comment]
Could use `-initWithDictionary` which if passed nil will create an empty dict.
