### ISSUE TITLE
Video Streaming does not start if a Video Capability Response is returned

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#763]
### Bug Report
When a video capability response is returned, the preferred formats and the preferred resolutions are saved with an incorrect key value. When it is time to check for the preferred video format, the check always fails because the key is incorrect. The naming conventions should follow the spec outlined in [SDL Proposal 0058](https://github.com/smartdevicelink/sdl_evolution/blob/5783a5d72ce80b0a24261e49f63da64765e29c2e/proposals/0058-video-streaming-capabilities.md)

In the `SDLNames` class, the key values should be changed from: 
```
SDLName const SDLNameVideoCodec = @"videoCodec"; // Incorrect
SDLName const SDLNameVideoProtocol = @"videoProtocol"; // Incorrect
```

to the following:
```
SDLName const SDLNameVideoCodec = @"codec";
SDLName const SDLNameVideoProtocol = @"protocol";
```

##### Reproduction Steps
1. Connect the Streaming Video example app to Core 4.4
2. Attempt to play the video

##### Expected Behavior
A video start service should be sent

##### Observed Behavior
A video start service is never sent, and the following error makes the video manager transition to state stopped.
>No preferred format or no preferred resolution found that works

##### OS & Version Information
* iOS Version: 11
* SDL iOS Version: 5.0.0
* Testing Against: Streaming Media Example app
* SDL Core Version: 4.4

**Comment by joeljfischer** [comment]
@NicoleYarroch does this also need fixing on v4.7.X?
