### ISSUE TITLE
Video streaming does not resume after app is backgrounded

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#776]
### Bug Report
When a video streaming app is backgrounded and then foregrounded during the same session, video streaming fails because the `VTCompressionSessionEncodeFrame` in the `SDLH264VideoEncoder` class fails with the error `-12903` (`kVTInvalidSessionErr`) . This bug might be fixed by creating a new compression session.
 
##### Reproduction Steps
1. Connect SDL_Video_Ex app to a TDK using using an iAP connection
1. Bring app to foreground and start video (if necessary)
1. Background app by pressing on home button
1. Bring app back to the foreground and start video (if necessary)

##### Expected Behavior
Video will resume

##### Observed Behavior
Video never resumes 

##### OS & Version Information
* iOS Version: iOS 11
* SDL iOS Version: 5.0.0 & 4.7.
* Testing Against: SDL_Video_Ex and a TDK (SYNC 3.0) using a iAP connection

**Comment by NicoleYarroch** [comment]
I attempted to reset the compression session if a `kVTInvalidSessionErr` was returned, but this hack did not work.

**Comment by joeljfischer** [comment]
The video session should be being restarted. In `didEnterAppStateInactive` it sets the `shouldRestartVideoStream` property to YES, and when in `didEnterStateAppActive` it calls `sdl_startVideoSession` which has the code:

```objc
if (self.shouldRestartVideoStream && [self.videoStreamStateMachine isCurrentState:SDLVideoStreamStateReady]) {
        SDLLogV(@"Video needs to be restarted. Stopping video stream.");
        [self sdl_stopVideoSession];
        return;
    }

    if ([self.videoStreamStateMachine isCurrentState:SDLVideoStreamStateStopped]
          && self.isHmiStateVideoStreamCapable) {
        [self.videoStreamStateMachine transitionToState:SDLVideoStreamStateStarting];
    } else {
        SDLLogE(@"Unable to send video start service request\n"
                "Video State must be in state STOPPED: %@\n"
                "HMI state must be LIMITED or FULL: %@\n",
                self.videoStreamStateMachine.currentState, self.hmiLevel);
    }
```

which should restart the video session.

**Comment by NicoleYarroch** [comment]
Ok, I reverted the code in `didEnterStateAppActive` and it looks like the problem is that the video stream state transitions to state stopped:
```
if ([self.videoStreamStateMachine isCurrentState:SDLVideoStreamStateStopped]
          && self.isHmiStateVideoStreamCapable) {
        [self.videoStreamStateMachine transitionToState:SDLVideoStreamStateStarting];
}
```
but then the video stream is not restarted so no video is sent to Core.

**Comment by NicoleYarroch** [comment]
I tested this on iOS 10 and did not have this issue; video resumes fine after the app is backgrounded and then foregrounded.

**Comment by joeljfischer** [comment]
Then it may simply be an iOS 11 issue. We ran into several here. Keep the issue open but make a tag for iOS level issues.

Thanks,
Joel Fischer
________________________________

**Comment by NicoleYarroch** [comment]
I tested this on iOS 11.1 beta and it seems to have been fixed; video resumes fine after the app is backgrounded and then foregrounded. It must be an iOS 11.0 issue.

**Comment by NicoleYarroch** [comment]
I turned the iOS 11 phone off and on and now I do not have this problem any more. At some point we need to add error handling for the `kVTInvalidSessionErr` that tells you to shutdown and restart the phone.
