### ISSUE TITLE
SDLJsonEncoder, SDLJsonDecoder, SDLDecoder.h, and SDLEncoder.h should be removed.

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#8]
SDLJsonEncoder and Decoder classes add unnecessary complexity and improperly built singletons to call a single line of code

``` objc
NSData* jsonData = [NSJSONSerialization dataWithJSONObject:dict options:kNilOptions error:&error];
```

The error is ignored in both cases.  It also defines two protocols, that are only used in those classes (Defined in SDLDecoder.h and SDLEncoder.h)

SDLDecoder.h and SDLJsonDecoder can be removed and the line

``` objc
NSDictionary* rpcMessageAsDictionary = [[SDLJsonDecoder instance] decode:self.payload];
```

can be replaced in SDLV1ProtocolMessage and SDLV2ProtocolMessage with

``` objc
NSDictionary *jsonObject = [NSJSONSerialization JSONObjectWithData:msgBytes options:kNilOptions error:nil];
```

The same can be applied to SDLJsonEncoder, and the one class which calls its encode message

**Comment by joeljfischer** [comment]
Should be deprecated in a 4.X release.
