### ISSUE TITLE
appHMIType in SDLLifecycleConfiguration is not an array

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#802]
### Bug Report
appHMIType in SDLLifecycleConfiguration is not an array

appHMIType in SDLLifecycleConfiguration is not an array. According to RegisterAppInterface RPC, it should be an array.

https://github.com/smartdevicelink/sdl_ios/blob/7f05c73cc0d7359cbc486e803891c6f12fd96750/SmartDeviceLink/SDLLifecycleConfiguration.h#L87
https://smartdevicelink.com/en/guides/android/remote-procedure-calls/registerappinterface/

##### OS & Version Information
* iOS Version: all
* SDL iOS Version: 5.0.0 and earlier

**Comment by joeljfischer** [comment]
Closed for #851
