### ISSUE TITLE
Audio stream is not stopped at hmi level none and background

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#803]
### Bug Report
Audio stream is not stopped when hmi level are changed to none or background from limited or full.
According to this guide, audio streaming is only allowed at hmi level limited and full.
https://smartdevicelink.com/en/guides/iOS/mobile-navigation/audio-streaming/

##### Reproduction Steps
1. Start SDL app (appHMIType = Navigation) and connect to SDL core
2. Change HMI level to full
3. Change HMI level to background or none

##### Expected Behavior
Audio streaming and video streaming are stopped 

##### Observed Behavior
Audio streaming is not stopped. Only video streaming is stopped.

##### OS & Version Information
* iOS Version: 11.1.2
* SDL iOS Version: 5.0.0-rc3
* Testing Against: Our in-house testing SDL HMI devboard

##### Test Case, Sample Code, and / or Example App
PR will be created.

**Comment by joeljfischer** [comment]
This does not seem to have been fixed in the AudioStreamManager
