### ISSUE TITLE
SDLAddCommand init with nil iconValue / iconType results in lifecyclemanager.error INVALID_DATA

### ISSUE THREAD

**Issue by Invader-Zim** [smartdevicelink/sdl_ios#822]
### Bug Report
`SDLAddCommand` has only one initializer that includes `parentId`.  This initializer also includes `iconValue` / `iconType`.  However, if `iconValue` / `iconType` aren't well documented, and when passed as `nil`, `SDLManager sendRequest` fails with:
`Error Domain=com.sdl.lifecyclemanager.error Code=-1 "INVALID_DATA"`

If I replace the nil with the following:
    `iconValue:@"0" iconType:SDLImageTypeStatic`
the `sendRequest` succeeds.  Unfortunately, it is not clear what effect this will have.

##### Reproduction Steps
1. Create a SDLAddSubMenu
2. SDLManager sendRequest
3. Create a SDLAddCommand, init with parentId (of the sub menu in step 1)
4. SDLManager sendRequest

##### Expected Behavior
handler called with no error

##### Observed Behavior
handler called with NSError
Error Domain=com.sdl.lifecyclemanager.error Code=-1 "INVALID_DATA" UserInfo={NSLocalizedRecoverySuggestion=Have you tried turning it off and on again?, NSLocalizedDescription=INVALID_DATA, NSLocalizedFailureReason=}

##### OS & Version Information
* iOS Version: iOS 11
* SDL iOS Version: 5.0.0
* Testing Against: Ford Sync TDK hardware (SYNC 3, Software Version: 2.0 Build 16074_DEVTEST)

**Comment by joeljfischer** [comment]
Hi @Invader-Zim, this would have been a better question for our [SDL Slack](slack.smartdevicelink.com).

Iconname and icontype are meant to be used to display an icon next to the command name in the menu. They should be able to be nil. Can you print out the request from the handler with each scenario? Also note that you can assemble the RPC yourself and don't _need_ to use the initializer.
