### ISSUE TITLE
Change registration fails "Could not find a connection"

### ISSUE THREAD

**Issue by poborin** [smartdevicelink/sdl_ios#824]
### Bug Report
Change registration fails "Could not find a connection"

##### Reproduction Steps
1. Set a dashboard language to US_EN
2. Connect application that supports EN, EN_US and FR_CA languages
3. Start an app on the dashboard and verify that the app is displaying the EN_US strings. 
4. Change the dashboard language to FR_CA.
5. Open an app on the dashboard

##### Expected Behavior
Application shows FR_CA strings and uses FR_CA voice engine

##### Observed Behavior
Application shows FR_CA string, but uses EN_US voice engine

##### OS & Version Information
* iOS Version: 11
* SDL iOS Version: 4.7.3
* Testing Against: TDK Sync 3, 16280_DEVTEST

##### Test Case, Sample Code, and / or Example App
In the beginning I create an SDLManager with default application name and EN_US locale.

```
(lldb) po sdlManager.configuration.lifecycleConfig.appName
"Test app"

(lldb) po sdlManager.configuration.lifecycleConfig.language
EN-US
```
Application get registered successfully and appears on the screen. Then, I’m checking `sdlManager!.registerResponse!.language`. Let’s say it’s `FR_CA`, thus I send change registration request:

```
ChangeRegistration (request)
{
    appName = "Test app";
    hmiDisplayLanguage = "FR-CA";
    language = "FR-CA";
    ngnMediaScreenAppName = Test;
    ttsName =     (
        "{\n    text = Test;\n    type = TEXT;\n}",
        "{\n    text = Application;\n    type = TEXT;\n}"
    );
    vrSynonyms =     (
        "Test application",
        "Test"
    );
}

ChangeRegistration (response)
{
    resultCode = SUCCESS;
    success = 1;
}, 

Error nil
```

It’s all good until I change the dashboard language. As I have subscribed to the `SDLDidChangeLanguage` notification I send second change registration request:

```
ChangeRegistration (request)
{
    appName = "Test app";
    hmiDisplayLanguage = "EN-US";
    language = "EN-US";
    ngnMediaScreenAppName = Test;
    ttsName =     (
        "{\n    text = Test;\n    type = TEXT;\n}",
        "{\n    text = Application;\n    type = TEXT;\n}"
    );
    vrSynonyms =     (
        "Test application",
        "Test"
    );
}

ChangeRegistration (response) nil

Error Domain = com.sdl.lifecyclemanager.error 
      Code = -2 "Could not find a connection" 
      UserInfo =
      {
          NSLocalizedRecoverySuggestion = Have you tried turning it off and on again?, 
          NSLocalizedDescription = Could not find a connection, 
          NSLocalizedFailureReason = The SDL library could not find a current connection to an SDL hardware device
      }
```

**Comment by joeljfischer** [comment]
First, this is the kind of question that should be happening on our slack slack.smartdevicelink.com, as far as I can tell, this is not a bug, though certainly slightly odd behavior.

I'm a bit confused what you're attempting to do here. You're checking the language after you connect, and send a change registration, I follow you there. But then you lose me. You're _then_ watching for `SDLDidChangeLanguage`? That isn't how the flow ought to occur. You should not be sending a second change registration based on the first change. All that error you're getting means is that you are not connected yet, so far as I can tell. I'm not 100% sure why that exact error is coming up, but you should not be sending that second `ChangeRegistration` request.

**Comment by poborin** [comment]
I will try to sum it up in a few bullet-points:

- our iOS app supports three languages: EN, EN_US, FR_CA. EN is a default language, thus the app creates an SDLManager with EN language
- application checks the dashboard language once it gets a first HMI status. The dashboard language is actually FR_CA, thus app sends a Change Registration request with FR_CA localisation
- after a few minutes if the user changes a dashboard language from FR_CA to EN_US, application receives SDLDidChangeLanguage notification and sends Change Registration request with EN_US locale

Nevertheless the Change Registration response fails with "Could not find a connection" but the application is still working and can update screens on the dashboard. It shows everything in EN_US, however the voice engine is still FR_CA.

Does that make more sense?

BTW, I have posted this question on SDL Slack three times with no response. What I supposed to do?

**Comment by joeljfischer** [comment]
Sounds good, I'll try to replicate and check it out when I can.

**Comment by joeljfischer** [comment]
Possibly related: https://github.com/smartdevicelink/sdl_android/issues/558

**Comment by SatbirTanda** [comment]
Have you been able to reproduce this?  When I observe `SDLDidChangeLanguage`, the `SDLLifecycleManager` restarts.  If I am calling `self.sdlManager?.stop` in the delegate `managerDidDisconnect` I am seeing a connection error and the app is removed from the HU.  But if I do not call `self.sdlManager?.stop` in the delegate `managerDidDisconnect`, the language change observes correctly.

**Comment by NicoleYarroch** [comment]
After doing some debugging, this appears to be user error.

1. When the user changes the language in **Settings**, an `OnAppInterfaceUnregistered` notification is sent by Core. The app will reconnect automatically to Core and the `SDLManager`’s start handler is called. The `registerAppInterfaceResponse` contains the new `language` and `hmiDisplayLanguage`.

```
Unregistration forced by module. {
    notification =     {
        correlationID = 4294967295;
        name = OnAppInterfaceUnregistered;
        parameters =         {
            reason = "LANGUAGE_CHANGE";
        };
    };
}
```

2. Before the `OnAppInterfaceUnregistered` notification is sent, an `onLanguageChange` notification is by Core. This is the current language used by Core. Do **not** send a `changeRegistration` from `onLanguageChange` because the `OnAppInterfaceUnregistered` notification will be sent right after the `onLanguageChange` is sent.

3. Below is an example of how the program should flow:

```
class ProxyManager {
	private var currentLanguage: SDLLanguage = ProxyManager.defaultLanguage
	private var currentHMIDisplayLanguage: SDLLanguage = ProxyManager.defaultLanguage

	func start() {
		sdlManager.start { (success, error)
			// This is called every time the app reconnects to Core
			checkHeadUnitLanguage()
		}
	}
	
	// Send a `changeRegistration` if necessary
	func checkHeadUnitLanguage() {
		// 1. Get the current head unit `language` and `hmiDisplayLanguage` from the `registerResponse`
	
		// 2. Check if the app’s `currentLanguage` and `currentHMIDisplayLanguage` matches the head-unit’s current language and `hmiDisplayLanguage`. If so, no need to send a `changeRegistration` request. 

		// 3. Check if the head-unit’s current language is supported by the app. If not, set the app’s `currentLanguage` and `currentHMIDisplayLanguage` to the app’s default supported language. No need to send a `changeRegistration` request. 

		// 4. If the app support’s the head-unit’s current language, send a `changeRegistration` request.
	}

	// didChangeLanguage notification
	func sdlLanguageDidChange(_ notification: SDLRPCNotificationNotification) {
		// 1. Get the new `language` and `hmiDisplayLanguage` from the notification

		// 2. Check to see if the new `language` and `hmiDisplayLanguage` are supported by the app. If they are, save to the `currentLanguage` and `currentHMIDisplayLanguage` vars. If not, set  `currentLanguage` and `currentHMIDisplayLanguage` to the app’s default language. 

		// 3. Refresh the SDL UI with the new language. 

		// 4. Do not send a `changeRegistration` request when a `didChangeLanguage` notification is received.
	}
}
```

**Comment by joeljfischer** [comment]
@NicoleYarroch Can we add something to the guides about this?

**Comment by NicoleYarroch** [comment]
I will create a PR to update the SDL_iOS documentation.
