### ISSUE TITLE
SDLAddCommand iconValue of nil results in INVALID_DATA

### ISSUE THREAD

**Issue by Invader-Zim** [smartdevicelink/sdl_ios#846]
### Bug Report
SDLAddCommand needs an initializer that accepts a parentId, but does not require an iconValue or iconType; OR allow this initializer to accept nil for iconValue/iconType.

##### Reproduction Steps
1. Pass "nil" for the iconValue parameter on the SDLAddCommand initializer

```objc
(instancetype)initWithId:(UInt32)commandId vrCommands:(nullable NSArray<NSString *> *)vrCommands menuName:(NSString *)menuName parentId:(UInt32)parentId position:(UInt16)position iconValue:(NSString *)iconValue iconType:(SDLImageType)iconType handler:(nullable SDLRPCCommandNotificationHandler)handler;
```

##### Expected Behavior
Either need an additional SDLAddCommand initializer that allows a parentId but removes the iconValue/iconType, OR allow nil to be passed for iconValue/iconType on the current initializer.

##### Observed Behavior
```
Error Domain=com.sdl.lifecyclemanager.error Code=-1 "INVALID_DATA" UserInfo={NSLocalizedRecoverySuggestion=Have you tried turning it off and on again?, NSLocalizedDescription=INVALID_DATA, NSLocalizedFailureReason=}
```

##### OS & Version Information
* iOS Version: iOS 11 (but that's irrelevant)
* SDL iOS Version: 5.0.0
* Testing Against: Toyota and Ford head units - not sure of the details

**Comment by joeljfischer** [comment]
@Invader-Zim I'm not sure I'm totally understanding how not having access to an initializer is causing an `INVALID_DATA`. A does not lead to B. If the initializer doesn't work to create the exact type of object you want, that's fine and it can be fixed. But what, exactly, are you doing to cause an `INVALID_DATA` error?

**Comment by Invader-Zim** [comment]
There are too many initializers.  I don't want to set an icon, I just want to specify the parent id.  If I pass nil for the icon arguments, I get an INVALID_DATA.  Personally, I have a work around; but I'm sure you want the interface to be friendly.  If you don't want to add overload, then just make tolerate supplying nil for the icon args.

Are you saying that when you pass nil for the icon args, you DON'T get INVALID_DATA??  If so, then either I have something else going wrong on my end - or a recent update has already addressed the issue.

**Comment by joeljfischer** [comment]
Thanks @Invader-Zim, I think I'm starting to understand the issue.

I'm just trying to understand the issue here. The nullability on the initializer you mention specified that those parameters must be nonnull, so I wasn't aware you were actually using them as nullable. I think the solution will be to make those parameters nullable and allow for that use case.

**Comment by Invader-Zim** [comment]
>>solution will be to make those parameters nullable and allow for that use case
Perfect.
