### ISSUE TITLE
[iOS11.2.2]SDL start service packet with only 00s

### ISSUE THREAD

**Issue by VGunasekaranHarman** [smartdevicelink/sdl_ios#848]
### Bug Report
[Summary]
Apps not getting registered on HU from iPhones having iOS 11.2.2

[INFO]
We are producing the HU with Applink solution. Its Linux based HU. We are facing the mentioned problem when iPhones having iOS 11.2.2 are connected to the HU.

##### Reproduction Steps
1. [Step 1] Make sure that HU is ON
2. [Step 2] Please open all the Applink apps on iPhone having iOS 11.2.2
3. [Step 3] Connect iPhone having iOS 11.2.2 with the Applink apps opened

##### Expected Behavior
Apps should get registered onto HU.

##### Observed Behavior
Apps are not getting registered.

##### OS & Version Information
* iOS Version: iOS 11.2.2
* SDL iOS Version: SDL 4.2
* Testing Against: Phone connection to register the Applink apps from iPhone having iOS 11.2.2

##### Test Case, Sample Code, and / or Example App

[IOS_11.2.2_apps_not_registering_22jan18_with_mediaone_bin.zip](https://github.com/smartdevicelink/sdl_ios/files/1651864/IOS_11.2.2_apps_not_registering_22jan18_with_mediaone_bin.zip)

**Comment by VGunasekaranHarman** [comment]
Hi,
We have attached the log.
Our analysis from the log:

We are getting all the start service packets as 00s only. Due to which, there will be no start service ack from HU side.

-----------------------------------------------------------------------------------------------------------
5546 2018/01/22 15:05:03.000000 564.7764 72 ECU1 ALCO JOUR 1154 log debug verbose 1 SDLCore_4.2.091517.5022572 [1351]:[protocol_handler_impl.cc:508] :OnTMMessageReceived::Received data from TM with connection id 42 msg data_size 40
5548 2018/01/22 15:05:03.000000 564.7766 74 ECU1 ALCO JOUR 1154 log debug verbose 1 SDLCore_4.2.091517.5022572 [1351]:[incoming_data_handler.cc:80] :ProcessData::Total data size for connection 42 is 40
5549 2018/01/22 15:05:03.000000 564.7767 75 ECU1 ALCO JOUR 1154 log warn verbose 1 SDLCore_4.2.091517.5022572 [1351]:[protocol_packet.cc:127] :deserialize::Unknown version:0
5550 2018/01/22 15:05:03.000000 564.7768 76 ECU1 ALCO JOUR 1154 log debug verbose 1 SDLCore_4.2.091517.5022572 [1351]:[protocol_packet.cc:148] :validate::Validating header - Version: 0, Protection: OFF, FrameType: 0, ServiceType: 0, FrameData: 0, SessionId: 0, DataSize: 0, MessageId: 0
5551 2018/01/22 15:05:03.000000 564.7768 77 ECU1 ALCO JOUR 1154 log warn verbose 1 SDLCore_4.2.091517.5022572 [1351]:[protocol_packet.cc:165] :validate::Unknown version:0
5552 2018/01/22 15:05:03.000000 564.7769 78 ECU1 ALCO JOUR 1154 log warn verbose 1 SDLCore_4.2.091517.5022572 [1351]:[incoming_data_handler.cc:153] :CreateFrame::Packet validation failed
-------------------------------------------------------------------------------------------------------------

**Comment by VGunasekaranHarman** [comment]
Hi,
We would like to know whether any specific parameter/attribute that HU has to send to iPhones having iOS version 11.2.2 to get proper start service packet.

Thanks.

**Comment by joeljfischer** [comment]
I'm not quite sure what you mean here, but there is no special code for version 11.2.2+ on the iPhone side. SDLC members have been noting severe 11.2 iAP issues. The parent apple radar bug for this issue is 35853159.

**Comment by VGunasekaranHarman** [comment]
Hi Joeljfischer,
Thanks for the reply.
Can you please share the snapshot of bug details of bug - 35853159??
Thanks.

**Comment by joeljfischer** [comment]
Is this still occurring on 11.3 beta or 11.2.6?

**Comment by VGunasekaranHarman** [comment]
Hi @joeljfischer 

Thank you for the reply.

We are not observing this problem with 11.2.5 and above.

Thanks,
Varadha.
