### ISSUE TITLE
Remove Siphon Server

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#85]
Major version change

The siphon server cannot currently be used by developers. It requires Ford-proprietary, closed-source, Windows-only software right now. Alternatives should be discussed.

**Comment by idamaster** [comment]
Perhaps we can open source the Siphon server software, add it here, and put together a roadmap/timeline for its development/purpose/etc.

**Comment by Heath-FoMoCo** [comment]
Open sourcing the siphon software it not an option.  Siphon was develop with the purpose of Ford use only and making changes to be open source would not be beneficial.

**Comment by joeljfischer** [comment]
Honestly, in addition to that, I do believe there are better options available. My preferred one that I would like to investigate is using an open-source HTTP server to serve a webpage from the device to the local network, which could then be viewed from any web browser that [supports sockets](http://caniuse.com/#feat=websockets). We're currently awaiting feedback from the lawyers regarding the use of MIT & Apache 2.0 software in our open-source projects for this and other purposes.

This would likely be implemented as another weakly linked framework, the main framework would look for it at runtime and use it if available, and no-op if it's not there. This would also allow developers to automatically use the framework in debug builds only, which is a vast improvement.

**Comment by joeljfischer** [comment]
@Heath-FoMoCo is this still in use? Do you think that Relay supersedes it? It seems like Relay and this attempt to accomplish the same thing, but Relay does it better.

**Comment by asm09fsu** [comment]
@joeljfischer so NSLog (when compiled with iOS 10) actually uses the new Unified Logging system. This means that for now, we do not have to do special modifications to handle that, however if we'd like to improve the ability to filter, we can investigate creating a [custom log object](https://developer.apple.com/reference/kernel/1643798-os_log_create?language=objc)
