### ISSUE TITLE
Video stream is stopped and restarted immediately when app enters background

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#858]
### Bug Report
When app enters the background, video streaming should pause until the app re-enters the foreground. Currently, video streaming stops and then restarts immediately. A `SDLVideoStreamDidStart` notification is sent even when the app is in the background. 

##### Reproduction Steps
1. Connect a video streaming app (`appType` = `NAVIGATION`) to Core.
1. Once video streaming has started, put the app on the iPhone into the background.

##### Expected Behavior
The `SDLVideoStreamDidStart` notification is not sent until the app on the iPhone is brought to the foreground.

##### Observed Behavior
The `SDLVideoStreamDidStart` notification is sent while the app is still in the background.

##### OS & Version Information
* iOS Version: 11.2
* SDL iOS Version: 5.1
* Testing Against: SDL Core 4.4

**Comment by SatbirTanda** [comment]
I can't reproduce this, I'm not seeing `SDLVideoStreamDidStartNotification ` firing when the app goes to the background and I do not see `sdl_didReceiveVideoStreamStarted` being called when the app goes to the background.

**Comment by NicoleYarroch** [comment]
@SatbirTanda This was an issue reported by @Rafal on the Slack channel. Is your setup for video streaming different from the [documentation](https://smartdevicelink.com/en/guides/iOS/mobile-navigation/video-streaming/)? If so, can you post your setup here? If not, we will close this issue.

**Comment by pierzyns** [comment]
The setup is according to the documentation. I even can show you place in the code which causes the error. 
```
- (void)didEnterStateAppInactive {
    SDLLogD(@"App became inactive");
    if (!self.protocol) { return; }

    [self sdl_sendBackgroundFrames];
    [self.touchManager cancelPendingTouches];
    self.restartVideoStream = YES;
}
- (void)didEnterStateVideoStreamStopped {
    SDLLogD(@"Video stream stopped");
    _videoEncrypted = NO;
    _videoFormat = nil;

    if (_videoEncoder != nil) {
        [_videoEncoder stop];
        _videoEncoder = nil;
    }

    self.displayLink.paused = YES;
    [self.displayLink invalidate];

    [[NSNotificationCenter defaultCenter] postNotificationName:SDLVideoStreamDidStopNotification object:nil];

    if (self.shouldRestartVideoStream) {
        self.restartVideoStream = NO;
        [self sdl_startVideoSession];
    }
}
```

Function didEnterStateAppInactive is called on notification UIApplicationWillResignActiveNotification and in this function property restartVideoStream is set to yes. Then, when the video streaming stops the function didEnterStateVideoStreamStopped is called and when property restartVideoStream is set to yes the video streaming starting again.

**Comment by pierzyns** [comment]
[logs.txt](https://github.com/smartdevicelink/sdl_ios/files/1744497/logs.txt)
Here are logs from iOS SDL SDK which shows the issue

**Comment by NicoleYarroch** [comment]
I have reproduced this bug. It appears that the video and audio streams are restarted when the app re-enters the foreground. I am working on a fix.

**Comment by NicoleYarroch** [comment]
A [pull request](https://github.com/smartdevicelink/sdl_ios/pull/878) has been created to fix this bug.
