### ISSUE TITLE
Video stream fails to start since 4th reconnection

### ISSUE THREAD

**Issue by alexanderlavrushko** [smartdevicelink/sdl_ios#859]
### Bug Report
Video stream fails to start after 4th USB reconnection. After it starts reproducing, only killing the app helps.

##### Reproduction Steps
1. Start SDL-compatible navigation app on the phone
2. Connect iPhone to head-unit with USB
3. Tap the app icon on the head-unit
4. After video stream started, unplug USB
5. Repeat steps 2-4, 4 times

##### Expected Behavior
Video stream successfully starts after 4th reconnection

##### Observed Behavior
Video stream fails to start after 4th reconnection

##### Error details
Error Domain=com.sdl.streamingmediamanager.video Code=2 "(null)" UserInfo={OSStatus=-12915}

##### Note
If stop video stream using sending HMI level NONE (on head-unit Menu -> Exit app), the problem doesn't happen. USB unplug is required to reproduce.

##### OS & Version Information
* iOS Version: 9.3.4, 10.3.3, 11.1.2
* SDL iOS Version: 4.2.3 - 4.7.5
* Testing Against: Ford SYNC 3, version 2.3, version 3.0

##### Example App
https://itunes.apple.com/us/app/car-navigation-maps-traffic/id820326185?mt=8

**Comment by joeljfischer** [comment]
Hi @alexanderlavrushko Have you seen this on SDL v5.2.0?

**Comment by alexanderlavrushko** [comment]
Hi @joeljfischer On SDL v5.2.0 it doesn't happen.
Just checked a test app with SDL v5.2.0, it works like a charm. 👍 Many thanks to the team.
(checked on iPhone 5s iOS 11.3.1, Ford SYNC 3.0, 16 times reconnected USB - 16 times restarted video stream)
