### ISSUE TITLE
Better factory methods for SDLTTSChunkFactory

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#86]
See #78 

> Ideally, we should define a factory method that takes in the SDLJingle enum and automatically assume the type as PRE_RECORDED and a similar method taking in an int value for SILENCE. Developers could still mess it up via the setter methods, but it at least makes it a bit easier to comprehend in code (and gives you a reason to import that header file).

**Comment by asm09fsu** [comment]
`SDLTTSChunkFactory` has been removed in SDL 5.0 and replace with initializers in `SDLTTSChunk`.
