### ISSUE TITLE
UIViews accessed on background thread for hit testing when SDLTouchManager calls SDLTouchManagerDelegate methods

### ISSUE THREAD

**Issue by Lievesley** [smartdevicelink/sdl_ios#875]
### Bug Report
UIViews are accessed on a background thread while hit testing when SDLTouchManager calls SDLTouchManagerDelegate methods.

##### Reproduction Steps
1. Enable main thread checker.
2. Run build in debugger and use touch events with hit testing.
3. SDLTouchManager calls [SDLFocusableItemLocator viewForPoint] which accesses UIViews on background thread.

##### Expected Behavior
UIViews should only be accessed on main thread.
The SDLTouchManager should also not call SDLTouchManagerDelegate methods on a background thread since it sends UIViews which may lead the callee to try to use the UIView on the background thread.

##### Observed Behavior
UIViews accessed on background thread.

##### OS & Version Information
* iOS Version: 11.0.3
* SDL iOS Version: 5.1.1

**Comment by NicoleYarroch** [comment]
Pull Request #833 was created to fix this bug
