### ISSUE TITLE
Single tap registered as a pan gesture

### ISSUE THREAD

**Issue by Lievesley** [smartdevicelink/sdl_ios#879]
### Bug Report
If the head unit registers a small movement of the finger it is immediately recognised as a pan event instead of a single tap. This means that the iOS SDL SDK never sends our app single tap events.

##### Reproduction Steps
1. Perform single tap on head unit display
2. `[SDLTouchManager sdl_handleTouchMoved]` is called which sets
    `_performingTouchType = SDLPerformingTouchTypePanningTouch;`
3. Single tap delegate method is never called
`[strongSelf.touchEventDelegate touchManager:strongSelf didReceiveSingleTapForView:hitView atPoint:point];`

##### Expected Behavior
There should be a threshold movement level below which pan gestures are not recognised to prevent them interfering with single tap touch events.

##### Observed Behavior
Pan gesture recogniser prevents single taps from being recognised.

##### OS & Version Information
* iOS Version: 11.0.3
* SDL iOS Version: v5.1
* Testing Against: Head unit

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

**Comment by Lievesley** [comment]
I'm creating a PR that fixes this.

**Comment by Lievesley** [comment]
PR is ready for review

**Comment by brettywhite** [comment]
@Lievesley i see you removed the CLA section, before we can merge any code after it is reviewed, that needs to be signed.

**Comment by Lievesley** [comment]
@brettywhite I just added it again.
