### ISSUE TITLE
iOS App crash after logging accessory object

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_ios#886]
### Bug Report
App crash after logging accessory object. The issue was reported externally but could not be reproduced yet. Based on the stack trace it looks like the phone just got connected over USB as it was trying to create an iAP control session.

##### Reproduction Steps
1. Connect iPhone over USB
2. ¯\_(ツ)_/¯ (will be provided once we can reproduce)

##### Observed Behavior
App did crash before establishing control session.

##### OS & Version Information
* iOS Version: 11.2.5
* SDL iOS Version: 5.0.0
* Testing Against: TBD

##### Test Case, Sample Code, and / or Example App
[crash.txt](https://github.com/smartdevicelink/sdl_ios/files/1781157/crash.txt)

**Comment by joeljfischer** [comment]
Hi @kshala-ford, do we have any more information on this? Is it reproducible on 5.1.0 or 5.2.0-develop?
