### ISSUE TITLE
iOS App crash after transportDidConnect within lifecycle manager

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_ios#888]
### Bug Report
App crash after transportDidConnect within lifecycle manager. The issue was reported externally but could not be reproduced yet. My impression is that the phone was disconnected during transport connect (race condition). Needs to be verified...

##### Reproduction Steps
1. Connect iPhone over USB
2. ¯\\_(ツ)_/¯ (will be provided once we can reproduce)

##### Observed Behavior
App did crash when handling `[SDLLifecycleManager transportDidConnect]` 

##### OS & Version Information
* iOS Version: 11.2.6
* SDL iOS Version: 5.0.0
* Testing Against: TBD

##### Test Case, Sample Code, and / or Example App
[crash.txt](https://github.com/smartdevicelink/sdl_ios/files/1781285/crash.txt)

**Comment by joeljfischer** [comment]
Hi @kshala-ford, do we have any more information on this? Is it reproducible on 5.1.0 or 5.2.0-develop? Are there any steps to reproduce it. I'm not sure what could be causing this in the state machine `isCurrentState` check.
