### ISSUE TITLE
CarWindow api should allow app to manually set screen resolution

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_ios#908]
## Bug Report
CarWindow based apps currently cannot manually set their screen resolution.  The CarWindow api automatically sets the screen resolution of the projected app based on values provided by SDL cores RAI response or getsystemcapabilities response.  Existing use cases require the app to project at a screen resolution that is lower than values provided by sdl core, however currently the api does not  provide a way to allow the app to manually set a screen resolution.

**OS & Version Information**
iOS Version: n/a
SDL iOS Version: develop branch
Testing Against: n/a

**Comment by mrapitis** [comment]
To add information to the original bug report, the code linked below should allow for the app to provide a user specified screen resolution, however the user defined resolution is stored in the preferredResolutions variable which is actually not used by the video encoder to set the screen resolution.
https://github.com/smartdevicelink/sdl_ios/blob/345121aec211b26b95668cb328a5e17f24bff0d3/SmartDeviceLink/SDLStreamingMediaLifecycleManager.m#L355

Currently the VideoEncoder uses the “screenSize” variable to project the custom resolution as seen in the link below:
https://github.com/smartdevicelink/sdl_ios/blob/345121aec211b26b95668cb328a5e17f24bff0d3/SmartDeviceLink/SDLStreamingMediaLifecycleManager.m#L389

In addition, setting a user preferred screen resolution appears to be dependent on receiving a successful response for SDLVideoStreamingCapability from the head unit (see code linked below), however this also should not be the case as some head units as some head unit implementations do not support the getsystemcapabilities rpc.
https://github.com/smartdevicelink/sdl_ios/blob/345121aec211b26b95668cb328a5e17f24bff0d3/SmartDeviceLink/SDLStreamingMediaLifecycleManager.m#L347

**Comment by theresalech** [comment]
Closed via #923
