### ISSUE TITLE
SDLTCPTransport.m - connect method should report failure to the application

### ISSUE THREAD

**Issue by pierzyns** [smartdevicelink/sdl_ios#911]
### Bug Report
SDLTCPTransport.m - connect method should report failure to the application.
SDLLogE is not sufficient to correctly manage the connection.

##### Reproduction Steps
1. Connect application to a wrong address

##### Expected Behavior
iOS SDL Framework reports error through callback or NSNotification, that connection failed

##### Observed Behavior
iOS SDL Framework doesn’t give any response and stays in Connecting state

##### OS & Version Information
* iOS Version: 11.1.2 (any)
* SDL iOS Version: 5.1.1
* Testing Against: sdl emulator

##### Test Case, Sample Code, and / or Example App
```
       int sock_fd = call_socket([self.hostName UTF8String], [self.portNumber UTF8String]);
       if (sock_fd < 0) {
           SDLLogE(@“Server not ready, connection failed”);
       // should send some notification here
           return;
       }
```

**Comment by joeljfischer** [comment]
Hi, the TCP transport is very much a debug transport. It is not intended for production and so doesn't have many things that could be done to help an app (e.g. retry, report to the app that the connection failed, etc.), however, as the TCP transport will be going to production at some point with the addition of the Wi-Fi high capacity secondary transport, the entire transport will be rewritten from the ground up to provide better feedback, etc. That is to say, this will most likely be fixed when the transport is rewritten in an upcoming release, but likely not before.
