### ISSUE TITLE
Observers notified of `hmiLevel` change when it does not change

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#918]
### Bug Report
In the `SDLLifecycleManager`'s `sdl_hmiStatusDidChange:` method, observers of the `SDLManagerDelegate`'s  `hmiLevel:didChangeToLevel:` method are notified unnecessarily when the `hmiLevel` changes from `nil` to `nil`. This is due to the fact that comparing two `nil` values using `isEqualToEnum` returns `false`.   

##### Reproduction Steps
1. Connect the SDL_iOS Example app to TDK (SYNC 3)
1. The `hmiLevel:didChangeToLevel:` is called when both the old `hmiLevel` and new `hmiLevel` are `nil`.

##### Expected Behavior
The `hmiLevel:didChangeToLevel:` is **not** called when both the old `hmiLevel` and new `hmiLevel` are `nil`.

##### Observed Behavior
The `hmiLevel:didChangeToLevel:` is called when both the old `hmiLevel` and new `hmiLevel` are `nil`.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 5.2
* Testing Against: TDK (SYNC 3)

**Comment by theresalech** [comment]
Fixed via #924
