### ISSUE TITLE
Add support for observing capability updates in the SDLSystemCapabilityManager

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#925]
### Bug Report
It would be nice to get a callback when capabilities have changed in the `SDLSystemCapabilityManager`, either to observe an individual one, or a group, or all. 

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 5.2
* Testing Against: n/a

**Comment by joeljfischer** [comment]
We have a proposal that will go out for this and a new issue will be created then.
