### ISSUE TITLE
[SDL 0150] Enhancing onHMIStatus with a New Parameter for Video Streaming State

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#929]
Proposal: [Enhancing onHMIStatus with a New Parameter for Video Streaming State](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0150-video-streaming-state.md)

> This proposal adds a new parameter `videoStreamingState` to `onHMIStatus` notification so that SDL core can notify an app to stop video streaming. This helps SDL Core handle the use cases of the coexistence of a navigation app and a projection app or multiple navigation/projection apps.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/429

**Comment by joeljfischer** [comment]
Closed via #994
