### ISSUE TITLE
Segmentation Fault on Swift 4.1 + Xcode 9.3

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#936]
### Bug Report
Tidal iOS Team reports a segmentation fault occurring on Xcode 9.3 + Swift 4.1

##### Reproduction Steps
1. Use SDLTriggerSource in code 

##### Expected Behavior
App with SDL 5.2.0 builds and runs on Xcode 9.3 + Swift 4.1

##### Observed Behavior
App with SDL 5.2.0 doesn't compile on Xcode 9.3 + Swift 4.1

##### OS & Version Information
* iOS Version: Unknown
* SDL iOS Version: 5.2.0

##### Test Case, Sample Code, and / or Example App

`1.  While emitting SIL for getter for rawValue in module '__ObjC'
2.  While silgen emitFunction SIL function "@_T0SC16SDLTriggerSourceV8rawValueSC7SDLEnumVvg".
 for getter for rawValue in module '__ObjC'`

[tidalCrash.txt](https://github.com/smartdevicelink/sdl_ios/files/1933917/tidalCrash.txt)

**Comment by joeljfischer** [comment]
@SatbirTanda Do you have any further information on this? We haven't seen this issue.

**Comment by SatbirTanda** [comment]
the TIDAL team submitted their app with a build from Xcode 9.2 + Swift 4.0.  They are still receiving the error though.  Haven't been able to reproduce it.
