### ISSUE TITLE
When connected via Bluetooth, RAI should not be sent if appType is Navigation

### ISSUE THREAD

**Issue by SatbirTanda** [smartdevicelink/sdl_ios#941]
### Bug Report
When iOS is connected to a MY20 head unit via Bluetooth, RAI should not be sent for Navigation / Projection Apps 

##### Reproduction Steps
1. Add SDL to iOS App with lifeCycle.appType = SDLAppHMIType.navigation
2. Connect iPhone to MY20 head unit via Bluetooth

##### Expected Behavior
RAI is not sent if app type is Navigation

##### Observed Behavior
RAI is sent if app type is Navigation

##### OS & Version Information
* iOS Version: All
* SDL iOS Version: 5.2.0
* Testing Against: MY20 Head Unit

**Comment by joeljfischer** [comment]
This is no longer true because now there is secondary transport stuff even for bluetooth based apps. Even before, it would be on the head unit to prevent the user from using the app, as there is no way for the library to know if we are connected over Bluetooth or USB.
