### ISSUE TITLE
Permission Manager issues

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#957]
### Bug Report
1. The permission manager is not reset on disconnection. `permissions`, `filters` and `currentHMILevel` should be reset to the default values when the app disconnects from the head unit. 
2. Subscribers to permission changes will be notified unnecessarily if the new permissions for a subscribed RPC are exactly the same when an `OnPermissionsChange` notification is received. The `sdl_filterPermissionChangesForFilters` only checks for the `rpcName` and not the `hmiPermissions` and `parameterPermissions`.

##### Reproduction Steps
1. Connect an app to SDL Core. And open the SDL app.
1. Subscribe to `GetVehicleData` permissions notifications via the permissions manager.
1. Trigger an `OnPermissionsChange` notification that does not include `GetVehicleData`.

##### Expected Behavior
The subscriber should not be notified.

##### Observed Behavior
The subscriber will be notified.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 5.2
* Testing Against: n/a

**Comment by joeljfischer** [comment]
For (2), this seems like a Core bug. An `OnPermissionsChange` should only be sent when the permission *changed*, not, as this report says, "if the new permissions for a subscribed RPC are exactly the same." Perhaps I'm not understanding this correctly.

**Comment by NicoleYarroch** [comment]
> For (2), this seems like a Core bug. An OnPermissionsChange should only be sent when the permission changed, not, as this report says, "if the new permissions for a subscribed RPC are exactly the same." Perhaps I'm not understanding this correctly.

When the `OnPermissionsChange` notification is sent, it includes all of the supported RPCs, not just the RPCs whose permissions changed. If the permissions for an RPC did not change, the observer will still be notified. This is because the permission manager assumes that the notification will only include the RPCs whose permissions changed.
