### ISSUE TITLE
Verbose log level not printing verbose logs to console

### ISSUE THREAD

**Issue by Rconroy** [smartdevicelink/sdl_ios#972]
### Bug Report
Verbose log level does not print verbose logs to console. Error, warning, and debug logs print when log level is set to verbose, but verbose logs do not appear.

##### Reproduction Steps
1. Setup SDL logging.
2. Set log level to verbose.
3. print error, warning, debug, and verbose logs to console.

##### Expected Behavior
All logs (error, warning, debug, and verbose) print to console.

##### Observed Behavior
All log types besides verbose print to console.

##### OS & Version Information
* iOS Version: N/A
* SDL iOS Version: v5.1.1
* Testing Against: N/A

**Comment by joeljfischer** [comment]
Tested on 5.2 Swift & Obj-C example apps; it works correctly.
